<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/explain.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['0'] = "Du lundi au dimanche";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['1'] = "Définit à quel jour une semaine calendaire débute";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['0'] = "Uniforme";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['1'] = "La première semaine de l'année";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['0'] = "Majoritaire";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['1'] = "La première semaine de l'année a plus de trois jours dans cette année et trois au plus dans l'année précédente";
 
?>
