<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/li_settings.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_settings']['settings'] = "Réglages du CRM";
$GLOBALS['TL_LANG']['li_settings']['customers'] = "Clients";
$GLOBALS['TL_LANG']['li_settings']['customerSettings'] = "Configuration clients";
$GLOBALS['TL_LANG']['li_settings']['customerSettingsDesc'] = "Configuration générale des clients, par ex. numerotation";
$GLOBALS['TL_LANG']['li_settings']['projects'] = "Projets";
$GLOBALS['TL_LANG']['li_settings']['projectSettings'] = "Configuration des projets";
$GLOBALS['TL_LANG']['li_settings']['projectSettingsDesc'] = "Configuraton générale des projets, par ex. comment ils sont numérotés";
$GLOBALS['TL_LANG']['li_settings']['services'] = "Services";
$GLOBALS['TL_LANG']['li_settings']['serviceTypes'] = "Types de services";
$GLOBALS['TL_LANG']['li_settings']['serviceTypesDesc'] = "Les types de services sont utilisés pour faciliter la recherche et l'archivage";
$GLOBALS['TL_LANG']['li_settings']['products'] = "Produits";
$GLOBALS['TL_LANG']['li_settings']['productTypes'] = "Types de produits";
$GLOBALS['TL_LANG']['li_settings']['productTypesDesc'] = "Les types de produits sont utilisés pour faciliter la recherche et l'archivage";
$GLOBALS['TL_LANG']['li_settings']['tasks'] = "Tâches";
$GLOBALS['TL_LANG']['li_settings']['taskStatus'] = "Etat d'avancement";
$GLOBALS['TL_LANG']['li_settings']['taskStatusDesc'] = "Permet de definir l'etat d'avancement d'une tâche.";
$GLOBALS['TL_LANG']['li_settings']['taskReminderSettings'] = "Paramètres de rappel des tâches";
$GLOBALS['TL_LANG']['li_settings']['taskReminderSettingsDesc'] = "Paramètres généraux du rappel des tâches, exemple : E-mail destinataires";
$GLOBALS['TL_LANG']['li_settings']['timekeeping'] = "Gestion du temps";
$GLOBALS['TL_LANG']['li_settings']['workingHours'] = "Horodatage";
$GLOBALS['TL_LANG']['li_settings']['workingHoursDesc'] = "Configuration générale du temps de travail, exemple : Début de semaine..";
$GLOBALS['TL_LANG']['li_settings']['hourlyWage'] = "Tarifications horaires";
$GLOBALS['TL_LANG']['li_settings']['hourlyWageDesc'] = "Les tarifications horaires permettent de définir comment les heures de travail sont facturées, selon le type de travail";
$GLOBALS['TL_LANG']['li_settings']['invoices'] = "Factures";
$GLOBALS['TL_LANG']['li_settings']['invoiceSettings'] = "Configuration des factures";
$GLOBALS['TL_LANG']['li_settings']['invoiceSettingsDesc'] = "Configuration générale de la facturation, ex.: numérotation des factures...";
$GLOBALS['TL_LANG']['li_settings']['invoiceCategories'] = "Catégories de factures";
$GLOBALS['TL_LANG']['li_settings']['invoiceCategoriesDesc'] = "Permet de grouper des factures en catégories pour faciliter la recherche et l'archivage";
$GLOBALS['TL_LANG']['li_settings']['invoiceTemplates'] = "Modèles de factures";
$GLOBALS['TL_LANG']['li_settings']['invoiceTemplatesDesc'] = "Permet des créer des modèles de facture";
$GLOBALS['TL_LANG']['li_settings']['invoiceDispatchSettings'] = "Envoi des factures";
$GLOBALS['TL_LANG']['li_settings']['invoiceDispatchSettingsDesc'] = "Configuration de l'envoi des factures, ex.: e-mail des destinataires";
$GLOBALS['TL_LANG']['li_settings']['invoiceReminderSettings'] = "Réglage des rappels de facturation";
$GLOBALS['TL_LANG']['li_settings']['invoiceReminderSettingsDesc'] = "Configuration générale des rappels de facturation, ex.: e-mails";
$GLOBALS['TL_LANG']['li_settings']['company'] = "Société";
$GLOBALS['TL_LANG']['li_settings']['companySettings'] = "Informations société";
$GLOBALS['TL_LANG']['li_settings']['companySettingsDesc'] = "Informations générales de la société, ex.: domiciliation bancaire";
$GLOBALS['TL_LANG']['li_settings']['taxSettings'] = "Configuration des taxes";
$GLOBALS['TL_LANG']['li_settings']['taxSettingsDesc'] = "Permet de définir les taxes applicables selon le type de produit ou service";
 
?>
