<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/modules.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['li_crm'] = "CRM";
$GLOBALS['TL_LANG']['MOD']['li_customers']['0'] = "Clients";
$GLOBALS['TL_LANG']['MOD']['li_customers']['1'] = "Gestion clients";
$GLOBALS['TL_LANG']['MOD']['li_products']['0'] = "Produits";
$GLOBALS['TL_LANG']['MOD']['li_products']['1'] = "Gestion produits";
$GLOBALS['TL_LANG']['MOD']['li_tasks']['0'] = "Tâches";
$GLOBALS['TL_LANG']['MOD']['li_tasks']['1'] = "Gestion des tâches";
$GLOBALS['TL_LANG']['MOD']['li_appointments']['0'] = "Rendez-vous";
$GLOBALS['TL_LANG']['MOD']['li_appointments']['1'] = "Gestion des rendez-vous";
$GLOBALS['TL_LANG']['MOD']['li_timekeeping']['0'] = "Gestion du temps";
$GLOBALS['TL_LANG']['MOD']['li_timekeeping']['1'] = "Gestion du temps";
$GLOBALS['TL_LANG']['MOD']['li_invoices']['0'] = "Factures";
$GLOBALS['TL_LANG']['MOD']['li_invoices']['1'] = "Gérer les factures";
$GLOBALS['TL_LANG']['MOD']['li_settings']['0'] = "Réglages";
$GLOBALS['TL_LANG']['MOD']['li_settings']['1'] = "Permet de régler les paramètres du CRM";
$GLOBALS['TL_LANG']['FMD']['li_crm'] = "CRM";
$GLOBALS['TL_LANG']['FMD']['tasklist']['0'] = "Liste des tâches";
$GLOBALS['TL_LANG']['FMD']['tasklist']['1'] = "Ajoute une liste de tâches à la page";
$GLOBALS['TL_LANG']['FMD']['taskreader']['0'] = "Lecteur de tâches";
$GLOBALS['TL_LANG']['FMD']['taskreader']['1'] = "Affiche les détails d'une tâche";
$GLOBALS['TL_LANG']['FMD']['invoicelist']['0'] = "Liste des factures";
$GLOBALS['TL_LANG']['FMD']['invoicelist']['1'] = "Ajoute une liste de factures à la page";
$GLOBALS['TL_LANG']['FMD']['invoicereader']['0'] = "Lecteur de factures";
$GLOBALS['TL_LANG']['FMD']['invoicereader']['1'] = "Affiche le détail d'une facture";
 
?>
