<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_work_package.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_work_package']['package_legend'] = "Lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['settings_legend'] = "Réglages";
$GLOBALS['TL_LANG']['tl_li_work_package']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_work_package']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_work_package']['hourLimit']['0'] = "Heure limite";
$GLOBALS['TL_LANG']['tl_li_work_package']['hourLimit']['1'] = "SVP entrez une heure limite";
$GLOBALS['TL_LANG']['tl_li_work_package']['toHourlyWage']['0'] = "Tarif horaire";
$GLOBALS['TL_LANG']['tl_li_work_package']['toHourlyWage']['1'] = "SVP choisissez un tarif horaire";
$GLOBALS['TL_LANG']['tl_li_work_package']['isExternal']['0'] = "Externe";
$GLOBALS['TL_LANG']['tl_li_work_package']['isExternal']['1'] = "Si le lot de travail est assigné à un projet externe";
$GLOBALS['TL_LANG']['tl_li_work_package']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_work_package']['toCustomer']['1'] = "SVP choisissez un client";
$GLOBALS['TL_LANG']['tl_li_work_package']['toProject']['0'] = "Projet";
$GLOBALS['TL_LANG']['tl_li_work_package']['toProject']['1'] = "SVP choisissez un projet";
$GLOBALS['TL_LANG']['tl_li_work_package']['printOnInvoice']['0'] = "Imprimer la facture";
$GLOBALS['TL_LANG']['tl_li_work_package']['printOnInvoice']['1'] = "Faut-il imprimer les heures de travail sur la facture ?";
$GLOBALS['TL_LANG']['tl_li_work_package']['internal'] = "Interne";
$GLOBALS['TL_LANG']['tl_li_work_package']['new']['0'] = "Nouveau lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['new']['1'] = "Créer un nouveau lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['edit']['0'] = "Modifier un lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['edit']['1'] = "Modifier le lot de travail %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['copy']['0'] = "Dupliquer un lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['copy']['1'] = "Dupliquer le lot de travail %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['delete']['0'] = "Supprimer un lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['delete']['1'] = "supprimer le lot de travail %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['show']['0'] = "Afficher un lot de travail";
$GLOBALS['TL_LANG']['tl_li_work_package']['show']['1'] = "Afficher le lot de travail %s";
 
?>
