<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_invoice_category.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_category']['category_legend'] = "Catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['orderNumber']['0'] = "Numero de commande";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['orderNumber']['1'] = "SVP entrez un nombre qui est utilisé";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['cssClass']['0'] = "Classe CSS";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['cssClass']['1'] = "SVP entrez une classe CSS";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['new']['0'] = "Nouvelle catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['new']['1'] = "Créer une nouvelle catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['edit']['0'] = "Modifier une catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['edit']['1'] = "Modifier une catégorie de facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['copy']['0'] = "Dupliquer la catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['copy']['1'] = "Dupliquer la catégorie de facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['delete']['0'] = "Supprimer la catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['delete']['1'] = "Supprimer la catégorie de facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['show']['0'] = "Afficher la catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['show']['1'] = "Afficher la catégorie de facture %s";
 
?>
