<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_invoice_settings.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['edit'] = "Modifier les réglages de la facture";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['invoice_data_legend'] = "Données de la facture";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['invoice_number_legend'] = "Numéro de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_maturity']['0'] = "Echéance";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_maturity']['1'] = "Entrez le nombre de jour avant expiration de l'échéance";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation']['0'] = "Création de la numérotation des factures";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation']['1'] = "SVP entrez une combinaison de lettres et de balises d'insertion qui peuvent être utilisées pour générer un numéro de facture. {{countInvoices::x}} retourne le nombre de factures actuelles. x determine combien de zero sont utilisés pour l'incrémentation.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation_start']['0'] = "Valeur de départ";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation_start']['1'] = "SVP entrez une valeur de départ. Ainsi, vous pouvez commencer la numerotation à partir de 100 par exemple au lieu de 1.";
 
?>
