<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_service.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_service']['service_legend'] = "Service";
$GLOBALS['TL_LANG']['tl_li_service']['price_legend'] = "Prix";
$GLOBALS['TL_LANG']['tl_li_service']['date_legend'] = "Date";
$GLOBALS['TL_LANG']['tl_li_service']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_service']['toCustomer']['1'] = "SVP choisissez un client";
$GLOBALS['TL_LANG']['tl_li_service']['toProject']['0'] = "Projet";
$GLOBALS['TL_LANG']['tl_li_service']['toProject']['1'] = "SVP sélectionnez un projet";
$GLOBALS['TL_LANG']['tl_li_service']['toServiceType']['0'] = "Type de service";
$GLOBALS['TL_LANG']['tl_li_service']['toServiceType']['1'] = "SVP sélectionnez un type de service";
$GLOBALS['TL_LANG']['tl_li_service']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_service']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_service']['unit']['0'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_service']['unit']['1'] = "SVP choisissez un e unité";
$GLOBALS['TL_LANG']['tl_li_service']['price']['0'] = "Prix";
$GLOBALS['TL_LANG']['tl_li_service']['price']['1'] = "SVP entrez un prix";
$GLOBALS['TL_LANG']['tl_li_service']['toTax']['0'] = "Taux de taxe";
$GLOBALS['TL_LANG']['tl_li_service']['toTax']['1'] = "SVP choisissez un taux de taxe";
$GLOBALS['TL_LANG']['tl_li_service']['currency']['0'] = "Devise";
$GLOBALS['TL_LANG']['tl_li_service']['currency']['1'] = "SVP sélectionnez une devise";
$GLOBALS['TL_LANG']['tl_li_service']['startDate']['0'] = "Date de début";
$GLOBALS['TL_LANG']['tl_li_service']['startDate']['1'] = "SVP sélectionnez une date de début";
$GLOBALS['TL_LANG']['tl_li_service']['endDate']['0'] = "Date de fin";
$GLOBALS['TL_LANG']['tl_li_service']['endDate']['1'] = "SVP entrez une date de fin";
$GLOBALS['TL_LANG']['tl_li_service']['repetition']['0'] = "Repetition";
$GLOBALS['TL_LANG']['tl_li_service']['repetition']['1'] = "Ce service doit-il être répété ?";
$GLOBALS['TL_LANG']['tl_li_service']['period']['0'] = "Période";
$GLOBALS['TL_LANG']['tl_li_service']['period']['1'] = "SVP choisissez une période";
$GLOBALS['TL_LANG']['tl_li_service']['units']['unit'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_service']['units']['hour'] = "Heure";
$GLOBALS['TL_LANG']['tl_li_service']['units']['month'] = "Mois";
$GLOBALS['TL_LANG']['tl_li_service']['units']['year'] = "Année";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['1'] = "1 mois";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['3'] = "3 mois";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['6'] = "6 mois";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['12'] = "12 mois";
$GLOBALS['TL_LANG']['tl_li_service']['new']['0'] = "Nouveau service";
$GLOBALS['TL_LANG']['tl_li_service']['new']['1'] = "Créer un nouveau service";
$GLOBALS['TL_LANG']['tl_li_service']['edit']['0'] = "Modifier un service";
$GLOBALS['TL_LANG']['tl_li_service']['edit']['1'] = "Modifier le service %s";
$GLOBALS['TL_LANG']['tl_li_service']['copy']['0'] = "Dupliquer le service";
$GLOBALS['TL_LANG']['tl_li_service']['copy']['1'] = "Dupliquer le service %s";
$GLOBALS['TL_LANG']['tl_li_service']['delete']['0'] = "Supprimer le service";
$GLOBALS['TL_LANG']['tl_li_service']['delete']['1'] = "Supprimer le service %s";
$GLOBALS['TL_LANG']['tl_li_service']['show']['0'] = "Afficher le service";
$GLOBALS['TL_LANG']['tl_li_service']['show']['1'] = "Afficher le service %s";
 
?>
