<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_product_to_customer.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['product_legend'] = "Produits";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toCustomer']['1'] = "SVP choisissez un client";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProject']['0'] = "Projet";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProject']['1'] = "SVP sélectionnez un projet";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['number']['0'] = "Quantité";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['number']['1'] = "SVP entrez la quantité de produits vendus";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProduct']['0'] = "Produit";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProduct']['1'] = "SVP choisissez un produit";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['saleDate']['0'] = "Date de vente";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['saleDate']['1'] = "SVP entrez la date de vente";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['note']['0'] = "Annotation";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['note']['1'] = "SVP entrez une annotation";
 
?>
