<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_service_type.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_service_type']['servicetype_legend'] = "Service";
$GLOBALS['TL_LANG']['tl_li_service_type']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_service_type']['title']['1'] = "SVP entrez le titre";
$GLOBALS['TL_LANG']['tl_li_service_type']['orderNumber']['0'] = "Numéro de commande";
$GLOBALS['TL_LANG']['tl_li_service_type']['orderNumber']['1'] = "SVP entrez un numéro de commande";
$GLOBALS['TL_LANG']['tl_li_service_type']['standardPrice']['0'] = "Prix standard";
$GLOBALS['TL_LANG']['tl_li_service_type']['standardPrice']['1'] = "SVP entrez le prix standard";
$GLOBALS['TL_LANG']['tl_li_service_type']['icon']['0'] = "Icône";
$GLOBALS['TL_LANG']['tl_li_service_type']['icon']['1'] = "SVP choisissez une icone. Les dimensions doivent être de 16X16 pixels";
$GLOBALS['TL_LANG']['tl_li_service_type']['defaultIcon'] = "Standard";
$GLOBALS['TL_LANG']['tl_li_service_type']['new']['0'] = "Nouveau type de service";
$GLOBALS['TL_LANG']['tl_li_service_type']['new']['1'] = "Créer un nouveau type de service";
$GLOBALS['TL_LANG']['tl_li_service_type']['edit']['0'] = "Editer le type de service";
$GLOBALS['TL_LANG']['tl_li_service_type']['edit']['1'] = "Editer le type de service %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['copy']['0'] = "Dupliquer le type de service";
$GLOBALS['TL_LANG']['tl_li_service_type']['copy']['1'] = "Dupliquer le type de service %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['delete']['0'] = "Supprimer le type de service";
$GLOBALS['TL_LANG']['tl_li_service_type']['delete']['1'] = "Supprimer le type de service %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['show']['0'] = "Afficher le type de service";
$GLOBALS['TL_LANG']['tl_li_service_type']['show']['1'] = "Afficher le type de service %s";
 
?>
