<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_timekeeping_settings.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['edit'] = "Modifier les réglages de la gestion du temps";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendar_legend'] = "Modifier les réglages du calendrier";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['li_crm_timekeeping_week_mode']['0'] = "Début de la semaine calendaire";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['li_crm_timekeeping_week_mode']['1'] = "SVP spécifiez comment le début de la semaine calendaire est défini";
 
?>
