<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_task.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task']['settings_legend'] = "Réglages";
$GLOBALS['TL_LANG']['tl_li_task']['task_legend'] = "Tâches";
$GLOBALS['TL_LANG']['tl_li_task']['publish_legend'] = "Réglages de publication";
$GLOBALS['TL_LANG']['tl_li_task']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_task']['toCustomer']['1'] = "SVP choisissez un client";
$GLOBALS['TL_LANG']['tl_li_task']['toProject']['0'] = "Projet";
$GLOBALS['TL_LANG']['tl_li_task']['toProject']['1'] = "SVP choisissez un projet";
$GLOBALS['TL_LANG']['tl_li_task']['toStatus']['0'] = "Etat";
$GLOBALS['TL_LANG']['tl_li_task']['toStatus']['1'] = "SVP sélectionnez l'état d'avancement de la tâche";
$GLOBALS['TL_LANG']['tl_li_task']['toUser']['0'] = "Assignée à";
$GLOBALS['TL_LANG']['tl_li_task']['toUser']['1'] = "SVP sélectionnez l'utilisateur auquel la tâche est assignée";
$GLOBALS['TL_LANG']['tl_li_task']['priority']['0'] = "Priorité";
$GLOBALS['TL_LANG']['tl_li_task']['priority']['1'] = "SVP sélectionnez une priorité";
$GLOBALS['TL_LANG']['tl_li_task']['title']['0'] = "titre";
$GLOBALS['TL_LANG']['tl_li_task']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_task']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_li_task']['alias']['1'] = "SVP entrez un Alias";
$GLOBALS['TL_LANG']['tl_li_task']['deadline']['0'] = "Date limite";
$GLOBALS['TL_LANG']['tl_li_task']['deadline']['1'] = "SVP entrez une date limite d'exécution de la tâche";
$GLOBALS['TL_LANG']['tl_li_task']['description']['0'] = "description";
$GLOBALS['TL_LANG']['tl_li_task']['description']['1'] = "SVP entrez une description";
$GLOBALS['TL_LANG']['tl_li_task']['published']['0'] = "Publier la tâche";
$GLOBALS['TL_LANG']['tl_li_task']['published']['1'] = "Afficher publiquement la tâche en front-end";
$GLOBALS['TL_LANG']['tl_li_task']['noCustomer'] = "Pas de client";
$GLOBALS['TL_LANG']['tl_li_task']['noTasksAvailable'] = "Pas de tâche disponible";
$GLOBALS['TL_LANG']['tl_li_task']['taskNotFound'] = "Aucune tâche trouvée";
$GLOBALS['TL_LANG']['tl_li_task']['details'] = "Détails";
$GLOBALS['TL_LANG']['tl_li_task']['task_done'] = "Tâche effectuée";
$GLOBALS['TL_LANG']['tl_li_task']['done_success'] = "La tâche a été effectuée avec succès";
$GLOBALS['TL_LANG']['tl_li_task']['done_fail'] = "La tâche n'a pu être effectuée";
$GLOBALS['TL_LANG']['tl_li_task']['back_overview'] = "Retour à la vue générale";
$GLOBALS['TL_LANG']['tl_li_task']['reminder']['0'] = "Rappel des tâches";
$GLOBALS['TL_LANG']['tl_li_task']['reminder']['1'] = "Gérer le rappel des tâches";
$GLOBALS['TL_LANG']['tl_li_task']['more_comments'] = "Afficher plus de commentaires";
$GLOBALS['TL_LANG']['tl_li_task']['comment_count'] = "Nombre total de commentaires %d";
$GLOBALS['TL_LANG']['tl_li_task']['new']['0'] = "Nouvelle tâche";
$GLOBALS['TL_LANG']['tl_li_task']['new']['1'] = "Créer une nouvelle tâche";
$GLOBALS['TL_LANG']['tl_li_task']['edit']['0'] = "Modifier une tâche";
$GLOBALS['TL_LANG']['tl_li_task']['edit']['1'] = "Modifier la tâche %s";
$GLOBALS['TL_LANG']['tl_li_task']['copy']['0'] = "Dupliquer une tâche";
$GLOBALS['TL_LANG']['tl_li_task']['copy']['1'] = "Dupliquer la tâche %s";
$GLOBALS['TL_LANG']['tl_li_task']['delete']['0'] = "Supprimer une tâche";
$GLOBALS['TL_LANG']['tl_li_task']['delete']['1'] = "Supprimer la tâche %s";
$GLOBALS['TL_LANG']['tl_li_task']['toggle']['0'] = "Publier/Dépublier une tâche";
$GLOBALS['TL_LANG']['tl_li_task']['toggle']['1'] = "Publier/Dépublier la tâche %s";
$GLOBALS['TL_LANG']['tl_li_task']['show']['0'] = "Afficher une tâche";
$GLOBALS['TL_LANG']['tl_li_task']['show']['1'] = "Afficher la tâche %s";
$GLOBALS['TL_LANG']['tl_li_task']['done']['0'] = "Clotûrer une tâche";
$GLOBALS['TL_LANG']['tl_li_task']['done']['1'] = "Clotûrer la tâche %s";
 
?>
