<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_contact.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_contact']['contact_legend'] = "Contact";
$GLOBALS['TL_LANG']['tl_li_contact']['date_legend'] = "Date et heure";
$GLOBALS['TL_LANG']['tl_li_contact']['note_legend'] = "Annotation";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment_legend'] = "Pièce jointe";
$GLOBALS['TL_LANG']['tl_li_contact']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_contact']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_contact']['category']['0'] = "Catégorie";
$GLOBALS['TL_LANG']['tl_li_contact']['category']['1'] = "SVP choisissez une catégorie";
$GLOBALS['TL_LANG']['tl_li_contact']['startDate']['0'] = "Date de début";
$GLOBALS['TL_LANG']['tl_li_contact']['startDate']['1'] = "SVP choisissez une date de début conforme au format horaire global";
$GLOBALS['TL_LANG']['tl_li_contact']['startTime']['0'] = "Heure de début";
$GLOBALS['TL_LANG']['tl_li_contact']['startTime']['1'] = "SVP entrez une heure de début";
$GLOBALS['TL_LANG']['tl_li_contact']['addEnd']['0'] = "Ajouter une fin";
$GLOBALS['TL_LANG']['tl_li_contact']['addEnd']['1'] = "Ajouter une date de fin au contact";
$GLOBALS['TL_LANG']['tl_li_contact']['endDate']['0'] = "Date de fin";
$GLOBALS['TL_LANG']['tl_li_contact']['endDate']['1'] = "Laissez le champ vide si le contact n'est pas un contact permanent";
$GLOBALS['TL_LANG']['tl_li_contact']['endTime']['0'] = "Heure de fin";
$GLOBALS['TL_LANG']['tl_li_contact']['endTime']['1'] = "Choisissez la même date de début et de fin pour créer un contact ouvert.";
$GLOBALS['TL_LANG']['tl_li_contact']['result']['0'] = "Résultat";
$GLOBALS['TL_LANG']['tl_li_contact']['result']['1'] = "SVP  choisissez un résultat";
$GLOBALS['TL_LANG']['tl_li_contact']['direction']['0'] = "Direction";
$GLOBALS['TL_LANG']['tl_li_contact']['direction']['1'] = "SVP choisissez une direction";
$GLOBALS['TL_LANG']['tl_li_contact']['note']['0'] = "Annotation";
$GLOBALS['TL_LANG']['tl_li_contact']['note']['1'] = "SVP entrez une annotation";
$GLOBALS['TL_LANG']['tl_li_contact']['addAttachment']['0'] = "Ajouter une pièce jointe";
$GLOBALS['TL_LANG']['tl_li_contact']['addAttachment']['1'] = "Ajouter une pièce jointe au contact";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment']['0'] = "Pièce jointe";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment']['1'] = "Choisissez une pièce jointe";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['phone'] = "Téléphone";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['email'] = "E-Mail";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['mail'] = "Courrier";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['fax'] = "Fax";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['direct'] = "Visiter";
$GLOBALS['TL_LANG']['tl_li_contact']['results']['reached'] = "Atteint";
$GLOBALS['TL_LANG']['tl_li_contact']['results']['not_reached'] = "Non atteint";
$GLOBALS['TL_LANG']['tl_li_contact']['directions']['incoming'] = "Entrant";
$GLOBALS['TL_LANG']['tl_li_contact']['directions']['outgoing'] = "Sortant";
$GLOBALS['TL_LANG']['tl_li_contact']['new']['0'] = "Nouveau Contact";
$GLOBALS['TL_LANG']['tl_li_contact']['new']['1'] = "Créer un nouveau contact";
$GLOBALS['TL_LANG']['tl_li_contact']['edit']['0'] = "Modifier le contact";
$GLOBALS['TL_LANG']['tl_li_contact']['edit']['1'] = "Modifier le contact %s";
$GLOBALS['TL_LANG']['tl_li_contact']['copy']['0'] = "Dupliquer le contact";
$GLOBALS['TL_LANG']['tl_li_contact']['copy']['1'] = "Dupliquer le contact %s";
$GLOBALS['TL_LANG']['tl_li_contact']['delete']['0'] = "Supprimer le contact";
$GLOBALS['TL_LANG']['tl_li_contact']['delete']['1'] = "Supprimer le contact %s";
$GLOBALS['TL_LANG']['tl_li_contact']['show']['0'] = "Afficher le contact";
$GLOBALS['TL_LANG']['tl_li_contact']['show']['1'] = "Afficher le contact %s";
 
?>
