<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_task_reminder_settings.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_reminder_settings']['edit'] = "Modifier les réglages des rappels";
$GLOBALS['TL_LANG']['tl_li_task_reminder_settings']['message_legend'] = "Rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder_settings']['li_crm_task_reminder_from']['0'] = "Adresse de l'expéditeur";
$GLOBALS['TL_LANG']['tl_li_task_reminder_settings']['li_crm_task_reminder_from']['1'] = "SVP entrez l'adresse e-mail de l'expéditeur";
$GLOBALS['TL_LANG']['tl_li_task_reminder_settings']['li_crm_task_reminder_fromName']['0'] = "Nom de l'expéditeur";
$GLOBALS['TL_LANG']['tl_li_task_reminder_settings']['li_crm_task_reminder_fromName']['1'] = "SVP entrez le nom de l'expéditeur";
 
?>
