<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_task_reminder.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_reminder']['reminder_legend'] = "Rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['once_legend'] = "Une fois";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['repeatedly_legend'] = "Plusieurs fois";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toCustomer']['1'] = "SVP sélectionnez un client";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toTask']['0'] = "Tâche";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toTask']['1'] = "SVP choisissez une tâche (Les tâches dont l'échéance est passée ne seront pas affichées)";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindOnce']['0'] = "Rappeler une fois";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindOnce']['1'] = "Créer un rappel unique";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindDate']['0'] = "Date de rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindDate']['1'] = "SVP choississez une date à laquelle le rappel doit être envoyé";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindRepeatedly']['0'] = "Rappeler plusieurs fois";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindRepeatedly']['1'] = "Crée un rappel itéré";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['0'] = "Intervalle";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['1'] = "SVP choisissez un intervalle";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['daily'] = "Quotidiennement";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['weekly'] = "Hebdomadairement";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['monthly'] = "Mensuellement";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['yearly'] = "Annuellement";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['noProject'] = "Pas de projet";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['noCustomer'] = "Pas de client";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['subject'] = "Rappel de tâche";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['text'] = "Rappel de tâche pour \"%s\", à la date %s";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['customerRemark'] = "La tâche est pour \"%s %s\"";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['new']['0'] = "Créer un rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['new']['1'] = "Créer un nouveau rappel de tâche";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['edit']['0'] = "Modifier un rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['edit']['1'] = "Modifier le rappel %s";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['copy']['0'] = "Dupliquer un rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['copy']['1'] = "Dupliquer le rappel %s";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['delete']['0'] = "Supprimer un rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['delete']['1'] = "Supprimer le rappel %s";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['show']['0'] = "Afficher un rappel";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['show']['1'] = "Afficher le rappel %s";
 
?>
