<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_company_settings.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_company_settings']['edit'] = "Editer les informations de la société";
$GLOBALS['TL_LANG']['tl_li_company_settings']['company_legend'] = "Société";
$GLOBALS['TL_LANG']['tl_li_company_settings']['address_legend'] = "Adresse";
$GLOBALS['TL_LANG']['tl_li_company_settings']['bank_legend'] = "Banque";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_name']['0'] = "Nom de la société";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_name']['1'] = "SVP entrez le nom de la société";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_default_currency']['0'] = "Devise par defaut";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_default_currency']['1'] = "SVP choisissez la devise de la société";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_tax_number']['0'] = "Numéro de T.V.A";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_tax_number']['1'] = "SVP entrer le numéro de TVA de la compagnie";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_ustid']['0'] = "Numéro de T.V.A";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_ustid']['1'] = "SVP entrer le numéro de TVA de la compagnie";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_postal']['0'] = "Code postal";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_postal']['1'] = "SVP entrez le code postal";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_account_number']['0'] = "Numéro de compte bancaire";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_account_number']['1'] = "SVP entrez le numéro de compte bancaire de votre société";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank_code']['0'] = "Code d'identification de votre banque";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank_code']['1'] = "SVP entrez le code d'identification de votre banque";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank']['0'] = "Nom de la banque";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank']['1'] = "SVP entrez le nom de votre banque";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_iban']['0'] = "IBAN";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_iban']['1'] = "SVP entrez votre code IBAN";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bic']['0'] = "BIC";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bic']['1'] = "SVP entrez votre code BIC";
 
?>
