<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_invoice_template.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_template']['template_legend'] = "Modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_data_legend'] = "Données de la facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['generation_path_legend'] = "Répertoire de création";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_template']['0'] = "Modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_template']['1'] = "SVP choisissez un modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['logo']['0'] = "Logo";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['logo']['1'] = "SVP sélectionnez un logo";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['maturity']['0'] = "Echéance";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['maturity']['1'] = "Entrez le nombre de jour avant la fin de l'échéance s'il diffère des réglages standards.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['basePath']['0'] = "Chemin ed base";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['basePath']['1'] = "SVP sélectionnez le chemin de base";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periodFolder']['0'] = "Créer un répertoire periodique";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periodFolder']['1'] = "Comment doit être créé le répertoire périodique";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['daily'] = "Quotidiennement";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['weekly'] = "Hebdomadairement";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['monthly'] = "Mensuellement";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['yearly'] = "Annuellement";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['new']['0'] = "Nouveau modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['new']['1'] = "Créer un nouveau modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['edit']['0'] = "Modifier un modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['edit']['1'] = "Modifier le modèle de facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['copy']['0'] = "Dupliquer le modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['copy']['1'] = "Dupliquer le modèle de facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['delete']['0'] = "Supprimer le modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['delete']['1'] = "Supprimer le modèle de facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['show']['0'] = "Afficher le modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['show']['1'] = "Afficher le modèle de facture %s";
 
?>
