<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_invoice.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_legend'] = "Facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['pdf_legend'] = "Fichier PDF";
$GLOBALS['TL_LANG']['tl_li_invoice']['settings_legend'] = "Réglages";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation_legend'] = "Création";
$GLOBALS['TL_LANG']['tl_li_invoice']['publish_legend'] = "Réglages de publication";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCustomer']['1'] = "SVP choisissez un client";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCategory']['0'] = "Catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCategory']['1'] = "SVP choisissez une catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_invoice']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_invoice']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_li_invoice']['alias']['1'] = "SVP entrez un alias";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceDate']['0'] = "Date de facturation";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceDate']['1'] = "SVP entrez une date de facturaton";
$GLOBALS['TL_LANG']['tl_li_invoice']['performanceDate']['0'] = "Date de livraison";
$GLOBALS['TL_LANG']['tl_li_invoice']['performanceDate']['1'] = "SVP entrez la date de livraison";
$GLOBALS['TL_LANG']['tl_li_invoice']['price']['0'] = "Prix";
$GLOBALS['TL_LANG']['tl_li_invoice']['price']['1'] = "SVP entrez le prix";
$GLOBALS['TL_LANG']['tl_li_invoice']['currency']['0'] = "Devise";
$GLOBALS['TL_LANG']['tl_li_invoice']['currency']['1'] = "SVP choisissez une devise";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity']['0'] = "Echéance";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity']['1'] = "Entrez le nombre de jour avant la fin de l'échéance s'il diffère des réglages standards.";
$GLOBALS['TL_LANG']['tl_li_invoice']['paid']['0'] = "Payé";
$GLOBALS['TL_LANG']['tl_li_invoice']['paid']['1'] = "La facture est-elle réglée ?";
$GLOBALS['TL_LANG']['tl_li_invoice']['file']['0'] = "Facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['file']['1'] = "SVP choisiisez une facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['isOut']['0'] = "Sortant";
$GLOBALS['TL_LANG']['tl_li_invoice']['isSingular']['0'] = "Unique";
$GLOBALS['TL_LANG']['tl_li_invoice']['isSingular']['1'] = "La facture est-elle unique ?";
$GLOBALS['TL_LANG']['tl_li_invoice']['enableGeneration']['0'] = "Activer la création";
$GLOBALS['TL_LANG']['tl_li_invoice']['enableGeneration']['1'] = "Activer la création automatique";
$GLOBALS['TL_LANG']['tl_li_invoice']['headline']['0'] = "En-tête";
$GLOBALS['TL_LANG']['tl_li_invoice']['headline']['1'] = "SVP entrez une en-tête";
$GLOBALS['TL_LANG']['tl_li_invoice']['toTemplate']['0'] = "Modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['toTemplate']['1'] = "SVP choisissez un modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['toAddress']['0'] = "Adresse de facturation";
$GLOBALS['TL_LANG']['tl_li_invoice']['toAddress']['1'] = "SVP choisissez une adresse de facturation";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionBefore']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_li_invoice']['discount']['0'] = "Remise";
$GLOBALS['TL_LANG']['tl_li_invoice']['discount']['1'] = "SVP entrez un taux de remise";
$GLOBALS['TL_LANG']['tl_li_invoice']['earlyPaymentDiscount']['0'] = "Texte du taux de remise pour paiement anticipé";
$GLOBALS['TL_LANG']['tl_li_invoice']['earlyPaymentDiscount']['1'] = "SVP entrez un texte pour la remise pour paiement anticipé";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionAfter']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_li_invoice']['published']['0'] = "Publier la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['published']['1'] = "Afficher en front-end";
$GLOBALS['TL_LANG']['tl_li_invoice']['new']['0'] = "Nouvelle facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['new']['1'] = "Créer une nouvelle facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['edit']['0'] = "Modifier la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['edit']['1'] = "Modifier la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['copy']['0'] = "Dupliquer la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['copy']['1'] = "Dupliquer la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['delete']['0'] = "Supprimer la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['delete']['1'] = "Supprimer la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['show']['0'] = "Afficher la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['show']['1'] = "Afficher la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['toggle']['0'] = "Publier/dépublier la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['toggle']['1'] = "Publier/dépublier la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['togglePaid']['0'] = "Facture payée/impayée";
$GLOBALS['TL_LANG']['tl_li_invoice']['togglePaid']['1'] = "Marquer la facture %s comme payée/impayée";
$GLOBALS['TL_LANG']['tl_li_invoice']['generate']['0'] = "Générer la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['generate']['1'] = "Générer la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch']['0'] = "Transmettre la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch']['1'] = "Transmettre la facture %s au client";
$GLOBALS['TL_LANG']['tl_li_invoice']['reports']['0'] = "Rapports";
$GLOBALS['TL_LANG']['tl_li_invoice']['reports']['1'] = "Afficher les rapports de facturation";
$GLOBALS['TL_LANG']['tl_li_invoice']['reminder']['0'] = "Rappels";
$GLOBALS['TL_LANG']['tl_li_invoice']['reminder']['1'] = "Gérer les rappels";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation']['0'] = "Generations";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation']['1'] = "Gérer la génération des factures";
$GLOBALS['TL_LANG']['tl_li_invoice']['showFile']['0'] = "Afficher le fichier de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['showFile']['1'] = "Afficher le fichier de la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadFile']['0'] = "Télécharger la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadFile']['1'] = "Télécharger la facture %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_month'] = "Processus de facturation - Vue mensuelle";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_year'] = "Processus de facturation - Vue annuelle";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_income'] = "Encaissements";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_expenses'] = "Dépenses";
$GLOBALS['TL_LANG']['tl_li_invoice']['income'] = "Encaissement";
$GLOBALS['TL_LANG']['tl_li_invoice']['expense'] = "Dépense";
$GLOBALS['TL_LANG']['tl_li_invoice']['tax_number'] = "TVA";
$GLOBALS['TL_LANG']['tl_li_invoice']['date'] = "Date";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_number'] = "Numéro de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['introduction_male'] = "M. %s<br />pour votre commande nous facturons les prestations suivantes.";
$GLOBALS['TL_LANG']['tl_li_invoice']['introduction_female'] = "Mme. %s<br />pour votre commande nous facturons les prestations suivantes.";
$GLOBALS['TL_LANG']['tl_li_invoice']['servicePositions']['0'] = "Prestations";
$GLOBALS['TL_LANG']['tl_li_invoice']['productPositions']['0'] = "Produits";
$GLOBALS['TL_LANG']['tl_li_invoice']['hourPositions']['0'] = "Heures";
$GLOBALS['TL_LANG']['tl_li_invoice']['hourPositions']['1'] = "SVP choisissez l'horaire pour ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_quantity']['0'] = "Quantité";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_quantity']['1'] = "SVP choisissez la quantité pour ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit']['0'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit']['1'] = "SVP choisissez l'unité pour ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_item']['0'] = "Référence";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_item']['1'] = "Sélectionnez la référence dans le CRM";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_label']['0'] = "Intitulé";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit_price']['0'] = "Prix unitaire";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit_price']['1'] = "SVP entrez l'unité monétaire pour ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_total_price'] = "A payer";
$GLOBALS['TL_LANG']['tl_li_invoice']['performance_is_invoice_date'] = "La date de facturation correspond à la date de livraison";
$GLOBALS['TL_LANG']['tl_li_invoice']['performance_date_at'] = "Date de livraison: %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['account_data'] = "Compte";
$GLOBALS['TL_LANG']['tl_li_invoice']['account_number'] = "Numéro de compte";
$GLOBALS['TL_LANG']['tl_li_invoice']['bank_code'] = "Code banque";
$GLOBALS['TL_LANG']['tl_li_invoice']['bank'] = "Nom de la banque";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity_remark'] = "Veuillez régler le total de la facture dans les %s jours.";
$GLOBALS['TL_LANG']['tl_li_invoice']['greeting'] = "Cordialement,<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['service'] = "Services";
$GLOBALS['TL_LANG']['tl_li_invoice']['products'] = "Produits";
$GLOBALS['TL_LANG']['tl_li_invoice']['hours'] = "Heures";
$GLOBALS['TL_LANG']['tl_li_invoice']['total_netto'] = "Total H.T";
$GLOBALS['TL_LANG']['tl_li_invoice']['total_brutto'] = "Total TTC";
$GLOBALS['TL_LANG']['tl_li_invoice']['tax'] = "TVA";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['unit'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['hour'] = "Heure";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['month'] = "Mois";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['year'] = "année";
$GLOBALS['TL_LANG']['tl_li_invoice']['discountOptions']['percent'] = "%";
$GLOBALS['TL_LANG']['tl_li_invoice']['discountOptions']['value'] = "Valeur";
$GLOBALS['TL_LANG']['tl_li_invoice']['details'] = "Détails";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadInvoice'] = "Télécharger la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['noInvoicesAvailable'] = "Pas de facture disponible";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceNotFound'] = "Facture non trouvée";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_generation'] = "Création de facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['paid_status_changed'] = "L'etat de paiement de la facture a été modifié avec succès";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation_success'] = "La facture a été créée avec succès";
$GLOBALS['TL_LANG']['tl_li_invoice']['back_overview'] = "Retour à la vue d'ensemble";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_subject'] = "Facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_text_male'] = "M. %s, veuillez trouver en pièce jointe la facture %s.Cordialement %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_text_female'] = "Mme. %s, veuillez trouver en pièce jointe la facture %s.Cordialement %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_html_male'] = "M. %s,<br /><br />euillez trouver en pièce jointe la facture %s.<br /><br />Cordialement<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_html_female'] = "Mme. %s,<br /><br />euillez trouver en pièce jointe la facture %s.<br /><br />Cordialement<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_dispatch'] = "Transmission de la facture";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_successful'] = "La facture a été transmise avec succès.";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_failed'] = "La facture n'a pu être transmise avec succès. Pour plus d'informations consultez le journal système";
$GLOBALS['TL_LANG']['tl_li_invoice']['generatedInvoiceName'] = "Facture";
 
?>
