<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_task_comment.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_comment']['settings_legend'] = "Réglages";
$GLOBALS['TL_LANG']['tl_li_task_comment']['comment_legend'] = "Commentaire";
$GLOBALS['TL_LANG']['tl_li_task_comment']['timekeeping_legend'] = "Gestion du temps";
$GLOBALS['TL_LANG']['tl_li_task_comment']['history_legend'] = "Historique";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changeCustomerProject']['0'] = "Assigner à un nouvel utilisateur";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changeCustomerProject']['1'] = "Choisiisez cette option si vous voulez assigner cette tâche à un nouvel utilisateur";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toCustomer']['1'] = "SVP choisissez un client";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toProject']['0'] = "Projet";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toProject']['1'] = "SVP sélectionnez un projet";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changePriority']['0'] = "Assigner une nouvelle priorité";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changePriority']['1'] = "Choisissez cette option si vous voulez assigner une nouvelle priorité à cette tâche";
$GLOBALS['TL_LANG']['tl_li_task_comment']['priority']['0'] = "Priorité";
$GLOBALS['TL_LANG']['tl_li_task_comment']['priority']['1'] = "SVP sélectionnez un epriorité";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changeTitle']['0'] = "Assigner un nouveau titre";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changeTitle']['1'] = "Choisissez cette option si vous voulez assigner un nouveau titre à cette tâche.";
$GLOBALS['TL_LANG']['tl_li_task_comment']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_task_comment']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changeDeadline']['0'] = "Assigner une nouvelle date limite";
$GLOBALS['TL_LANG']['tl_li_task_comment']['changeDeadline']['1'] = "Choisissez cette option si vous voulez assigner une nouvelle date limite à cette tâche";
$GLOBALS['TL_LANG']['tl_li_task_comment']['deadline']['0'] = "Date limite";
$GLOBALS['TL_LANG']['tl_li_task_comment']['deadline']['1'] = "SVP entrez une date d'échéance";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toStatus']['0'] = "Etat";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toStatus']['1'] = "SVP selectionnez l'état d'éxécution";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toUser']['0'] = "Utilisateur";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toUser']['1'] = "SVP sélectionnez l'urilisateur responsable de cette tâche";
$GLOBALS['TL_LANG']['tl_li_task_comment']['comment']['0'] = "Commentaire";
$GLOBALS['TL_LANG']['tl_li_task_comment']['comment']['1'] = "SVP entrez un commentaire";
$GLOBALS['TL_LANG']['tl_li_task_comment']['keeptime']['0'] = "Horodater";
$GLOBALS['TL_LANG']['tl_li_task_comment']['keeptime']['1'] = "Enregistrer le temps passé à cette tâche";
$GLOBALS['TL_LANG']['tl_li_task_comment']['hours']['0'] = "Heures";
$GLOBALS['TL_LANG']['tl_li_task_comment']['hours']['1'] = "SVP entrez le nombre d'heures";
$GLOBALS['TL_LANG']['tl_li_task_comment']['minutes']['0'] = "Minutes";
$GLOBALS['TL_LANG']['tl_li_task_comment']['minutes']['1'] = "SVP entre le nombre de minutes";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toWorkPackage']['0'] = "Lot de travail";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toWorkPackage']['1'] = "Le lot de travail auquel les heures vont être affectées";
$GLOBALS['TL_LANG']['tl_li_task_comment']['history']['0'] = "Commentaires";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeNoCustomer'] = "&rarr; Deleted assignment to customer";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeCustomerProject'] = "&rarr; Assign au client %s %s, projet %s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeCustomer'] = "&rarr; Assigner au client %s %s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changePriority'] = "&rarr; Nouvelle priorité %s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeTitle'] = "&rarr; Titre mis à jour";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeDeadline'] = "&rarr; nouvelle date limite %s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeStatus'] = "&rarr; Etat changé en %2\$s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeUser'] = "&rarr; assigné à %2\$s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['keeptime'] = "&rarr; temps passé %d:%02d en %s";
$GLOBALS['TL_LANG']['tl_li_task_comment']['new']['0'] = "Nouveau commentaire";
$GLOBALS['TL_LANG']['tl_li_task_comment']['new']['1'] = "Créer un nouveau commentaire";
$GLOBALS['TL_LANG']['tl_li_task_comment']['edit']['0'] = "Modifier un commentaire";
$GLOBALS['TL_LANG']['tl_li_task_comment']['edit']['1'] = "Modifier le commentaire %s";
 
?>
