<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_product.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product']['product_legend'] = "Produit";
$GLOBALS['TL_LANG']['tl_li_product']['price_legend'] = "Prix";
$GLOBALS['TL_LANG']['tl_li_product']['toProductType']['0'] = "Type de produit";
$GLOBALS['TL_LANG']['tl_li_product']['toProductType']['1'] = "SVP sélectionnez le type de produit";
$GLOBALS['TL_LANG']['tl_li_product']['unit']['0'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_product']['unit']['1'] = "SVP choisissez une unité";
$GLOBALS['TL_LANG']['tl_li_product']['number']['0'] = "Quantité";
$GLOBALS['TL_LANG']['tl_li_product']['number']['1'] = "SVP entrez la quantité";
$GLOBALS['TL_LANG']['tl_li_product']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_product']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_product']['price']['0'] = "Prix";
$GLOBALS['TL_LANG']['tl_li_product']['price']['1'] = "SVP entrez un prix";
$GLOBALS['TL_LANG']['tl_li_product']['currency']['0'] = "Devise";
$GLOBALS['TL_LANG']['tl_li_product']['currency']['1'] = "SVP choisissez une devise";
$GLOBALS['TL_LANG']['tl_li_product']['toTax']['0'] = "Taux de taxe";
$GLOBALS['TL_LANG']['tl_li_product']['toTax']['1'] = "SVP choisissez un taux de taxe";
$GLOBALS['TL_LANG']['tl_li_product']['units']['unit'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_product']['units']['hour'] = "Heure";
$GLOBALS['TL_LANG']['tl_li_product']['units']['month'] = "Mois";
$GLOBALS['TL_LANG']['tl_li_product']['units']['year'] = "Année";
$GLOBALS['TL_LANG']['tl_li_product']['new']['0'] = "Nouveau produit";
$GLOBALS['TL_LANG']['tl_li_product']['new']['1'] = "Créer un nouveau produit";
$GLOBALS['TL_LANG']['tl_li_product']['edit']['0'] = "Modifier un produit";
$GLOBALS['TL_LANG']['tl_li_product']['edit']['1'] = "Modifier le produit %s";
$GLOBALS['TL_LANG']['tl_li_product']['copy']['0'] = "Dupliquer un produit";
$GLOBALS['TL_LANG']['tl_li_product']['copy']['1'] = "Dupliquer le produit %s";
$GLOBALS['TL_LANG']['tl_li_product']['delete']['0'] = "Supprimer un produit";
$GLOBALS['TL_LANG']['tl_li_product']['delete']['1'] = "Supprimer le produit %s";
$GLOBALS['TL_LANG']['tl_li_product']['show']['0'] = "Afficher un produit";
$GLOBALS['TL_LANG']['tl_li_product']['show']['1'] = "Afficher le produit %s";
 
?>
