<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_invoice_generation.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['invoice_legend'] = "Facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generation_legend'] = "Création";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['settings_legend'] = "Paramètres";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCustomer']['1'] = "SVP séléctionnez un client";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCategory']['0'] = "Catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCategory']['1'] = "SVP choisissez une catégorie de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['alias']['1'] = "SVP entrez un alias";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['currency']['0'] = "Devise";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['currency']['1'] = "SVP choisissez une devise";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['maturity']['0'] = "Echéance";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['maturity']['1'] = "Entrez le nombre de jour avant la fin de l'échéance s'il diffère des réglages standards.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['headline']['0'] = "En-tête";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['headline']['1'] = "SVP entrez un texte d'en-tête";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toTemplate']['0'] = "Modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toTemplate']['1'] = "SVP choisiisez un modèle de facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toAddress']['0'] = "Adresse de facturation";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toAddress']['1'] = "SVP choisissez une adresse de facturation";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['startDate']['0'] = "Date dedébut";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['startDate']['1'] = "SVP entrez une date de début";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInverval']['0'] = "Intervalle";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInverval']['1'] = "SVP choisissez un intervalle";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['descriptionBefore']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['publishImmediately']['0'] = "Publier la facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['publishImmediately']['1'] = "Publier la facture immédiatement après la création";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['sendImmediately']['0'] = "Envoyer la facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['sendImmediately']['1'] = "Envoyer la facture immédiatement après la création";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_quantity']['0'] = "Quantité";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_quantity']['1'] = "SVP entrez la quantité pour ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit']['0'] = "Unité";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit']['1'] = "SVP choisissez l'unité pour ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_item']['0'] = "Référence";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_item']['1'] = "SCP sélectionnez la référence dans le CRM";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_label']['0'] = "Intitulé";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_label']['1'] = "SVP entrez l'intitulé de ce poste";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit_price']['0'] = "Prix unitaire";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_total_price'] = "Total";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['weekly'] = "Hebdomadaire";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['biweekly'] = "Bi-hebdomadaire";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['monthly'] = "Mensuel";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['bimonthly'] = "Bi-mensuel";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['quarterly'] = "Trimestriel";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['half-yearly'] = "Semestriel";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['yearly'] = "Annuel";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['discountOptions']['percent'] = "%";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['discountOptions']['value'] = "Valeur";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['new']['0'] = "Génération d'une nouvelle facture";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['edit']['0'] = "Modifier la facture générée";
 
?>
