<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_product_type.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product_type']['type_legend'] = "Type de produit";
$GLOBALS['TL_LANG']['tl_li_product_type']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_product_type']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_product_type']['icon']['0'] = "Icône";
$GLOBALS['TL_LANG']['tl_li_product_type']['icon']['1'] = "SVP choisissez une icone. Les dimensions doivent être de 16X16 pixels";
$GLOBALS['TL_LANG']['tl_li_product_type']['defaultIcon'] = "Défaut";
$GLOBALS['TL_LANG']['tl_li_product_type']['new']['0'] = "Nouveau type de produit";
$GLOBALS['TL_LANG']['tl_li_product_type']['new']['1'] = "Créer un nouveau type de produit";
$GLOBALS['TL_LANG']['tl_li_product_type']['edit']['0'] = "Modifier un type de produit";
$GLOBALS['TL_LANG']['tl_li_product_type']['edit']['1'] = "Modifier le type de produit %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['copy']['0'] = "Dupliquer un type de produits";
$GLOBALS['TL_LANG']['tl_li_product_type']['copy']['1'] = "Dupliquer le type de produits %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['delete']['0'] = "Effacer un type de produits";
$GLOBALS['TL_LANG']['tl_li_product_type']['delete']['1'] = "Effacer le type de produits %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['show']['0'] = "Afficher le type de produits";
$GLOBALS['TL_LANG']['tl_li_product_type']['show']['1'] = "afficher le type de produits %s";
 
?>
