<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_appointment.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_appointment']['date_legend'] = "Date";
$GLOBALS['TL_LANG']['tl_li_appointment']['time_legend'] = "Date et heure";
$GLOBALS['TL_LANG']['tl_li_appointment']['visibility_legend'] = "Visibilité";
$GLOBALS['TL_LANG']['tl_li_appointment']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_appointment']['toCustomer']['1'] = "SVP séléctionnez un client.";
$GLOBALS['TL_LANG']['tl_li_appointment']['creator']['0'] = "Créateur";
$GLOBALS['TL_LANG']['tl_li_appointment']['creator']['1'] = "SVP sélectionnez un créateur";
$GLOBALS['TL_LANG']['tl_li_appointment']['subject']['0'] = "Sujet";
$GLOBALS['TL_LANG']['tl_li_appointment']['subject']['1'] = "SVP saisissez u sujet.";
$GLOBALS['TL_LANG']['tl_li_appointment']['task']['0'] = "Tâche";
$GLOBALS['TL_LANG']['tl_li_appointment']['task']['1'] = "SVP sélectionnez une tâche.";
$GLOBALS['TL_LANG']['tl_li_appointment']['participants']['0'] = "Invités";
$GLOBALS['TL_LANG']['tl_li_appointment']['participants']['1'] = "SVP choisissez les invités";
$GLOBALS['TL_LANG']['tl_li_appointment']['place']['0'] = "Lieu";
$GLOBALS['TL_LANG']['tl_li_appointment']['place']['1'] = "SVP saisissez un lieu";
$GLOBALS['TL_LANG']['tl_li_appointment']['color']['0'] = "Couleur";
$GLOBALS['TL_LANG']['tl_li_appointment']['color']['1'] = "SVP choisissez une couleur";
$GLOBALS['TL_LANG']['tl_li_appointment']['note']['0'] = "Annotation";
$GLOBALS['TL_LANG']['tl_li_appointment']['note']['1'] = "SVP écrivez une annotation";
$GLOBALS['TL_LANG']['tl_li_appointment']['startTime']['0'] = "Heure de début";
$GLOBALS['TL_LANG']['tl_li_appointment']['startTime']['1'] = "SVP choisissez une heure de début conforme au format horaire global";
$GLOBALS['TL_LANG']['tl_li_appointment']['endTime']['0'] = "Heure de fin";
$GLOBALS['TL_LANG']['tl_li_appointment']['endTime']['1'] = "Choisissez la même date de début et de fin pour créer un évènement ouvert.";
$GLOBALS['TL_LANG']['tl_li_appointment']['startDate']['0'] = "Date de début";
$GLOBALS['TL_LANG']['tl_li_appointment']['startDate']['1'] = "SVP choisissez une date de début conforme au format horaire global";
$GLOBALS['TL_LANG']['tl_li_appointment']['endDate']['0'] = "Date de fin";
$GLOBALS['TL_LANG']['tl_li_appointment']['endDate']['1'] = "Laissez vide pour créer un évènement journalier unique";
$GLOBALS['TL_LANG']['tl_li_appointment']['repetition']['0'] = "Répétition";
$GLOBALS['TL_LANG']['tl_li_appointment']['repetition']['1'] = "L'évènement doit-il être répété ?";
$GLOBALS['TL_LANG']['tl_li_appointment']['period']['0'] = "Periodicité";
$GLOBALS['TL_LANG']['tl_li_appointment']['period']['1'] = "SVP choisissez une periodicité";
$GLOBALS['TL_LANG']['tl_li_appointment']['private']['0'] = "Privé";
$GLOBALS['TL_LANG']['tl_li_appointment']['private']['1'] = "L'évènement est-il privé ?";
$GLOBALS['TL_LANG']['tl_li_appointment']['periods']['weekly'] = "Hebdomadaire";
$GLOBALS['TL_LANG']['tl_li_appointment']['periods']['biweekly'] = "Bi-hebdomadaire";
$GLOBALS['TL_LANG']['tl_li_appointment']['periods']['monthly'] = "Mensuel";
$GLOBALS['TL_LANG']['tl_li_appointment']['details'] = "Détails";
$GLOBALS['TL_LANG']['tl_li_appointment']['appointmentNotFound'] = "Rendez-vous non trouvé.";
$GLOBALS['TL_LANG']['tl_li_appointment']['day'] = "Jour";
$GLOBALS['TL_LANG']['tl_li_appointment']['week'] = "Semaine";
$GLOBALS['TL_LANG']['tl_li_appointment']['month'] = "Mois";
$GLOBALS['TL_LANG']['tl_li_appointment']['year'] = "Année";
$GLOBALS['TL_LANG']['tl_li_appointment']['prevDay'] = "Jour précédent";
$GLOBALS['TL_LANG']['tl_li_appointment']['nextDay'] = "Jour suivant";
$GLOBALS['TL_LANG']['tl_li_appointment']['prevWeek'] = "Semaine précédente";
$GLOBALS['TL_LANG']['tl_li_appointment']['nextWeek'] = "Semaine suivante";
$GLOBALS['TL_LANG']['tl_li_appointment']['prevMonth'] = "Mois précédent";
$GLOBALS['TL_LANG']['tl_li_appointment']['nextMonth'] = "Mois suivant";
$GLOBALS['TL_LANG']['tl_li_appointment']['time'] = "Heure";
$GLOBALS['TL_LANG']['tl_li_appointment']['appointmentsAtDay'] = "Rendez-vous à %s";
$GLOBALS['TL_LANG']['tl_li_appointment']['noAppointmentsAtDay'] = "Pas de rendez-vous ce jour là";
$GLOBALS['TL_LANG']['tl_li_appointment']['dayView']['0'] = "Vue journalière";
$GLOBALS['TL_LANG']['tl_li_appointment']['dayView']['1'] = "Voir tous les rendez-vous d'une journée";
$GLOBALS['TL_LANG']['tl_li_appointment']['weekView']['0'] = "Vue hebdomadaire";
$GLOBALS['TL_LANG']['tl_li_appointment']['weekView']['1'] = "Voir tous les rendez-vous d'une semaine";
$GLOBALS['TL_LANG']['tl_li_appointment']['monthView']['0'] = "Vue mensuelle";
$GLOBALS['TL_LANG']['tl_li_appointment']['monthView']['1'] = "Voir tous les rendez-vous d'un mois";
$GLOBALS['TL_LANG']['tl_li_appointment']['new']['0'] = "Nouveau rendez-vous";
$GLOBALS['TL_LANG']['tl_li_appointment']['new']['1'] = "Créer un nouveau rendez-vous";
$GLOBALS['TL_LANG']['tl_li_appointment']['edit']['0'] = "Editer un rendez-vous";
$GLOBALS['TL_LANG']['tl_li_appointment']['edit']['1'] = "Editer le rendez vous %s";
$GLOBALS['TL_LANG']['tl_li_appointment']['copy']['0'] = "Dupliquer le rendez-vous";
$GLOBALS['TL_LANG']['tl_li_appointment']['copy']['1'] = "Dupliquer le rendez-vous %s";
$GLOBALS['TL_LANG']['tl_li_appointment']['delete']['0'] = "Supprimer le rendez-vous";
$GLOBALS['TL_LANG']['tl_li_appointment']['delete']['1'] = "Supprimer le rendez-vous %s";
$GLOBALS['TL_LANG']['tl_li_appointment']['show']['0'] = "Afficher le rendez-vous";
$GLOBALS['TL_LANG']['tl_li_appointment']['show']['1'] = "Afficher le rendez-vous %s";
 
?>
