<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_working_hour.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_working_hour']['hour_legend'] = "spécifiez le tarif horaire";
$GLOBALS['TL_LANG']['tl_li_working_hour']['entryDate']['0'] = "Date";
$GLOBALS['TL_LANG']['tl_li_working_hour']['entryDate']['1'] = "SVP choisissez une date";
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']['0'] = "Lot de travail";
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']['1'] = "SVP choisissez un lot de travail";
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']['0'] = "Heures";
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']['1'] = "SVP spécifiez le nombre d'heures effectuées";
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']['0'] = "Minutes";
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']['1'] = "SVP spécifiez le nombre de minutes";
$GLOBALS['TL_LANG']['tl_li_working_hour']['addHours'] = "Ajouter l'enregistrement";
$GLOBALS['TL_LANG']['tl_li_working_hour']['manageWorkPackages'] = "Gérer les lots de travail";
$GLOBALS['TL_LANG']['tl_li_working_hour']['editWorkPackage'] = "Modifier le lot de travail";
$GLOBALS['TL_LANG']['tl_li_working_hour']['calendar_week'] = "Semaine calendaire";
$GLOBALS['TL_LANG']['tl_li_working_hour']['editEntry'] = "Modifier l'enregistement";
$GLOBALS['TL_LANG']['tl_li_working_hour']['deleteEntry'] = "Supprimer l'enregistrement";
$GLOBALS['TL_LANG']['tl_li_working_hour']['deleteConfirmDialog'] = "Etes-vous sûr(e) de vouloir supprimer cet enregistrement ?";
 
?>
