<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_tax.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_tax']['tax_legend'] = "Taxes";
$GLOBALS['TL_LANG']['tl_li_tax']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_tax']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_tax']['rate']['0'] = "Prix";
$GLOBALS['TL_LANG']['tl_li_tax']['rate']['1'] = "SVP entrez un prix";
$GLOBALS['TL_LANG']['tl_li_tax']['new']['0'] = "Nouvelle taxe";
$GLOBALS['TL_LANG']['tl_li_tax']['new']['1'] = "Créer une nouvelle taxe";
$GLOBALS['TL_LANG']['tl_li_tax']['edit']['0'] = "Modifier une taxe";
$GLOBALS['TL_LANG']['tl_li_tax']['edit']['1'] = "Modifier la taxe %s";
$GLOBALS['TL_LANG']['tl_li_tax']['copy']['0'] = "Copier une taxe";
$GLOBALS['TL_LANG']['tl_li_tax']['copy']['1'] = "Copier la taxe %s";
$GLOBALS['TL_LANG']['tl_li_tax']['delete']['0'] = "Supprimer une taxe";
$GLOBALS['TL_LANG']['tl_li_tax']['delete']['1'] = "Supprimer la taxe %s";
$GLOBALS['TL_LANG']['tl_li_tax']['show']['0'] = "Afficher une taxe";
$GLOBALS['TL_LANG']['tl_li_tax']['show']['1'] = "Afficher la taxe %s";
 
?>
