<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_project.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_project']['project_legend'] = "Projet";
$GLOBALS['TL_LANG']['tl_li_project']['toCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_li_project']['toCustomer']['1'] = "Choisissez un client";
$GLOBALS['TL_LANG']['tl_li_project']['projectNumber']['0'] = "Numéro de projet";
$GLOBALS['TL_LANG']['tl_li_project']['projectNumber']['1'] = "SVP entrez un numéro de projet";
$GLOBALS['TL_LANG']['tl_li_project']['title']['0'] = "Titrre";
$GLOBALS['TL_LANG']['tl_li_project']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_project']['new']['0'] = "Nouveau projet";
$GLOBALS['TL_LANG']['tl_li_project']['new']['1'] = "Créer un nouveau projet";
$GLOBALS['TL_LANG']['tl_li_project']['edit']['0'] = "Modifier un projet";
$GLOBALS['TL_LANG']['tl_li_project']['edit']['1'] = "Modifier le projet %s";
$GLOBALS['TL_LANG']['tl_li_project']['copy']['0'] = "Dupliquer le projet";
$GLOBALS['TL_LANG']['tl_li_project']['copy']['1'] = "Dupliquer le projet %s";
$GLOBALS['TL_LANG']['tl_li_project']['delete']['0'] = "Supprimer le projet";
$GLOBALS['TL_LANG']['tl_li_project']['delete']['1'] = "Supprimer le projet %s";
$GLOBALS['TL_LANG']['tl_li_project']['show']['0'] = "Afficher le projet";
$GLOBALS['TL_LANG']['tl_li_project']['show']['1'] = "Afficher le projet %s";
 
?>
