<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_hourly_wage.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage_legend'] = "Tarification horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['price_legend'] = "Tarif";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage']['0'] = "Rémunération";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage']['1'] = "SVP entrez la rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['toTax']['0'] = "Taxe applicable";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['toTax']['1'] = "SVP choisissez un taux de taxes applicable";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['currency']['0'] = "Devise";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['currency']['1'] = "SVP choisiisez une devise";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['new']['0'] = "Nouvelle rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['new']['1'] = "Créer une nouvelle rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['edit']['0'] = "Modifier une rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['edit']['1'] = "Modifier la rémunération horaire %s";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['copy']['0'] = "Dupliquer la rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['copy']['1'] = "Dupliquer la rémunération horaire %s";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['delete']['0'] = "Supprimer la rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['delete']['1'] = "Supprimer la rémunération horaire %s";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['show']['0'] = "Afficher la rémunération horaire";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['show']['1'] = "Afficher la rémunération horaire %s";
 
?>
