<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_li_task_status.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_status']['status_legend'] = "Etat";
$GLOBALS['TL_LANG']['tl_li_task_status']['settings_legend'] = "Réglages";
$GLOBALS['TL_LANG']['tl_li_task_status']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_li_task_status']['title']['1'] = "SVP entrez un titre";
$GLOBALS['TL_LANG']['tl_li_task_status']['orderNumber']['0'] = "Numéro de commande";
$GLOBALS['TL_LANG']['tl_li_task_status']['orderNumber']['1'] = "SVP entrez un numéro de commande";
$GLOBALS['TL_LANG']['tl_li_task_status']['icon']['0'] = "Icône";
$GLOBALS['TL_LANG']['tl_li_task_status']['icon']['1'] = "SVP choisissez une icone. Les dimensions doivent être de 16X16 pixels";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDisabled']['0'] = "Désactivée";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDisabled']['1'] = "Considérer la tâche desactivée quand marquée de cet état";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDone']['0'] = "Effectuée";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDone']['1'] = "Considérer la tâche effectuée quand marquée de cet état";
$GLOBALS['TL_LANG']['tl_li_task_status']['cssClass']['0'] = "Classe CSS";
$GLOBALS['TL_LANG']['tl_li_task_status']['cssClass']['1'] = "SVP entrer une classe CSS";
$GLOBALS['TL_LANG']['tl_li_task_status']['defaultIcon'] = "Standard";
$GLOBALS['TL_LANG']['tl_li_task_status']['new']['0'] = "Nouvel état";
$GLOBALS['TL_LANG']['tl_li_task_status']['new']['1'] = "Créer un nouvel état";
$GLOBALS['TL_LANG']['tl_li_task_status']['edit']['0'] = "Modifier un état";
$GLOBALS['TL_LANG']['tl_li_task_status']['edit']['1'] = "Modifier l'état %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['copy']['0'] = "Dupliquer l'état";
$GLOBALS['TL_LANG']['tl_li_task_status']['copy']['1'] = "Dupliquer l'état %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['delete']['0'] = "Supprimer un état";
$GLOBALS['TL_LANG']['tl_li_task_status']['delete']['1'] = "Supprimer l'état %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['show']['0'] = "Afficher un état";
$GLOBALS['TL_LANG']['tl_li_task_status']['show']['1'] = "Afficher l'état %s";
 
?>
