<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_module.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['isCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_module']['isCustomer']['1'] = "Le nouveau membre est-il un client ?";
 
?>
