<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/fr/tl_member.php 
 * 
 * Contao extension: li_crm 0.5.1 alpha1 
 * French translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Stéphane Joos (septentrio) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['customer_legend'] = "Client";
$GLOBALS['TL_LANG']['tl_member']['bank_legend'] = "Banque";
$GLOBALS['TL_LANG']['tl_member']['isCustomer']['0'] = "Client";
$GLOBALS['TL_LANG']['tl_member']['isCustomer']['1'] = "ce membre est-il client ?";
$GLOBALS['TL_LANG']['tl_member']['customerNumber']['0'] = "Numéro de client";
$GLOBALS['TL_LANG']['tl_member']['customerNumber']['1'] = "SVP entrez un numéro de client";
$GLOBALS['TL_LANG']['tl_member']['customerName']['0'] = "Nom du client";
$GLOBALS['TL_LANG']['tl_member']['customerName']['1'] = "SVP entrez le nom du client";
$GLOBALS['TL_LANG']['tl_member']['customerColor']['0'] = "Colorisation";
$GLOBALS['TL_LANG']['tl_member']['customerColor']['1'] = "SVP choisissez une couleur. Cette couleur sera utilisée pour colorier le planning";
$GLOBALS['TL_LANG']['tl_member']['accountNumber']['0'] = "Numero de compte bancaire";
$GLOBALS['TL_LANG']['tl_member']['accountNumber']['1'] = "Veuillez saisir le code bancaire";
$GLOBALS['TL_LANG']['tl_member']['bankCode']['0'] = "Code banque";
$GLOBALS['TL_LANG']['tl_member']['bankCode']['1'] = "Veuillez saisir le code banque";
$GLOBALS['TL_LANG']['tl_member']['bank']['0'] = "Nom de la banque";
$GLOBALS['TL_LANG']['tl_member']['bank']['1'] = "Veuillez saisir le nom de la banque";
$GLOBALS['TL_LANG']['tl_member']['iban']['0'] = "Code IBAN";
$GLOBALS['TL_LANG']['tl_member']['iban']['1'] = "Veuillez entrez le code IBAN";
$GLOBALS['TL_LANG']['tl_member']['bic']['0'] = "BIC";
$GLOBALS['TL_LANG']['tl_member']['bic']['1'] = "Veuillez entrez le code BIC";
$GLOBALS['TL_LANG']['tl_member']['registerProducts']['0'] = "Produits";
$GLOBALS['TL_LANG']['tl_member']['registerProducts']['1'] = "Veuillez choisir le produit";
$GLOBALS['TL_LANG']['tl_member']['contacts']['0'] = "Contacts";
$GLOBALS['TL_LANG']['tl_member']['contacts']['1'] = "Gérer les contacts du membre %s";
$GLOBALS['TL_LANG']['tl_member']['phone']['0'] = "Téléphone";
$GLOBALS['TL_LANG']['tl_member']['phone']['1'] = "Veuillez saisir le numero de téléphone";
 
?>
