<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/es/explain.php 
 * 
 * Contao extension: li_crm 0.5.1 stable 
 * Spanisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Rainer RANALA (ranala) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['0'] = "Lunes / Domingo";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['1'] = "Elije con cual día el calendario inicia.";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['1'] = "La primera semana en el año es la semana cual contiene el día definido arriba.";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['0'] = "Por mayoria";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['1'] = "La primera semana en el año es la semana cual contiene mas de tres días en este año.";
 
?>
