<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/es/li_customer.php 
 * 
 * Contao extension: li_crm 0.5.1 stable 
 * Spanisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Rainer RANALA (ranala) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_customers']['customers'] = "Clientes";
$GLOBALS['TL_LANG']['li_customers']['customer'] = "Cliente";
$GLOBALS['TL_LANG']['li_customers']['noEntries'] = "No hay entradas";
 
?>
