<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/es/li_settings.php 
 * 
 * Contao extension: li_crm 0.5.1 stable 
 * Spanisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Rainer RANALA (ranala) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_settings']['settings'] = "CRM - Configuración";
$GLOBALS['TL_LANG']['li_settings']['customers'] = "Clientes";
$GLOBALS['TL_LANG']['li_settings']['customerSettings'] = "Clientes - Configuración";
$GLOBALS['TL_LANG']['li_settings']['customerSettingsDesc'] = "Configuración general de clientes, p.e. número de cliente.";
$GLOBALS['TL_LANG']['li_settings']['projects'] = "Proyetos";
$GLOBALS['TL_LANG']['li_settings']['projectSettings'] = "Proyetos - Configuración";
$GLOBALS['TL_LANG']['li_settings']['projectSettingsDesc'] = "Configuración general de proyectos, p.e. número de proyectos.";
$GLOBALS['TL_LANG']['li_settings']['services'] = "Servicios";
$GLOBALS['TL_LANG']['li_settings']['serviceTypes'] = "Tipos de servicios";
$GLOBALS['TL_LANG']['li_settings']['serviceTypesDesc'] = "Agrupa diferentes tipos de servicios para buscar y archivar mas fácil.";
$GLOBALS['TL_LANG']['li_settings']['products'] = "Productos";
$GLOBALS['TL_LANG']['li_settings']['productTypes'] = "Tipos de productos";
$GLOBALS['TL_LANG']['li_settings']['productTypesDesc'] = "Agrupa diferentes tipos de productos para buscar y archivar mas fácil.";
$GLOBALS['TL_LANG']['li_settings']['tasks'] = "Tareas";
$GLOBALS['TL_LANG']['li_settings']['taskStatus'] = "Estado de tareas";
$GLOBALS['TL_LANG']['li_settings']['taskStatusDesc'] = "Para definir el estado actual de las tareas.";
$GLOBALS['TL_LANG']['li_settings']['taskReminderSettings'] = "Recordatorio de tareas - Configuración";
$GLOBALS['TL_LANG']['li_settings']['taskReminderSettingsDesc'] = "Configuración general de recordatorio de tareas, p.e. dirección correo electrónico del destinatario.";
$GLOBALS['TL_LANG']['li_settings']['timekeeping'] = "Control de puntualidad";
$GLOBALS['TL_LANG']['li_settings']['workingHours'] = "Horas de trabajo";
$GLOBALS['TL_LANG']['li_settings']['workingHoursDesc'] = "Configuración general de las horas de trabajo, p.e. el inicio de la semana en el calendario.";
$GLOBALS['TL_LANG']['li_settings']['hourlyWage'] = "Sueldo de cada hora";
$GLOBALS['TL_LANG']['li_settings']['hourlyWageDesc'] = "Se puede definir paquetes de trabajo con sueldos de horas para la facturación.";
$GLOBALS['TL_LANG']['li_settings']['invoices'] = "Facturas";
$GLOBALS['TL_LANG']['li_settings']['invoiceSettings'] = "Factura - Configuración";
$GLOBALS['TL_LANG']['li_settings']['invoiceSettingsDesc'] = "Configuración general de facturas, p.e. número de la factura.";
$GLOBALS['TL_LANG']['li_settings']['invoiceCategories'] = "Factura - Categorías";
$GLOBALS['TL_LANG']['li_settings']['invoiceCategoriesDesc'] = "Agrupa diferentes categorías de facturas para buscar y archivar mas fácil.";
$GLOBALS['TL_LANG']['li_settings']['invoiceTemplates'] = "Factura - Template";
$GLOBALS['TL_LANG']['li_settings']['invoiceTemplatesDesc'] = "Con el Template de factura se puede definir el diseño de la factura generada";
$GLOBALS['TL_LANG']['li_settings']['invoiceDispatchSettings'] = "Factura - Envió";
$GLOBALS['TL_LANG']['li_settings']['invoiceDispatchSettingsDesc'] = "Configuración general del envió de facturas, p.e. dirección correo electrónico de los destinatarios.";
$GLOBALS['TL_LANG']['li_settings']['invoiceReminderSettings'] = "Recordatorio de facturas - Configuración";
$GLOBALS['TL_LANG']['li_settings']['invoiceReminderSettingsDesc'] = "Configuración general de recordatorio de facturas, p.e. dirección correo electrónico de los destinatarios.";
$GLOBALS['TL_LANG']['li_settings']['company'] = "Empresa";
$GLOBALS['TL_LANG']['li_settings']['companySettings'] = "Empresa - Configuración";
$GLOBALS['TL_LANG']['li_settings']['companySettingsDesc'] = "Configuración general de empresa, p.e. número de la cuenta y domicilio.";
$GLOBALS['TL_LANG']['li_settings']['taxSettings'] = "Impuestos - Configuración";
$GLOBALS['TL_LANG']['li_settings']['taxSettingsDesc'] = "Se puede definir los impuestos para servicios, productos y sueldos de horas.";
 
?>
