<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/es/modules.php 
 * 
 * Contao extension: li_crm 0.5.1 stable 
 * Spanisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Rainer RANALA (ranala) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['li_crm'] = "CRM";
$GLOBALS['TL_LANG']['MOD']['li_customers']['0'] = "Clientes";
$GLOBALS['TL_LANG']['MOD']['li_customers']['1'] = "Configurar clientes";
$GLOBALS['TL_LANG']['MOD']['li_products']['0'] = "Productos";
$GLOBALS['TL_LANG']['MOD']['li_products']['1'] = "Configurar productos";
$GLOBALS['TL_LANG']['MOD']['li_tasks']['0'] = "Tareas";
$GLOBALS['TL_LANG']['MOD']['li_tasks']['1'] = "Configurar tareas";
$GLOBALS['TL_LANG']['MOD']['li_appointments']['0'] = "Citas";
$GLOBALS['TL_LANG']['MOD']['li_appointments']['1'] = "Configurar citas";
$GLOBALS['TL_LANG']['MOD']['li_timekeeping']['0'] = "Control de puntualidad";
$GLOBALS['TL_LANG']['MOD']['li_timekeeping']['1'] = "Configurar control de puntualidad";
$GLOBALS['TL_LANG']['MOD']['li_invoices']['0'] = "Facturas";
$GLOBALS['TL_LANG']['MOD']['li_invoices']['1'] = "Configurar facturas";
$GLOBALS['TL_LANG']['MOD']['li_settings']['0'] = "Configuración";
$GLOBALS['TL_LANG']['MOD']['li_settings']['1'] = "Administrar CRM configuración";
$GLOBALS['TL_LANG']['FMD']['li_crm'] = "CRM";
$GLOBALS['TL_LANG']['FMD']['tasklist']['0'] = "Listado de tareas";
$GLOBALS['TL_LANG']['FMD']['tasklist']['1'] = "Añadir un listado de tareas";
$GLOBALS['TL_LANG']['FMD']['taskreader']['0'] = "Lector de tareas";
$GLOBALS['TL_LANG']['FMD']['taskreader']['1'] = "Visualizar los detalles de tareas";
$GLOBALS['TL_LANG']['FMD']['invoicelist']['0'] = "Listado de facturas";
$GLOBALS['TL_LANG']['FMD']['invoicelist']['1'] = "Añadir un listado de facturas";
$GLOBALS['TL_LANG']['FMD']['invoicereader']['0'] = "Lector de facturas";
$GLOBALS['TL_LANG']['FMD']['invoicereader']['1'] = "Visualizar los detalles de facturas";
 
?>
