<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/es/tl_li_appointment.php 
 * 
 * Contao extension: li_crm 0.5.1 stable 
 * Spanisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Rainer RANALA (ranala) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_appointment']['date_legend'] = "Fecha";
$GLOBALS['TL_LANG']['tl_li_appointment']['time_legend'] = "Fecha y tiempo";
$GLOBALS['TL_LANG']['tl_li_appointment']['visibility_legend'] = "Visibilidad";
$GLOBALS['TL_LANG']['tl_li_appointment']['toCustomer']['0'] = "Cliente";
$GLOBALS['TL_LANG']['tl_li_appointment']['toCustomer']['1'] = "Seleccionar clientes";
$GLOBALS['TL_LANG']['tl_li_appointment']['creator']['0'] = "Realizador";
$GLOBALS['TL_LANG']['tl_li_appointment']['creator']['1'] = "Seleccionar realizador";
$GLOBALS['TL_LANG']['tl_li_appointment']['subject']['0'] = "Asunto";
$GLOBALS['TL_LANG']['tl_li_appointment']['subject']['1'] = "Rellenar asunto";
$GLOBALS['TL_LANG']['tl_li_appointment']['task']['0'] = "Tarea";
$GLOBALS['TL_LANG']['tl_li_appointment']['task']['1'] = "Seleccionar tarea";
$GLOBALS['TL_LANG']['tl_li_appointment']['participants']['0'] = "Participante";
$GLOBALS['TL_LANG']['tl_li_appointment']['participants']['1'] = "Seleccionar participante";
$GLOBALS['TL_LANG']['tl_li_appointment']['place']['0'] = "Lugar";
$GLOBALS['TL_LANG']['tl_li_appointment']['place']['1'] = "Rellenar lugar";
$GLOBALS['TL_LANG']['tl_li_appointment']['color']['0'] = "Color";
$GLOBALS['TL_LANG']['tl_li_appointment']['color']['1'] = "Seleccionar color";
$GLOBALS['TL_LANG']['tl_li_appointment']['note']['0'] = "Noticia";
$GLOBALS['TL_LANG']['tl_li_appointment']['note']['1'] = "Rellenar noticia";
$GLOBALS['TL_LANG']['tl_li_appointment']['startTime']['0'] = "Tiempo de salida";
$GLOBALS['TL_LANG']['tl_li_appointment']['startTime']['1'] = "Rellenar el tiempo de salida correspondiente al formato de tiempo global.";
$GLOBALS['TL_LANG']['tl_li_appointment']['endTime']['0'] = "Tiempo de finalización";
$GLOBALS['TL_LANG']['tl_li_appointment']['endTime']['1'] = "Utilizar el mismo valor para el tiempo de salida y de finalización para crear un evento con fin abierto.";
$GLOBALS['TL_LANG']['tl_li_appointment']['startDate']['0'] = "Día de salida";
$GLOBALS['TL_LANG']['tl_li_appointment']['startDate']['1'] = "Rellenar el día de salida correspondiente al formato de tiempo global.";
$GLOBALS['TL_LANG']['tl_li_appointment']['endDate']['0'] = "Día de finalización";
$GLOBALS['TL_LANG']['tl_li_appointment']['endDate']['1'] = "Dejar libre para crear un evento de un día.";
$GLOBALS['TL_LANG']['tl_li_appointment']['repetition']['0'] = "Repetición";
$GLOBALS['TL_LANG']['tl_li_appointment']['repetition']['1'] = "Quiere repetir el servcio ?";
$GLOBALS['TL_LANG']['tl_li_appointment']['period']['0'] = "Periodo";
$GLOBALS['TL_LANG']['tl_li_appointment']['period']['1'] = "Seleccionar periodo";
$GLOBALS['TL_LANG']['tl_li_appointment']['private']['0'] = "Privado";
$GLOBALS['TL_LANG']['tl_li_appointment']['private']['1'] = "Quiere marcar la fecha como privado ?";
$GLOBALS['TL_LANG']['tl_li_appointment']['periods']['weekly'] = "Semanal";
$GLOBALS['TL_LANG']['tl_li_appointment']['periods']['biweekly'] = "Bisemanal";
$GLOBALS['TL_LANG']['tl_li_appointment']['periods']['monthly'] = "Mensual";
$GLOBALS['TL_LANG']['tl_li_appointment']['details'] = "Detalles";
$GLOBALS['TL_LANG']['tl_li_appointment']['appointmentNotFound'] = "No hay citas.";
$GLOBALS['TL_LANG']['tl_li_appointment']['day'] = "Día";
$GLOBALS['TL_LANG']['tl_li_appointment']['week'] = "Semana";
$GLOBALS['TL_LANG']['tl_li_appointment']['month'] = "Mes";
$GLOBALS['TL_LANG']['tl_li_appointment']['year'] = "Año";
$GLOBALS['TL_LANG']['tl_li_appointment']['prevDay'] = "Día anterior";
$GLOBALS['TL_LANG']['tl_li_appointment']['nextDay'] = "Día próximo";
$GLOBALS['TL_LANG']['tl_li_appointment']['prevWeek'] = "Semana anterior";
$GLOBALS['TL_LANG']['tl_li_appointment']['nextWeek'] = "Semana próximo";
$GLOBALS['TL_LANG']['tl_li_appointment']['prevMonth'] = "Mes anterior";
$GLOBALS['TL_LANG']['tl_li_appointment']['nextMonth'] = "Mes próximo";
$GLOBALS['TL_LANG']['tl_li_appointment']['time'] = "Tiempo";
$GLOBALS['TL_LANG']['tl_li_appointment']['appointmentsAtDay'] = "Cita a las %s";
$GLOBALS['TL_LANG']['tl_li_appointment']['noAppointmentsAtDay'] = "No hay citas este día.";
$GLOBALS['TL_LANG']['tl_li_appointment']['dayView']['0'] = "Vista del día";
$GLOBALS['TL_LANG']['tl_li_appointment']['dayView']['1'] = "Mirar todas citas del día.";
$GLOBALS['TL_LANG']['tl_li_appointment']['weekView']['0'] = "Vista de la semana";
$GLOBALS['TL_LANG']['tl_li_appointment']['weekView']['1'] = "Mirar todas citas de la semana.";
$GLOBALS['TL_LANG']['tl_li_appointment']['monthView']['0'] = "Vista del mes";
$GLOBALS['TL_LANG']['tl_li_appointment']['monthView']['1'] = "Mirar todas citas del mes.";
 
?>
