<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/explain.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['0'] = "Maandag / Zondag";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['1'] = "Stel in welke dag een kalenderweek start.";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['0'] = "Constant";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['1'] = "De eerste week van het jaar is de week die begint met de dag die hierboven is ingesteld. ";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['0'] = "Meerderheidsregel";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['1'] = "De eerste week van het jaar is de week die meer dan drie dagen heeft in dat jaar.";
 
?>
