<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/li_customer.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_customers']['customers'] = "Klanten";
$GLOBALS['TL_LANG']['li_customers']['customer'] = "Klant";
$GLOBALS['TL_LANG']['li_customers']['noEntries'] = "Geen klanten gevonden.";
$GLOBALS['TL_LANG']['li_customers']['customerNew']['0'] = "Nieuwe klant";
$GLOBALS['TL_LANG']['li_customers']['customerNew']['1'] = "Maak een nieuwe klant";
$GLOBALS['TL_LANG']['li_customers']['customerEdit']['0'] = "Klant Wijzigen";
$GLOBALS['TL_LANG']['li_customers']['customerEdit']['1'] = "Wijzig klant ID %s";
$GLOBALS['TL_LANG']['li_customers']['customerCopy']['0'] = "Klant dupliceeren";
$GLOBALS['TL_LANG']['li_customers']['customerCopy']['1'] = "Dupliceer klant ID %s";
$GLOBALS['TL_LANG']['li_customers']['customerDelete']['0'] = "Klant verwijderen";
$GLOBALS['TL_LANG']['li_customers']['customerDelete']['1'] = "Verwijder klant ID %s";
$GLOBALS['TL_LANG']['li_customers']['customerDelete']['2'] = "Weet u zeker dat u klant ID %s wil verwijderen?";
$GLOBALS['TL_LANG']['li_customers']['customerInfo']['0'] = "Toon klant";
$GLOBALS['TL_LANG']['li_customers']['customerInfo']['1'] = "Toon klant ID %s";
$GLOBALS['TL_LANG']['li_customers']['addressesManage']['0'] = "Beheer adressen";
$GLOBALS['TL_LANG']['li_customers']['addressesManage']['1'] = "Beheer de adressen van klant ID %s";
$GLOBALS['TL_LANG']['li_customers']['contactsManage']['0'] = "Beheer contacten";
$GLOBALS['TL_LANG']['li_customers']['contactsManage']['1'] = "Beheer de contactmomenten van klant ID %s";
$GLOBALS['TL_LANG']['li_customers']['projectNew']['0'] = "Nieuw project";
$GLOBALS['TL_LANG']['li_customers']['projectNew']['1'] = "Maak een nieuw project";
$GLOBALS['TL_LANG']['li_customers']['projectEdit']['0'] = "Project Wijzigen";
$GLOBALS['TL_LANG']['li_customers']['projectEdit']['1'] = "Wijzig project ID %s";
$GLOBALS['TL_LANG']['li_customers']['projectCopy']['0'] = "Project Kopieren";
$GLOBALS['TL_LANG']['li_customers']['projectCopy']['1'] = "Dupliceer project ID %s";
$GLOBALS['TL_LANG']['li_customers']['projectDelete']['0'] = "Project verwijderen";
$GLOBALS['TL_LANG']['li_customers']['projectDelete']['1'] = "Verwijder project ID %s";
$GLOBALS['TL_LANG']['li_customers']['projectDelete']['2'] = "Weet u zeker dat u project ID %s wil verwijderen?";
$GLOBALS['TL_LANG']['li_customers']['projectInfo']['0'] = "Toon project";
$GLOBALS['TL_LANG']['li_customers']['projectInfo']['1'] = "Toon project ID %s";
$GLOBALS['TL_LANG']['li_customers']['productNew']['0'] = "Product toevoegen";
$GLOBALS['TL_LANG']['li_customers']['productNew']['1'] = "Product toevoegen aan project";
$GLOBALS['TL_LANG']['li_customers']['productEdit']['0'] = "Product wijzigen";
$GLOBALS['TL_LANG']['li_customers']['productEdit']['1'] = "Wijzig product ID %s";
$GLOBALS['TL_LANG']['li_customers']['productCopy']['0'] = "Product kopieren";
$GLOBALS['TL_LANG']['li_customers']['productCopy']['1'] = "Dupliceer product";
$GLOBALS['TL_LANG']['li_customers']['productDelete']['0'] = "Product verwijderen";
$GLOBALS['TL_LANG']['li_customers']['productDelete']['1'] = "Verwijder product ID %s";
$GLOBALS['TL_LANG']['li_customers']['productDelete']['2'] = "Weet u zeker dat u product ID %s wil verwijderen";
$GLOBALS['TL_LANG']['li_customers']['productInfo']['0'] = "Toon product";
$GLOBALS['TL_LANG']['li_customers']['productInfo']['1'] = "Toon product ID %s";
$GLOBALS['TL_LANG']['li_customers']['serviceNew']['0'] = "Nieuwe opdracht";
$GLOBALS['TL_LANG']['li_customers']['serviceNew']['1'] = "Maak een nieuwe opdracht aan";
$GLOBALS['TL_LANG']['li_customers']['serviceEdit']['0'] = "Opdracht bewerken";
$GLOBALS['TL_LANG']['li_customers']['serviceEdit']['1'] = "Wijzig opdracht ID %s";
$GLOBALS['TL_LANG']['li_customers']['serviceCopy']['0'] = "Opdracht kopieren";
$GLOBALS['TL_LANG']['li_customers']['serviceCopy']['1'] = "Dupliceer opdracht ID %s";
$GLOBALS['TL_LANG']['li_customers']['serviceDelete']['0'] = "Verwijder opdracht";
$GLOBALS['TL_LANG']['li_customers']['serviceDelete']['1'] = "Verwijder opdracht ID %s";
$GLOBALS['TL_LANG']['li_customers']['serviceDelete']['2'] = "Weet u zeker dat u opdracht ID %s wil verwijderen?";
$GLOBALS['TL_LANG']['li_customers']['serviceInfo']['0'] = "Toon opdracht";
$GLOBALS['TL_LANG']['li_customers']['serviceInfo']['1'] = "Toon opdracht ID %s";
 
?>
