<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/li_settings.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_settings']['settings'] = "CRM instellingen";
$GLOBALS['TL_LANG']['li_settings']['customers'] = "Klanten";
$GLOBALS['TL_LANG']['li_settings']['customerSettings'] = "Klant instellingen";
$GLOBALS['TL_LANG']['li_settings']['customerSettingsDesc'] = "Met de klant instellingen worden instellingen ten aanzien van klanten ingesteld. Hier kunt u instellen hoe de klantnummers wordt gegenereerd.";
$GLOBALS['TL_LANG']['li_settings']['projects'] = "Projecten";
$GLOBALS['TL_LANG']['li_settings']['projectSettings'] = "Project instellingen";
$GLOBALS['TL_LANG']['li_settings']['projectSettingsDesc'] = "Met de project instellingen worden instellingen ten aanzien van projecten ingesteld. Hier kunt u instellen hoe een projectnummer wordt gegenereerd.";
$GLOBALS['TL_LANG']['li_settings']['services'] = "Opdrachten";
$GLOBALS['TL_LANG']['li_settings']['serviceTypes'] = "Opdracht types";
$GLOBALS['TL_LANG']['li_settings']['serviceTypesDesc'] = "Door middel van opdracht types definieert u de verschillende soorten opdrachten. Aan elke type opdracht kan een pictogram worden toegewezen wat wordt getoond in het overzicht. Het pictogram moet 16x16 pixels zijn.";
$GLOBALS['TL_LANG']['li_settings']['products'] = "Producten";
$GLOBALS['TL_LANG']['li_settings']['productTypes'] = "Productsoorten";
$GLOBALS['TL_LANG']['li_settings']['productTypesDesc'] = "Productsoorten zijn gebruikt om verschillende producten te groeperen voor de zoekfunctie en archivering";
$GLOBALS['TL_LANG']['li_settings']['tasks'] = "Taken";
$GLOBALS['TL_LANG']['li_settings']['taskStatus'] = "Taak statussen";
$GLOBALS['TL_LANG']['li_settings']['taskStatusDesc'] = "Door middel van taak statussen definieert u de verschillende soorten statussen die een taak kan hebben. Aan elke status kan een pictogram worden toegewezen wat wordt getoond in het overzicht. Het pictogram moet 16x16 pixels zijn.";
$GLOBALS['TL_LANG']['li_settings']['taskReminderSettings'] = "Herinnering instellingen";
$GLOBALS['TL_LANG']['li_settings']['taskReminderSettingsDesc'] = "Door middel van de herinninering instellingen definieert u de instellingen van een taak herinnering. Hier kunt u instellen naar wie de e-mail reminder wordt gestuurd.";
$GLOBALS['TL_LANG']['li_settings']['timekeeping'] = "Tijdregistratie";
$GLOBALS['TL_LANG']['li_settings']['workingHours'] = "Werkuren";
$GLOBALS['TL_LANG']['li_settings']['workingHoursDesc'] = "Algemene instellingen voor werkuren, bijv. de start van een kalenderweek.";
$GLOBALS['TL_LANG']['li_settings']['hourlyWage'] = "Uurtarief";
$GLOBALS['TL_LANG']['li_settings']['hourlyWageDesc'] = "Uurtarieven worden gebruikt door pakketten om de werkuren te factureren. ";
$GLOBALS['TL_LANG']['li_settings']['invoices'] = "Facturen";
$GLOBALS['TL_LANG']['li_settings']['invoiceSettings'] = "Factuur instellingen";
$GLOBALS['TL_LANG']['li_settings']['invoiceSettingsDesc'] = "Algemene instellingen voor facturen, bijv. factuurnummers.";
$GLOBALS['TL_LANG']['li_settings']['invoiceCategories'] = "Factuur categorieën";
$GLOBALS['TL_LANG']['li_settings']['invoiceCategoriesDesc'] = "Door middel van factuur categorieën definieert u verschillende categorieën voor de facturen. Dit vergemakkelijkt het zoeken en versturen van facturen.";
$GLOBALS['TL_LANG']['li_settings']['invoiceTemplates'] = "Factuur sjabloon";
$GLOBALS['TL_LANG']['li_settings']['invoiceTemplatesDesc'] = "Factuur sjabloon definieren de layout van de gegenereerde factuur.";
$GLOBALS['TL_LANG']['li_settings']['invoiceDispatchSettings'] = "Factuur verzending";
$GLOBALS['TL_LANG']['li_settings']['invoiceDispatchSettingsDesc'] = "Algemene factuur verzending instellingen, bijv. Email ontvangers.";
$GLOBALS['TL_LANG']['li_settings']['invoiceReminderSettings'] = "Herinnering instellingen";
$GLOBALS['TL_LANG']['li_settings']['invoiceReminderSettingsDesc'] = "Met de herinnering instellingen worden instellingen ten aanzien van de factuur herinneringen ingesteld.";
$GLOBALS['TL_LANG']['li_settings']['company'] = "Bedrijf";
$GLOBALS['TL_LANG']['li_settings']['companySettings'] = "Bedrijfsgegevens";
$GLOBALS['TL_LANG']['li_settings']['companySettingsDesc'] = "Algemene bedrijfsgegevens zoals adressen en bankinformatie.";
$GLOBALS['TL_LANG']['li_settings']['taxSettings'] = "BTW Instellingen";
$GLOBALS['TL_LANG']['li_settings']['taxSettingsDesc'] = "Hier kunt u de BTW tarieven instellen voor producten en uw uurtarief.";
 
?>
