<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/modules.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['li_crm'] = "CRM";
$GLOBALS['TL_LANG']['MOD']['li_customers']['0'] = "Klanten";
$GLOBALS['TL_LANG']['MOD']['li_customers']['1'] = "Beheer klanten.";
$GLOBALS['TL_LANG']['MOD']['li_products']['0'] = "Producten";
$GLOBALS['TL_LANG']['MOD']['li_products']['1'] = "Beheer producten.";
$GLOBALS['TL_LANG']['MOD']['li_tasks']['0'] = "Taken";
$GLOBALS['TL_LANG']['MOD']['li_tasks']['1'] = "Beheer taken.";
$GLOBALS['TL_LANG']['MOD']['li_timekeeping']['0'] = "Tijdregistratie";
$GLOBALS['TL_LANG']['MOD']['li_timekeeping']['1'] = "Beheer tijdregistratie.";
$GLOBALS['TL_LANG']['MOD']['li_invoices']['0'] = "Facturen";
$GLOBALS['TL_LANG']['MOD']['li_invoices']['1'] = "Beheer facturen.";
$GLOBALS['TL_LANG']['MOD']['li_settings']['0'] = "Instellingen";
$GLOBALS['TL_LANG']['MOD']['li_settings']['1'] = "Beheer instellingen van het CRM.";
 
?>
