<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_product.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product']['product_legend'] = "Product";
$GLOBALS['TL_LANG']['tl_li_product']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_product']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_product']['toProductType']['0'] = "Productsoort";
$GLOBALS['TL_LANG']['tl_li_product']['toProductType']['1'] = "Kies een productsoort.";
$GLOBALS['TL_LANG']['tl_li_product']['price']['0'] = "Prijs";
$GLOBALS['TL_LANG']['tl_li_product']['price']['1'] = "Voer een prijs in";
$GLOBALS['TL_LANG']['tl_li_product']['taxRate']['0'] = "BTW percentage";
$GLOBALS['TL_LANG']['tl_li_product']['taxRate']['1'] = "Voer een BTW percentage in.";
$GLOBALS['TL_LANG']['tl_li_product']['new']['0'] = "Nieuw product";
$GLOBALS['TL_LANG']['tl_li_product']['new']['1'] = "Maak een nieuw product";
$GLOBALS['TL_LANG']['tl_li_product']['edit']['0'] = "Product bewerken";
$GLOBALS['TL_LANG']['tl_li_product']['edit']['1'] = "Wijzig product ID %s";
$GLOBALS['TL_LANG']['tl_li_product']['copy']['0'] = "Product kopieren";
$GLOBALS['TL_LANG']['tl_li_product']['copy']['1'] = "Dupliceer product ID %s";
$GLOBALS['TL_LANG']['tl_li_product']['delete']['0'] = "Product verwijderen";
$GLOBALS['TL_LANG']['tl_li_product']['delete']['1'] = "Verwijder product ID %s";
$GLOBALS['TL_LANG']['tl_li_product']['show']['0'] = "Toon product";
$GLOBALS['TL_LANG']['tl_li_product']['show']['1'] = "Toon product ID %s";
 
?>
