<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_product_type.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product_type']['type_legend'] = "Productsoort";
$GLOBALS['TL_LANG']['tl_li_product_type']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_product_type']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_product_type']['icon']['0'] = "Pictogram";
$GLOBALS['TL_LANG']['tl_li_product_type']['icon']['1'] = "Kies een pictogram. De afmetingen van het pictogram moeten 16x16 pixels zijn.";
$GLOBALS['TL_LANG']['tl_li_product_type']['new']['0'] = "Nieuwe productsoort";
$GLOBALS['TL_LANG']['tl_li_product_type']['new']['1'] = "Maak een nieuwe productsoort";
$GLOBALS['TL_LANG']['tl_li_product_type']['edit']['0'] = "Productsoort bewerken";
$GLOBALS['TL_LANG']['tl_li_product_type']['edit']['1'] = "Wijzig productsoort ID %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['copy']['0'] = "Productsoort kopieren";
$GLOBALS['TL_LANG']['tl_li_product_type']['copy']['1'] = "Dupliceer productsoort ID %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['delete']['0'] = "Productsoort verwijderen";
$GLOBALS['TL_LANG']['tl_li_product_type']['delete']['1'] = "Verwijder productsoort ID %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['show']['0'] = "Toon productsoort";
$GLOBALS['TL_LANG']['tl_li_product_type']['show']['1'] = "Toon productsoort ID %s";
$GLOBALS['TL_LANG']['tl_li_product_type']['defaultIcon'] = "Standaard";
 
?>
