<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_contact.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_contact']['contact_legend'] = "Contactmoment";
$GLOBALS['TL_LANG']['tl_li_contact']['date_legend'] = "Datum en tijd";
$GLOBALS['TL_LANG']['tl_li_contact']['note_legend'] = "Notitie";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment_legend'] = "Bijlage";
$GLOBALS['TL_LANG']['tl_li_contact']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_contact']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_contact']['category']['0'] = "Categorie";
$GLOBALS['TL_LANG']['tl_li_contact']['category']['1'] = "Selecteer een categorie.";
$GLOBALS['TL_LANG']['tl_li_contact']['startDate']['0'] = "Start datum";
$GLOBALS['TL_LANG']['tl_li_contact']['startDate']['1'] = "Voer de startdatum in volgens de ingestelde tijdsaanduiding";
$GLOBALS['TL_LANG']['tl_li_contact']['startTime']['0'] = "Start tijd";
$GLOBALS['TL_LANG']['tl_li_contact']['startTime']['1'] = "Voer de starttijd in volgens de ingestelde tijdsaanduiding.";
$GLOBALS['TL_LANG']['tl_li_contact']['addEnd']['0'] = "Einde toevoegen";
$GLOBALS['TL_LANG']['tl_li_contact']['addEnd']['1'] = "Voer een eind datum en tijd in voor dit contact.";
$GLOBALS['TL_LANG']['tl_li_contact']['endDate']['0'] = "Eind datum";
$GLOBALS['TL_LANG']['tl_li_contact']['endDate']['1'] = "Laat leeg wanneer het slechts een dag betreft.";
$GLOBALS['TL_LANG']['tl_li_contact']['endTime']['0'] = "Eind tijd";
$GLOBALS['TL_LANG']['tl_li_contact']['endTime']['1'] = "Gebruik hetzelfde tijstip voor start en eind om een open eind evenement te creeren.";
$GLOBALS['TL_LANG']['tl_li_contact']['result']['0'] = "Resultaat";
$GLOBALS['TL_LANG']['tl_li_contact']['result']['1'] = "Selecteer het resultaat.";
$GLOBALS['TL_LANG']['tl_li_contact']['direction']['0'] = "Richting";
$GLOBALS['TL_LANG']['tl_li_contact']['direction']['1'] = "Selecteer een richting.";
$GLOBALS['TL_LANG']['tl_li_contact']['note']['0'] = "Notitie";
$GLOBALS['TL_LANG']['tl_li_contact']['note']['1'] = "Voer een notitie in.";
$GLOBALS['TL_LANG']['tl_li_contact']['addAttachment']['0'] = "Bijlage toevoegen";
$GLOBALS['TL_LANG']['tl_li_contact']['addAttachment']['1'] = "Voeg een bijlage toe aan dit contact.";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment']['0'] = "Bijlage";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment']['1'] = "Selecteer een bijlage.";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['phone'] = "Telefoon";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['email'] = "Email";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['mail'] = "E-mail of post";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['fax'] = "Fax";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['direct'] = "Bezoek";
$GLOBALS['TL_LANG']['tl_li_contact']['results']['reached'] = "Behaald";
$GLOBALS['TL_LANG']['tl_li_contact']['results']['not_reached'] = "Niet behaald";
$GLOBALS['TL_LANG']['tl_li_contact']['directions']['incoming'] = "Inkomende";
$GLOBALS['TL_LANG']['tl_li_contact']['directions']['outgoing'] = "Uitgaande";
$GLOBALS['TL_LANG']['tl_li_contact']['new']['0'] = "Nieuw contactmoment";
$GLOBALS['TL_LANG']['tl_li_contact']['new']['1'] = "Maak een nieuw contact";
$GLOBALS['TL_LANG']['tl_li_contact']['edit']['0'] = "Contactmoment bewerken";
$GLOBALS['TL_LANG']['tl_li_contact']['edit']['1'] = "Wijzig contact ID %s";
$GLOBALS['TL_LANG']['tl_li_contact']['copy']['0'] = "Contactmoment kopieren";
$GLOBALS['TL_LANG']['tl_li_contact']['copy']['1'] = "Dupliceer contact ID %s";
$GLOBALS['TL_LANG']['tl_li_contact']['delete']['0'] = "Contactmoment verwijderen";
$GLOBALS['TL_LANG']['tl_li_contact']['delete']['1'] = "Verwijder contact ID %s";
$GLOBALS['TL_LANG']['tl_li_contact']['show']['0'] = "Toon contactmoment";
$GLOBALS['TL_LANG']['tl_li_contact']['show']['1'] = "Toon contactmoment ID %s";
 
?>
