<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_hourly_wage.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage_legend'] = "Uurtarief";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['price_legend'] = "Prijs";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage']['0'] = "Tarief";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage']['1'] = "Voer het netto uurtarief in";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['toTax']['0'] = "BTW Percentage";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['toTax']['1'] = "Kies een BTW percentage";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['currency']['0'] = "Valuta";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['currency']['1'] = "Kies de te gebruiken valuta";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['new']['0'] = "Nieuw uurtarief";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['new']['1'] = "Maak nieuw uurtarief aan";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['edit']['0'] = "Uurtarief bewerken";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['edit']['1'] = "Wijzig uurtarief ID %s";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['copy']['0'] = "Uurtarief kopieren";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['copy']['1'] = "Dupliceer uurtarief ID %s";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['delete']['0'] = "Uurtarief verwijderen";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['delete']['1'] = "Verwijder uurtarief ID %s";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['show']['0'] = "Toon uurtarief";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['show']['1'] = "Toon uurtarief ID %s";
 
?>
