<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_working_hour.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_working_hour']['hour_legend'] = "Voer tarief in";
$GLOBALS['TL_LANG']['tl_li_working_hour']['entryDate']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_li_working_hour']['entryDate']['1'] = "Selecteer een datum.";
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']['0'] = "Werkpakket";
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']['1'] = "Selecteer een werkpakket";
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']['0'] = "Uren";
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']['1'] = "Voer het aantal gewerkte uren in.";
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']['0'] = "Minuten";
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']['1'] = "Voer het aantal gewerkte minuten in.";
$GLOBALS['TL_LANG']['tl_li_working_hour']['editEntry'] = "Boeking wijzigen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['deleteEntry'] = "Boeking verwijderen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['deleteConfirmDialog'] = "Weet u zeker dat u deze boeking wil verwijderen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['addHours'] = "Boeking toevoegen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['manageWorkPackages'] = "Werkpakketten beheren";
$GLOBALS['TL_LANG']['tl_li_working_hour']['editWorkPackage'] = "Werkpakket bewerken";
 
?>
