<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_task_status.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_status']['status_legend'] = "Status";
$GLOBALS['TL_LANG']['tl_li_task_status']['settings_legend'] = "Instellingen";
$GLOBALS['TL_LANG']['tl_li_task_status']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_task_status']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_task_status']['orderNumber']['0'] = "Order nummer";
$GLOBALS['TL_LANG']['tl_li_task_status']['orderNumber']['1'] = "Voer een order nummer in.";
$GLOBALS['TL_LANG']['tl_li_task_status']['icon']['0'] = "Pictogram";
$GLOBALS['TL_LANG']['tl_li_task_status']['icon']['1'] = "Selecteer een pictogram van 16x16px.";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDisabled']['0'] = "Taak uitschakelen";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDisabled']['1'] = "Moet deze taak met deze status worden uitgeschakeld?";
$GLOBALS['TL_LANG']['tl_li_task_status']['new']['0'] = "Nieuwe status";
$GLOBALS['TL_LANG']['tl_li_task_status']['new']['1'] = "Maak een nieuwe status";
$GLOBALS['TL_LANG']['tl_li_task_status']['edit']['0'] = "Status bewerken";
$GLOBALS['TL_LANG']['tl_li_task_status']['edit']['1'] = "Wijzig status ID %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['copy']['0'] = "Status kopieren";
$GLOBALS['TL_LANG']['tl_li_task_status']['copy']['1'] = "Kopier status ID %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['delete']['0'] = "Status verwijderen";
$GLOBALS['TL_LANG']['tl_li_task_status']['delete']['1'] = "Verwijder status ID %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['show']['0'] = "Toon status";
$GLOBALS['TL_LANG']['tl_li_task_status']['show']['1'] = "Toon status ID %s";
$GLOBALS['TL_LANG']['tl_li_task_status']['defaultIcon'] = "Standaard";
 
?>
