<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_invoice_dispatch_settings.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['dispatch_legend'] = "Verzending";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_from']['0'] = "Adres afzender";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_from']['1'] = "Voer het e-mailadres van de afzender in.";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_fromName']['0'] = "Naam afzender";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_fromName']['1'] = "Voer de naam van de afzender in.";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['edit'] = "Wijzig verzendinstellingen";
 
?>
