<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_invoice_category.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_category']['category_legend'] = "Factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['orderNumber']['0'] = "Sorteernummer";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['orderNumber']['1'] = "Voer een soorteernummer in, wat gebruikt wordt om facturen te catagoriseren.";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['new']['0'] = "Nieuwe factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['new']['1'] = "Maak nieuwe factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['edit']['0'] = "Bewerk factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['edit']['1'] = "Wijzig factuurcategorie ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['copy']['0'] = "Kopier factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['copy']['1'] = "Dupliceer factuurcategorie ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['delete']['0'] = "Verwijder factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['delete']['1'] = "Verwijder factuurcategorie ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['show']['0'] = "Toon factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['show']['1'] = "Toon factuurcategorie ID %s";
 
?>
