<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_invoice_reminder.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['reminder_legend'] = "Herinnering";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['once_legend'] = "Eenmalig";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['repeatedly_legend'] = "Meerdere malen";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['toCustomer']['0'] = "Klant";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['toCustomer']['1'] = "Selecteer een klant.";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['toInvoice']['0'] = "Factuur";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['toInvoice']['1'] = "Selecteer een factuur.";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindOnce']['0'] = "Herinner eenmalig";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindOnce']['1'] = "Moet deze herinnering eenmalig verzonden worden?";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindDate']['0'] = "Herinnerings datum";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindDate']['1'] = "Voer de datum in dat de herinnering moet worden verzonden.";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindRepeatedly']['0'] = "Herinnering herhalen";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindRepeatedly']['1'] = "Moet de herinnering worden herhaald?";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindInterval']['0'] = "Interval";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindInterval']['1'] = "Selecteer interval";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindInterval']['daily'] = "Dagelijks";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindInterval']['weekly'] = "Weekelijks";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindInterval']['monthly'] = "Maandelijks";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['remindInterval']['yearly'] = "Jaarlijks";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['new']['0'] = "Nieuwe Herinnering";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['new']['1'] = "Maak een herinnering";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['edit']['0'] = "Herinnering bewerken";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['edit']['1'] = "Wijzig herinnering ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['copy']['0'] = "Herinnering kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['copy']['1'] = "Dupliceer herinnering ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['delete']['0'] = "Herinnering verwijderen";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['delete']['1'] = "Verwijder herinnering ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['show']['0'] = "Toon herinnering";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['show']['1'] = "Toon herinnering ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['noCustomer'] = "Geen klant";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['subject'] = "Factuur herinnering";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['text'] = "Factuur herinnering voor factuur \"%s\" van %s.";
$GLOBALS['TL_LANG']['tl_li_invoice_reminder']['customerRemark'] = "Deze factuur hoort bij klant \"%s %s\".";
 
?>
