<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_company_settings.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_company_settings']['company_legend'] = "Bedrijf";
$GLOBALS['TL_LANG']['tl_li_company_settings']['address_legend'] = "Adres";
$GLOBALS['TL_LANG']['tl_li_company_settings']['bank_legend'] = "Bank";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_name']['0'] = "Bedrijfsnaam";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_name']['1'] = "Voer bedrijfsnaam in.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_tax_number']['0'] = "BTW nummer";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_tax_number']['1'] = "Voer BTW nummer in.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_account_number']['0'] = "Rekeningnummer";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_account_number']['1'] = "Voer het rekeningnummer van het bedrijf in.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank_code']['0'] = "Bank code";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank_code']['1'] = "Voer de bankcode van uw account in.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank']['0'] = "Naam bank";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank']['1'] = "Voer de naam van de bank in.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['edit'] = "Bedrijfsgegevens bewerken";
 
?>
