<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_customer_settings.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_customer_settings']['customer_number_legend'] = "Klantnummer";
$GLOBALS['TL_LANG']['tl_li_customer_settings']['li_crm_customer_number_generation']['0'] = "Generatie klantnummer";
$GLOBALS['TL_LANG']['tl_li_customer_settings']['li_crm_customer_number_generation']['1'] = "Voer een combinatie van insert tags en tekst hoe het klantnummer wordt gegenereerd. Er kan gebruik worden gemaakt van {{countCustomers::x}} voor het verkrijgen van klantnummers. De waarde van x stelt in hoe veel cijfers worden gebruikt, de rest wordt opgevult met nullen.";
$GLOBALS['TL_LANG']['tl_li_customer_settings']['li_crm_customer_number_generation_start']['0'] = "Klantenteller startgetal";
$GLOBALS['TL_LANG']['tl_li_customer_settings']['li_crm_customer_number_generation_start']['1'] = "Voer een getal in waarmee het klantnummer begint. Hierdoor kan bijvoorbeeld het klantnummer beginnen met 100.";
$GLOBALS['TL_LANG']['tl_li_customer_settings']['edit'] = "Wijzig klantinstellingen";
 
?>
