<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_invoice.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_legend'] = "Factuur";
$GLOBALS['TL_LANG']['tl_li_invoice']['pdf_legend'] = "PDF document";
$GLOBALS['TL_LANG']['tl_li_invoice']['settings_legend'] = "Instellingen";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation_legend'] = "Generatie";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCustomer']['0'] = "Klant";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCustomer']['1'] = "Selecteer een klant.";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCategory']['0'] = "Factuurcategorie";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCategory']['1'] = "Selecteer een categorie.";
$GLOBALS['TL_LANG']['tl_li_invoice']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['alias']['0'] = "Referentie";
$GLOBALS['TL_LANG']['tl_li_invoice']['alias']['1'] = "Voer een referentie in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceDate']['0'] = "Factuurdatum";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceDate']['1'] = "Voer de factuurdatum in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['performanceDate']['0'] = "Opdracht datum";
$GLOBALS['TL_LANG']['tl_li_invoice']['performanceDate']['1'] = "Voer de opdracht datum in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['price']['0'] = "Bedrag";
$GLOBALS['TL_LANG']['tl_li_invoice']['price']['1'] = "Voer het bedrag in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['currency']['0'] = "Valuta";
$GLOBALS['TL_LANG']['tl_li_invoice']['currency']['1'] = "Kies de valuta";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity']['0'] = "Vervalperiode";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity']['1'] = "Voer het aantal dagen van de vervalperiode van de factuur in, als het anders is dan de standaard ingestelde vervalperiode ";
$GLOBALS['TL_LANG']['tl_li_invoice']['file']['0'] = "Factuur";
$GLOBALS['TL_LANG']['tl_li_invoice']['file']['1'] = "Selecteer ingaande of uitgaande factuur.";
$GLOBALS['TL_LANG']['tl_li_invoice']['isOut']['0'] = "Uitgaande factuur?";
$GLOBALS['TL_LANG']['tl_li_invoice']['isOut']['1'] = "Is dit een verkoopfactuur?";
$GLOBALS['TL_LANG']['tl_li_invoice']['isSingular']['0'] = "Eenmalige factuur?";
$GLOBALS['TL_LANG']['tl_li_invoice']['isSingular']['1'] = "Is deze factuur eenmalig?";
$GLOBALS['TL_LANG']['tl_li_invoice']['enableGeneration']['0'] = "Generatie activeren";
$GLOBALS['TL_LANG']['tl_li_invoice']['enableGeneration']['1'] = "Activeer automatische generatie.";
$GLOBALS['TL_LANG']['tl_li_invoice']['headline']['0'] = "Kopregel";
$GLOBALS['TL_LANG']['tl_li_invoice']['headline']['1'] = "Voer een kopregel in";
$GLOBALS['TL_LANG']['tl_li_invoice']['toTemplate']['0'] = "Factuur sjabloon";
$GLOBALS['TL_LANG']['tl_li_invoice']['toTemplate']['1'] = "Kies een factuur sjabloon.";
$GLOBALS['TL_LANG']['tl_li_invoice']['toAddress']['0'] = "Factuuradres";
$GLOBALS['TL_LANG']['tl_li_invoice']['toAddress']['1'] = "Kies een factuuradres.";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionBefore']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionBefore']['1'] = "Voer de omschrijving voor de factuurregels in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionAfter']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionAfter']['1'] = "Voer de omschrijving na de factuurregels in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['new']['0'] = "Nieuwe Factuur";
$GLOBALS['TL_LANG']['tl_li_invoice']['new']['1'] = "Maak een nieuwe factuur aan.";
$GLOBALS['TL_LANG']['tl_li_invoice']['edit']['0'] = "Factuur bewerken";
$GLOBALS['TL_LANG']['tl_li_invoice']['edit']['1'] = "Wijzig factuur ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['copy']['0'] = "Factuur kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['copy']['1'] = "Dupliceer factuur ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['delete']['0'] = "Verwijder factuur";
$GLOBALS['TL_LANG']['tl_li_invoice']['delete']['1'] = "Verwijder factuur %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['show']['0'] = "Toon factuur";
$GLOBALS['TL_LANG']['tl_li_invoice']['show']['1'] = "Toon factuur ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['generate']['0'] = "Factuur genereren";
$GLOBALS['TL_LANG']['tl_li_invoice']['generate']['1'] = "Genereer factuur ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch']['0'] = "Factuur verzenden";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch']['1'] = "Verzend factuur met ID %s naar de klant";
$GLOBALS['TL_LANG']['tl_li_invoice']['reports']['0'] = "Rapporten";
$GLOBALS['TL_LANG']['tl_li_invoice']['reports']['1'] = "Toon de rapporten van de facturen";
$GLOBALS['TL_LANG']['tl_li_invoice']['reminder']['0'] = "Factuur herinnering";
$GLOBALS['TL_LANG']['tl_li_invoice']['reminder']['1'] = "Beheer de factuurherinnering";
$GLOBALS['TL_LANG']['tl_li_invoice']['showFile']['0'] = "Toon het factuurbestand";
$GLOBALS['TL_LANG']['tl_li_invoice']['showFile']['1'] = "Toon het factuurbestand van factuur ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadFile']['0'] = "Factuur downloaden";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadFile']['1'] = "Download factuur ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_month'] = "Factuurproces - Maandoverzicht";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_year'] = "Factuurproces - Jaaroverzicht";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_income'] = "Inkomsten";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_expenses'] = "Uitgaven";
$GLOBALS['TL_LANG']['tl_li_invoice']['income'] = "Inkomsten";
$GLOBALS['TL_LANG']['tl_li_invoice']['expense'] = "Uitgaven";
$GLOBALS['TL_LANG']['tl_li_invoice']['tax_number'] = "BTW nummer";
$GLOBALS['TL_LANG']['tl_li_invoice']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_number'] = "Factuurnummer";
$GLOBALS['TL_LANG']['tl_li_invoice']['introduction_male'] = "Geachte heer %s,<br />Hierbij factureren we de aan u geleverde diensten.";
$GLOBALS['TL_LANG']['tl_li_invoice']['introduction_female'] = "Geachte mevrouw %s, Hierbij factureren we de aan u geleverde diensten.";
$GLOBALS['TL_LANG']['tl_li_invoice']['servicePositions']['0'] = "Diensten";
$GLOBALS['TL_LANG']['tl_li_invoice']['servicePositions']['1'] = "Kies de diensten factuur-regel";
$GLOBALS['TL_LANG']['tl_li_invoice']['productPositions']['0'] = "Producten";
$GLOBALS['TL_LANG']['tl_li_invoice']['productPositions']['1'] = "Kies de product factuur-regel";
$GLOBALS['TL_LANG']['tl_li_invoice']['hourPositions']['0'] = "Uren";
$GLOBALS['TL_LANG']['tl_li_invoice']['hourPositions']['1'] = "Kies de uren factuur-regel";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_quantity']['0'] = "Aantal";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_quantity']['1'] = "Voer het aantal voor deze factuur-regel in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit']['0'] = "Eenheid";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit']['1'] = "Kies de eenheid voor deze factuur-regel";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_item']['0'] = "Referentie";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_item']['1'] = "Kies een referentie in het CRM";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_label']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_label']['1'] = "Voer een omschrijving voor deze factuur-regel in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit_price']['0'] = "Eenheid prijs";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit_price']['1'] = "Voer een eenheid prijs voor deze factuur-regel in.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_total_price'] = "Totaal";
$GLOBALS['TL_LANG']['tl_li_invoice']['performance_is_invoice_date'] = "De factuurdatum is de opdracht datum";
$GLOBALS['TL_LANG']['tl_li_invoice']['performance_date_at'] = "Opdracht datum: %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['account_data'] = "Bankgegevens";
$GLOBALS['TL_LANG']['tl_li_invoice']['account_number'] = "Rekeningnummer";
$GLOBALS['TL_LANG']['tl_li_invoice']['bank_code'] = "Bank Code";
$GLOBALS['TL_LANG']['tl_li_invoice']['bank'] = "Bank";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity_remark'] = "Gelieve het totaalbedrag betalen binnen %s dagen.";
$GLOBALS['TL_LANG']['tl_li_invoice']['greeting'] = "Met vriendelijke groet,<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['service'] = "Diensten";
$GLOBALS['TL_LANG']['tl_li_invoice']['products'] = "Producten";
$GLOBALS['TL_LANG']['tl_li_invoice']['hours'] = "Uren";
$GLOBALS['TL_LANG']['tl_li_invoice']['total_netto'] = "Totaal";
$GLOBALS['TL_LANG']['tl_li_invoice']['total_brutto'] = "Totaal incl. BTW";
$GLOBALS['TL_LANG']['tl_li_invoice']['tax'] = "BTW";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['unit'] = "Eenheid";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['hour'] = "Uur";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['month'] = "Maand";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['year'] = "Jaar";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_generation'] = "Factuur generatie";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation_success'] = "De factuur is succesvol gegenereerd.";
$GLOBALS['TL_LANG']['tl_li_invoice']['back_overview'] = "Terug naar overzicht";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_subject'] = "Factuur";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_text_male'] = "Geachte heer %s,\n\nIn de bijlage van deze e-mail vindt u de factuur van %s.\n\nMet vriendelijke groet,\n%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_text_female'] = "Geachte mevrouw %s,\n\nIn de bijlage van deze e-mail vindt u de factuur van %s.\n\nMet vriendelijke groet,\n%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_html_male'] = "Geachte heer %s,<br /><br />In de bijlage van deze e-mail vindt u de factuur van %s.<br /><br />Met vriendelijke groet,<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_html_female'] = "Geachte mevrouw %s,<br /><br />In de bijlage van deze e-mail vindt u de factuur van %s.<br /><br />Met vriendelijke groet,<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_dispatch'] = "Factuur verzending";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_successful'] = "De factuur is succesvol verzonden.";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_failed'] = "De factuur kon niet worden verzonden. Bekijk het systeemlog voor meer informatie.";
 
?>
