<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_work_package.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_work_package']['package_legend'] = "Werkpakketten";
$GLOBALS['TL_LANG']['tl_li_work_package']['settings_legend'] = "Instellingen";
$GLOBALS['TL_LANG']['tl_li_work_package']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_work_package']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_work_package']['hourLimit']['0'] = "Tijdlimiet";
$GLOBALS['TL_LANG']['tl_li_work_package']['hourLimit']['1'] = "Voer een tijdlimiet in uren in.";
$GLOBALS['TL_LANG']['tl_li_work_package']['toHourlyWage']['0'] = "Uurtarief";
$GLOBALS['TL_LANG']['tl_li_work_package']['toHourlyWage']['1'] = "Kies een uurtarief";
$GLOBALS['TL_LANG']['tl_li_work_package']['isExternal']['0'] = "Extern";
$GLOBALS['TL_LANG']['tl_li_work_package']['isExternal']['1'] = "Is het werkpakket toegewezen aan een extern project?";
$GLOBALS['TL_LANG']['tl_li_work_package']['toProject']['0'] = "Project";
$GLOBALS['TL_LANG']['tl_li_work_package']['toProject']['1'] = "Kies een project";
$GLOBALS['TL_LANG']['tl_li_work_package']['new']['0'] = "Nieuw werkpakket";
$GLOBALS['TL_LANG']['tl_li_work_package']['new']['1'] = "Maak een nieuw werkpakket";
$GLOBALS['TL_LANG']['tl_li_work_package']['edit']['0'] = "Werkpakket bewerken";
$GLOBALS['TL_LANG']['tl_li_work_package']['edit']['1'] = "Wijzig werkpakket ID %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['copy']['0'] = "Werkpakket kopieren";
$GLOBALS['TL_LANG']['tl_li_work_package']['copy']['1'] = "Dupliceer werkpakket ID %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['delete']['0'] = "Werkpakket verwijderen";
$GLOBALS['TL_LANG']['tl_li_work_package']['delete']['1'] = "Verwijder werkpakket ID %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['show']['0'] = "Toon werkpakket";
$GLOBALS['TL_LANG']['tl_li_work_package']['show']['1'] = "Toon werkpakket ID %s";
$GLOBALS['TL_LANG']['tl_li_work_package']['internal'] = "Intern";
 
?>
