<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_task.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task']['settings_legend'] = "Instellingen";
$GLOBALS['TL_LANG']['tl_li_task']['task_legend'] = "Taak";
$GLOBALS['TL_LANG']['tl_li_task']['toCustomer']['0'] = "Klant";
$GLOBALS['TL_LANG']['tl_li_task']['toCustomer']['1'] = "Selecteer een klant.";
$GLOBALS['TL_LANG']['tl_li_task']['toProject']['0'] = "Project";
$GLOBALS['TL_LANG']['tl_li_task']['toProject']['1'] = "Selecteer een project.";
$GLOBALS['TL_LANG']['tl_li_task']['toStatus']['0'] = "Status";
$GLOBALS['TL_LANG']['tl_li_task']['toStatus']['1'] = "Selecteer een status.";
$GLOBALS['TL_LANG']['tl_li_task']['toUser']['0'] = "Toegewezen aan";
$GLOBALS['TL_LANG']['tl_li_task']['toUser']['1'] = "Selecteer gebruiker waar deze taak aan wordt toegewezen.";
$GLOBALS['TL_LANG']['tl_li_task']['priority']['0'] = "Prioriteit";
$GLOBALS['TL_LANG']['tl_li_task']['priority']['1'] = "Selecteer prioriteit.";
$GLOBALS['TL_LANG']['tl_li_task']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_task']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_task']['alias']['0'] = "Referentie";
$GLOBALS['TL_LANG']['tl_li_task']['alias']['1'] = "Voer een referentie in.";
$GLOBALS['TL_LANG']['tl_li_task']['deadline']['0'] = "Deadline";
$GLOBALS['TL_LANG']['tl_li_task']['deadline']['1'] = "Voer de datum in wanneer de taak moet zijn afgerond.";
$GLOBALS['TL_LANG']['tl_li_task']['description']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_li_task']['description']['1'] = "Voer een omschrijving in.";
$GLOBALS['TL_LANG']['tl_li_task']['new']['0'] = "Nieuwe taak";
$GLOBALS['TL_LANG']['tl_li_task']['new']['1'] = "Maak een nieuwe taak";
$GLOBALS['TL_LANG']['tl_li_task']['edit']['0'] = "Taak bewerken";
$GLOBALS['TL_LANG']['tl_li_task']['edit']['1'] = "Wijzig taak ID %s";
$GLOBALS['TL_LANG']['tl_li_task']['copy']['0'] = "Taak kopieren";
$GLOBALS['TL_LANG']['tl_li_task']['copy']['1'] = "Dupliceer taak ID %s";
$GLOBALS['TL_LANG']['tl_li_task']['delete']['0'] = "Taak verwijderen";
$GLOBALS['TL_LANG']['tl_li_task']['delete']['1'] = "Verwijder taak ID %s";
$GLOBALS['TL_LANG']['tl_li_task']['show']['0'] = "Toon taak";
$GLOBALS['TL_LANG']['tl_li_task']['show']['1'] = "Toon taak ID %s";
$GLOBALS['TL_LANG']['tl_li_task']['noCustomer'] = "Geen klant";
$GLOBALS['TL_LANG']['tl_li_task']['reminder']['0'] = "Taak herinnering";
$GLOBALS['TL_LANG']['tl_li_task']['reminder']['1'] = "Beheer taak herinnering";
 
?>
