<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_project.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_project']['project_legend'] = "Project";
$GLOBALS['TL_LANG']['tl_li_project']['toCustomer']['0'] = "Klant";
$GLOBALS['TL_LANG']['tl_li_project']['toCustomer']['1'] = "Selecteer een klant.";
$GLOBALS['TL_LANG']['tl_li_project']['projectNumber']['0'] = "Project nummer";
$GLOBALS['TL_LANG']['tl_li_project']['projectNumber']['1'] = "Voer het projectnummer in.";
$GLOBALS['TL_LANG']['tl_li_project']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_project']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_project']['new']['0'] = "Nieuw project";
$GLOBALS['TL_LANG']['tl_li_project']['new']['1'] = "Maak een nieuw project aan";
$GLOBALS['TL_LANG']['tl_li_project']['edit']['0'] = "Project bewerken";
$GLOBALS['TL_LANG']['tl_li_project']['edit']['1'] = "Wijzig project ID %s";
$GLOBALS['TL_LANG']['tl_li_project']['copy']['0'] = "Project kopieren";
$GLOBALS['TL_LANG']['tl_li_project']['copy']['1'] = "Dupliceer project ID %s";
$GLOBALS['TL_LANG']['tl_li_project']['delete']['0'] = "Project verwijderen";
$GLOBALS['TL_LANG']['tl_li_project']['delete']['1'] = "Verwijder project ID %s";
$GLOBALS['TL_LANG']['tl_li_project']['show']['0'] = "Toon project";
$GLOBALS['TL_LANG']['tl_li_project']['show']['1'] = "Toon project ID %s";
 
?>
