<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_timekeeping_settings.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendar_legend'] = "Kalender instellingen wijzigen";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['li_crm_timekeeping_week_mode']['0'] = "Start van de kalender week";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['li_crm_timekeeping_week_mode']['1'] = "Stel de start van de kalenderweek in.";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['7'] = "Maandag / Constant";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['3'] = "Maandag / Meerderheidsregel";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['2'] = "Zondag / Constant";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['6'] = "Zondag / Meerderheidsregel";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['edit'] = "Tijdregistratie instellingen bewerken";
 
?>
