<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_member.php 
 * 
 * Contao extension: li_crm 0.3.0 alpha1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['customer_legend'] = "Klant";
$GLOBALS['TL_LANG']['tl_member']['isCustomer']['0'] = "Klant";
$GLOBALS['TL_LANG']['tl_member']['isCustomer']['1'] = "Is dit lid ook klant?";
$GLOBALS['TL_LANG']['tl_member']['customerNumber']['0'] = "Klantnummer";
$GLOBALS['TL_LANG']['tl_member']['customerNumber']['1'] = "Voer een klantnummer in.";
$GLOBALS['TL_LANG']['tl_member']['customerName']['0'] = "Klant naam";
$GLOBALS['TL_LANG']['tl_member']['customerName']['1'] = "Voer een klantnaam in.";
$GLOBALS['TL_LANG']['tl_member']['customerColor']['0'] = "Kleur";
$GLOBALS['TL_LANG']['tl_member']['customerColor']['1'] = "Kies een kleur. Deze kleur wordt gebruikt in de werkuren op de kalender.";
 
?>
