<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_service.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_service']['service_legend'] = "Opdracht";
$GLOBALS['TL_LANG']['tl_li_service']['price_legend'] = "Prijs";
$GLOBALS['TL_LANG']['tl_li_service']['toCustomer']['0'] = "Klant";
$GLOBALS['TL_LANG']['tl_li_service']['toCustomer']['1'] = "Selecteer een klant.";
$GLOBALS['TL_LANG']['tl_li_service']['toProject']['0'] = "Project";
$GLOBALS['TL_LANG']['tl_li_service']['toProject']['1'] = "Selecteer een project.";
$GLOBALS['TL_LANG']['tl_li_service']['toServiceType']['0'] = "Opdracht type";
$GLOBALS['TL_LANG']['tl_li_service']['toServiceType']['1'] = "Selecteer een opdracht type.";
$GLOBALS['TL_LANG']['tl_li_service']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_service']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_service']['price']['0'] = "Prijs";
$GLOBALS['TL_LANG']['tl_li_service']['price']['1'] = "Voer een prijs in.";
$GLOBALS['TL_LANG']['tl_li_service']['toTax']['0'] = "BTW percentage";
$GLOBALS['TL_LANG']['tl_li_service']['toTax']['1'] = "Kies een BTW percentage";
$GLOBALS['TL_LANG']['tl_li_service']['currency']['0'] = "Valuta";
$GLOBALS['TL_LANG']['tl_li_service']['currency']['1'] = "Kies de valuta";
$GLOBALS['TL_LANG']['tl_li_service']['new']['0'] = "Nieuwe opdracht";
$GLOBALS['TL_LANG']['tl_li_service']['new']['1'] = "Maak een nieuwe opdracht";
$GLOBALS['TL_LANG']['tl_li_service']['edit']['0'] = "Opdracht bewerken";
$GLOBALS['TL_LANG']['tl_li_service']['edit']['1'] = "Wijzig opdracht ID %s";
$GLOBALS['TL_LANG']['tl_li_service']['copy']['0'] = "Opdracht kopieren";
$GLOBALS['TL_LANG']['tl_li_service']['copy']['1'] = "Dupliceer opdracht ID %s";
$GLOBALS['TL_LANG']['tl_li_service']['delete']['0'] = "Opdracht verwijderen";
$GLOBALS['TL_LANG']['tl_li_service']['delete']['1'] = "Verwijder opdracht ID %s";
$GLOBALS['TL_LANG']['tl_li_service']['show']['0'] = "Toon opdracht";
$GLOBALS['TL_LANG']['tl_li_service']['show']['1'] = "Toon opdracht ID %s";
 
?>
