<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_product_to_customer.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['product_legend'] = "Producten";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toCustomer']['0'] = "Klanten";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toCustomer']['1'] = "Selecteer een klant.";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProject']['0'] = "Project";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProject']['1'] = "Selecteer een project.";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProduct']['0'] = "Product";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProduct']['1'] = "Selecteer een product.";
 
?>
