<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_invoice_template.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_template']['template_legend'] = "Factuur sjabloon";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_data_legend'] = "Factuur data";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['generation_path_legend'] = "Factuurgeneratie map";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_template']['0'] = "Factuur sjabloon";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_template']['1'] = "Kies een factuur sjabloon.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['logo']['0'] = "Logo";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['logo']['1'] = "Kies een logo.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['maturity']['0'] = "Vervalperiode";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['maturity']['1'] = "Voer het aantal dagen van de factuur vervalperiode in.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionBefore']['0'] = "Omschrijving voor factuur-regels";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionBefore']['1'] = "Voer de omschrijving voor de factuur-regels in.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionAfter']['0'] = "Omschrijving na factuur-regels";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionAfter']['1'] = "Voer de omschrijving na de factuurregels in.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['basePath']['0'] = "Basismap";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['basePath']['1'] = "Kies een basismap.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periodFolder']['0'] = "Maak periodieke map";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periodFolder']['1'] = "Selecteer waar de periodieke map moet worden aangemaakt.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['daily'] = "Dagelijks";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['weekly'] = "Wekelijks";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['monthly'] = "Maandelijks";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['yearly'] = "Jaarlijks";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['new']['0'] = "Nieuwe factuur sjabloon";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['new']['1'] = "Maak een nieuwe factuur sjabloon.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['edit']['0'] = "Factuur sjabloon bewerken";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['edit']['1'] = "Wijzig factuur sjabloon ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['copy']['0'] = "Factuur sjabloon kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['copy']['1'] = "Dupliceer factuur sjabloon ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['delete']['0'] = "Factuur sjabloon verwijderen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['delete']['1'] = "Verwijder factuur sjabloon ID %s";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['show']['0'] = "Toon factuur sjabloon";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['show']['1'] = "Toon factuur sjabloon ID %s";
 
?>
