<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_tax.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_tax']['tax_legend'] = "Belastingen";
$GLOBALS['TL_LANG']['tl_li_tax']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_tax']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_tax']['rate']['0'] = "Prijs";
$GLOBALS['TL_LANG']['tl_li_tax']['rate']['1'] = "Voer een prijs in.";
$GLOBALS['TL_LANG']['tl_li_tax']['new']['0'] = "Nieuwe belasting";
$GLOBALS['TL_LANG']['tl_li_tax']['new']['1'] = "Nieuwe belasting";
$GLOBALS['TL_LANG']['tl_li_tax']['edit']['0'] = "Belasting bewerken";
$GLOBALS['TL_LANG']['tl_li_tax']['edit']['1'] = "Wijzig belasting ID %s";
$GLOBALS['TL_LANG']['tl_li_tax']['copy']['0'] = "Belasting kopieren";
$GLOBALS['TL_LANG']['tl_li_tax']['copy']['1'] = "Dupliceer belasting ID %s";
$GLOBALS['TL_LANG']['tl_li_tax']['delete']['0'] = "Belasting verwijderen";
$GLOBALS['TL_LANG']['tl_li_tax']['delete']['1'] = "Verwijder belasting ID %s";
$GLOBALS['TL_LANG']['tl_li_tax']['show']['0'] = "Belasting tonen";
$GLOBALS['TL_LANG']['tl_li_tax']['show']['1'] = "Toon belasting ID %s";
 
?>
