<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_service_type.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_service_type']['servicetype_legend'] = "Opdracht type";
$GLOBALS['TL_LANG']['tl_li_service_type']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_service_type']['title']['1'] = "Voer een titel in.";
$GLOBALS['TL_LANG']['tl_li_service_type']['orderNumber']['0'] = "Order nummer";
$GLOBALS['TL_LANG']['tl_li_service_type']['orderNumber']['1'] = "Voer een ordernummer in.";
$GLOBALS['TL_LANG']['tl_li_service_type']['standardPrice']['0'] = "Standaard prijs";
$GLOBALS['TL_LANG']['tl_li_service_type']['standardPrice']['1'] = "Voer een standaard prijs in.";
$GLOBALS['TL_LANG']['tl_li_service_type']['icon']['0'] = "Pictogram";
$GLOBALS['TL_LANG']['tl_li_service_type']['icon']['1'] = "Selecteer een pictogram van 16x16 pixels.";
$GLOBALS['TL_LANG']['tl_li_service_type']['new']['0'] = "Nieuwe opdracht type";
$GLOBALS['TL_LANG']['tl_li_service_type']['new']['1'] = "Maak een nieuwe opdracht type";
$GLOBALS['TL_LANG']['tl_li_service_type']['edit']['0'] = "Opdracht type bewerken";
$GLOBALS['TL_LANG']['tl_li_service_type']['edit']['1'] = "Wijzig opdracht type ID %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['copy']['0'] = "Opdracht type kopieren";
$GLOBALS['TL_LANG']['tl_li_service_type']['copy']['1'] = "Dupliceer opdracht type ID %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['delete']['0'] = "Opdracht type verwijderen";
$GLOBALS['TL_LANG']['tl_li_service_type']['delete']['1'] = "Verwijder opdracht type ID %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['show']['0'] = "Toon opdracht type";
$GLOBALS['TL_LANG']['tl_li_service_type']['show']['1'] = "Toon opdracht type ID %s";
$GLOBALS['TL_LANG']['tl_li_service_type']['defaultIcon'] = "Standaard";
 
?>
