<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/nl/tl_li_invoice_settings.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['invoice_data_legend'] = "Factuur data";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['invoice_number_legend'] = "Factuurnummer";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_maturity']['0'] = "Vervalperiode";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_maturity']['1'] = "Voer het aantal dagen van de factuur vervalperiode in.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation']['0'] = "Factuurnummer generatie";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation']['1'] = "Voer een combinatie van insert tages en tekst hoe het factuurnummer wordt gegenereerd. Er kan gebruik worden gemaakt van {{countInvoices::x}} voor het verkrijgen van factuurnummers. De waarde van x stelt in hoe veel cijfers worden gebruikt, de rest wordt opgevult met nullen.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation_start']['0'] = "Factuurnummer startgetal";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation_start']['1'] = "Voer een getal in waarmee het factuurnummer begint. Hierdoor kan bijvoorbeeld het factuurnummer beginnen met 100 in plaats van 1.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['edit'] = "Factuurinstellingen bewerken";
 
?>
