<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/explain.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['0'] = "Montags / Sonntags";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['0']['1'] = "Definiert, wann eine neue Kalenderwoche beginnt";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['0'] = "Einheitlich";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['1']['1'] = "Die erste Kalenderwoche ist die Woche eines Jahres, die das erste Mal den oben definierten Tag besitzt.";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['0'] = "Mehrheitlich";
$GLOBALS['TL_LANG']['XPL']['li_crm_timekeeping_calendar_week_mode']['2']['1'] = "Die erste Kalenderwoche ist die Woche eines Jahres, die mehr als drei Tage im \"neuen\" Jahr besitzt.";
 
?>
