<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/li_customer.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_customers']['customers'] = "Kunden";
$GLOBALS['TL_LANG']['li_customers']['customer'] = "Kunde";
$GLOBALS['TL_LANG']['li_customers']['noEntries'] = "Keine Einträge gefunden.";