<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/li_customer.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['li_customers']['customers'] = "Kunden";
$GLOBALS['TL_LANG']['li_customers']['customer'] = "Kunde";
$GLOBALS['TL_LANG']['li_customers']['noEntries'] = "Keine Einträge gefunden.";
$GLOBALS['TL_LANG']['li_customers']['customerNew']['0'] = "Neuer Kunde";
$GLOBALS['TL_LANG']['li_customers']['customerNew']['1'] = "Einen neuen Kunden erstellen";
$GLOBALS['TL_LANG']['li_customers']['customerEdit']['0'] = "Kunde bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['customerEdit']['1'] = "Den Kunden mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['customerCopy']['0'] = "Kunde duplizieren";
$GLOBALS['TL_LANG']['li_customers']['customerCopy']['1'] = "Den Kunden mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['li_customers']['customerDelete']['0'] = "Kunde löschen";
$GLOBALS['TL_LANG']['li_customers']['customerDelete']['1'] = "Den Kunden mit der ID %s löschen";
$GLOBALS['TL_LANG']['li_customers']['customerDelete']['2'] = "Soll der Kunde mit der ID %s wirklich gelöscht werden?";
$GLOBALS['TL_LANG']['li_customers']['customerInfo']['0'] = "Kunde anzeigen";
$GLOBALS['TL_LANG']['li_customers']['customerInfo']['1'] = "Den Kunden mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['li_customers']['addressesManage']['0'] = "Adressen verwalten";
$GLOBALS['TL_LANG']['li_customers']['addressesManage']['1'] = "Die Adressen des Kunden mit der ID %s verwalten";
$GLOBALS['TL_LANG']['li_customers']['contactsManage']['0'] = "Kontakte verwalten";
$GLOBALS['TL_LANG']['li_customers']['contactsManage']['1'] = "Die Kontakte des Kunden mit der ID %s verwalten";
$GLOBALS['TL_LANG']['li_customers']['projectNew']['0'] = "Neues Projekt";
$GLOBALS['TL_LANG']['li_customers']['projectNew']['1'] = "Ein neues Projekt erstellen";
$GLOBALS['TL_LANG']['li_customers']['projectEdit']['0'] = "Projekt bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['projectEdit']['1'] = "Das Projekt mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['projectCopy']['0'] = "Projekt duplizieren";
$GLOBALS['TL_LANG']['li_customers']['projectCopy']['1'] = "Das Projekt mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['li_customers']['projectDelete']['0'] = "Projekt löschen";
$GLOBALS['TL_LANG']['li_customers']['projectDelete']['1'] = "Das Projekt mit der ID %s löschen";
$GLOBALS['TL_LANG']['li_customers']['projectDelete']['2'] = "Soll das Projekt mit der ID %s wirklich gelöscht werden?";
$GLOBALS['TL_LANG']['li_customers']['projectInfo']['0'] = "Projekt anzeigen";
$GLOBALS['TL_LANG']['li_customers']['projectInfo']['1'] = "Projekt mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['li_customers']['productNew']['0'] = "Produkt hinzufügen";
$GLOBALS['TL_LANG']['li_customers']['productNew']['1'] = "Einem Projekt ein Produkt hinzufügen";
$GLOBALS['TL_LANG']['li_customers']['productEdit']['0'] = "Produkt bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['productEdit']['1'] = "Das Produkt mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['productCopy']['0'] = "Produkt duplizieren";
$GLOBALS['TL_LANG']['li_customers']['productCopy']['1'] = "Das Produkt mit der ID %s einem weiteren Projekt zuordnen";
$GLOBALS['TL_LANG']['li_customers']['productDelete']['0'] = "Produkt löschen";
$GLOBALS['TL_LANG']['li_customers']['productDelete']['1'] = "Das Produkt mit der ID %s aus dem Projekt löschen";
$GLOBALS['TL_LANG']['li_customers']['productDelete']['2'] = "Soll die Zuordnung des Produkts zu diesem Projekt wirklich gelöscht werden?";
$GLOBALS['TL_LANG']['li_customers']['productInfo']['0'] = "Produkt anzeigen";
$GLOBALS['TL_LANG']['li_customers']['productInfo']['1'] = "Das Produkts mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['li_customers']['serviceNew']['0'] = "Neue Leistung";
$GLOBALS['TL_LANG']['li_customers']['serviceNew']['1'] = "Eine neue Leistung erstellen";
$GLOBALS['TL_LANG']['li_customers']['serviceEdit']['0'] = "Leistung bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['serviceEdit']['1'] = "Die Leistung mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['li_customers']['serviceCopy']['0'] = "Leistung duplizieren";
$GLOBALS['TL_LANG']['li_customers']['serviceCopy']['1'] = "Die Leistung mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['li_customers']['serviceDelete']['0'] = "Leistung löschen";
$GLOBALS['TL_LANG']['li_customers']['serviceDelete']['1'] = "Die Leistung mit der ID %s löschen";
$GLOBALS['TL_LANG']['li_customers']['serviceDelete']['2'] = "Soll die Leistung mit der ID %s wirklich gelöscht werden?";
$GLOBALS['TL_LANG']['li_customers']['serviceInfo']['0'] = "Leistung anzeigen";
$GLOBALS['TL_LANG']['li_customers']['serviceInfo']['1'] = "Die Leistung mit der ID %s anzeigen";
 
?>
