<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_working_hour.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_working_hour']['hour_legend'] = "Stunden erfassen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['entryDate']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_li_working_hour']['entryDate']['1'] = "Datum an dem die Stunden geleistet wurden";
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']['0'] = "Arbeitspaket";
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']['1'] = "Das Arbeitspaket, dem die Arbeitsstunden zugeordnet werden sollen.";
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']['0'] = "Stunden";
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']['1'] = "Anzahl der Stunden";
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']['0'] = "Minuten";
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']['1'] = "Anzahl der Minuten";
$GLOBALS['TL_LANG']['tl_li_working_hour']['editEntry'] = "Stundeneintrag bearbeiten";
$GLOBALS['TL_LANG']['tl_li_working_hour']['deleteEntry'] = "Stundeneintrag löschen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['deleteConfirmDialog'] = "Diesen Stundeneintrag wirklich löschen?";
$GLOBALS['TL_LANG']['tl_li_working_hour']['addHours'] = "Stunden erfassen";
$GLOBALS['TL_LANG']['tl_li_working_hour']['manageWorkPackages'] = "Arbeitspakete verwalten";
$GLOBALS['TL_LANG']['tl_li_working_hour']['editWorkPackage'] = "Zugehöriges Arbeitspaket bearbeiten";
$GLOBALS['TL_LANG']['tl_li_working_hour']['calendar_week'] = "Kalenderwoche";
 
?>
