<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_project_settings.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_project_settings']['project_number_legend'] = "Projektnummer";
$GLOBALS['TL_LANG']['tl_li_project_settings']['li_crm_project_number_generation']['0'] = "Generierung der Projektnummer";
$GLOBALS['TL_LANG']['tl_li_project_settings']['li_crm_project_number_generation']['1'] = "Bitte geben Sie die Kombination von Insert-Tags und Text ein, durch die eine Projektnummer generiert werden soll. Mit {{countProjects::x}} wird die aktuelle Anzahl an Projekten ausgegeben. Der x-Wert bestimmt auf wie viele Stellen die Nummer mit Nullen aufgefüllt werden soll.";
$GLOBALS['TL_LANG']['tl_li_project_settings']['li_crm_project_number_generation_start']['0'] = "Projektzähler Start";
$GLOBALS['TL_LANG']['tl_li_project_settings']['li_crm_project_number_generation_start']['1'] = "Bitte geben Sie die Zahl ein, bei der der Projektzähler startet. Dadurch können Sie die Nummern z. B. ab 100 starten lassen.";
$GLOBALS['TL_LANG']['tl_li_project_settings']['edit'] = "Projekteinstellungen bearbeiten";
 
?>
