<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_task_status.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_status']['status_legend'] = "Status";
$GLOBALS['TL_LANG']['tl_li_task_status']['settings_legend'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_li_task_status']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_task_status']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_task_status']['orderNumber']['0'] = "Sortiernummer";
$GLOBALS['TL_LANG']['tl_li_task_status']['orderNumber']['1'] = "Bitte geben Sie die Sortiernummer ein.";
$GLOBALS['TL_LANG']['tl_li_task_status']['icon']['0'] = "Icon";
$GLOBALS['TL_LANG']['tl_li_task_status']['icon']['1'] = "Bitte wählen Sie das Icon aus. Es sollte die Maße von 16x16 haben.";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDisabled']['0'] = "Aufgabe deaktiviert";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDisabled']['1'] = "Soll die Aufgabe mit diesem Status deaktiviert dargestellt werden?";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDone']['0'] = "Aufgabe erledigt";
$GLOBALS['TL_LANG']['tl_li_task_status']['isTaskDone']['1'] = "Soll die Aufgabe mit diesem Status erledigt dargestellt werden?";
$GLOBALS['TL_LANG']['tl_li_task_status']['cssClass']['0'] = "CSS Klasse";
$GLOBALS['TL_LANG']['tl_li_task_status']['cssClass']['1'] = "Bitte geben Sie die CSS Klasse ein.";
$GLOBALS['TL_LANG']['tl_li_task_status']['new']['0'] = "Neuer Status";
$GLOBALS['TL_LANG']['tl_li_task_status']['new']['1'] = "Einen neuen Status anlegen";
$GLOBALS['TL_LANG']['tl_li_task_status']['edit']['0'] = "Status bearbeiten";
$GLOBALS['TL_LANG']['tl_li_task_status']['edit']['1'] = "Den Status mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_task_status']['copy']['0'] = "Status duplizieren";
$GLOBALS['TL_LANG']['tl_li_task_status']['copy']['1'] = "Den Status mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_task_status']['delete']['0'] = "Status löschen";
$GLOBALS['TL_LANG']['tl_li_task_status']['delete']['1'] = "Den Status mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_task_status']['show']['0'] = "Status anzeigen";
$GLOBALS['TL_LANG']['tl_li_task_status']['show']['1'] = "Den Status mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_task_status']['defaultIcon'] = "Standard";
 
?>