<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_invoice.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_legend'] = "Rechnung";
$GLOBALS['TL_LANG']['tl_li_invoice']['pdf_legend'] = "PDF-Datei";
$GLOBALS['TL_LANG']['tl_li_invoice']['settings_legend'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation_legend'] = "Generierung";
$GLOBALS['TL_LANG']['tl_li_invoice']['publish_legend'] = "Veröffentlichung";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCustomer']['1'] = "Bitte wählen Sie einen Kunden aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCategory']['0'] = "Rechnungskategorie";
$GLOBALS['TL_LANG']['tl_li_invoice']['toCategory']['1'] = "Bitte wählen Sie die Rechnungskategorie aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_li_invoice']['alias']['1'] = "Bitte geben Sie den Alias ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceDate']['0'] = "Rechnungsdatum";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceDate']['1'] = "Bitte geben Sie das Rechnungsdatum ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['performanceDate']['0'] = "Leistungsdatum";
$GLOBALS['TL_LANG']['tl_li_invoice']['performanceDate']['1'] = "Bitte geben Sie das Leistungsdatum ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['price']['0'] = "Preis";
$GLOBALS['TL_LANG']['tl_li_invoice']['price']['1'] = "Bitte geben Sie den Preis ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['currency']['0'] = "Währung";
$GLOBALS['TL_LANG']['tl_li_invoice']['currency']['1'] = "Bitte geben Sie die Währung des Preises an.";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity']['0'] = "Laufzeit";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity']['1'] = "Geben Sie die Anzahl der Tage ein, die der Kunde zur Bezahlung der Rechnung Zeit hat, falls diese von der Standard- und Templateeinstellungen abweicht.";
$GLOBALS['TL_LANG']['tl_li_invoice']['file']['0'] = "Rechnung";
$GLOBALS['TL_LANG']['tl_li_invoice']['file']['1'] = "Bitte wählen Sie die Rechnung aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['isOut']['0'] = "Ausgangsrechnung?";
$GLOBALS['TL_LANG']['tl_li_invoice']['isOut']['1'] = "Ist die Rechnung eine Ausgangsrechnung?";
$GLOBALS['TL_LANG']['tl_li_invoice']['isSingular']['0'] = "Einmalige Rechnung?";
$GLOBALS['TL_LANG']['tl_li_invoice']['isSingular']['1'] = "Ist die Rechnung eine einmalige Rechnung?";
$GLOBALS['TL_LANG']['tl_li_invoice']['enableGeneration']['0'] = "Generierung aktivieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['enableGeneration']['1'] = "Rechnungsgenerierung aktivieren.";
$GLOBALS['TL_LANG']['tl_li_invoice']['headline']['0'] = "Überschrift";
$GLOBALS['TL_LANG']['tl_li_invoice']['headline']['1'] = "Bitte geben Sie die Überschrift ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['toTemplate']['0'] = "Rechnungstemplate";
$GLOBALS['TL_LANG']['tl_li_invoice']['toTemplate']['1'] = "Bitte wählen Sie das Rechnungstemplate aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['toAddress']['0'] = "Rechnungsadresse";
$GLOBALS['TL_LANG']['tl_li_invoice']['toAddress']['1'] = "Bitte wählen Sie die Rechnungsadresse aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionBefore']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionBefore']['1'] = "Bitte geben Sie die Beschreibung vor den Positionen ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['discount'] = array('Rabatt', 'Bitte geben Sie den Rabatt ein.');
$GLOBALS['TL_LANG']['tl_li_invoice']['earlyPaymentDiscount'] = array('Skontotext', 'Bitte geben Sie den Skontotext ein.');
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionAfter']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_li_invoice']['descriptionAfter']['1'] = "Bitte geben Sie die Beschreibung nach den Positionen ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['published']['0'] = "Rechnung veröffentlichen";
$GLOBALS['TL_LANG']['tl_li_invoice']['published']['1'] = "Die Rechnung auf der Website anzeigen.";
$GLOBALS['TL_LANG']['tl_li_invoice']['new']['0'] = "Neue Rechnung";
$GLOBALS['TL_LANG']['tl_li_invoice']['new']['1'] = "Eine neue Rechnung erstellen";
$GLOBALS['TL_LANG']['tl_li_invoice']['edit']['0'] = "Rechnung editieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['edit']['1'] = "Die Rechnung mit der ID %s editieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['copy']['0'] = "Rechnung kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['copy']['1'] = "Die Rechnung mit der ID %s kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['delete']['0'] = "Rechnung löschen";
$GLOBALS['TL_LANG']['tl_li_invoice']['delete']['1'] = "Die Rechnung mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_invoice']['show']['0'] = "Rechnung anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice']['show']['1'] = "Die Rechnung mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice']['toggle']['0'] = "Rechnung veröffentlichen/unveröffentlichen";
$GLOBALS['TL_LANG']['tl_li_invoice']['toggle']['1'] = "Die Rechnung mit der ID %s veröffentlichen/unveröffentlichen";
$GLOBALS['TL_LANG']['tl_li_invoice']['generate']['0'] = "Rechnung generieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['generate']['1'] = "Die Rechnung mit der ID %s generieren";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch']['0'] = "Rechnung verschicken";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch']['1'] = "Die Rechnung mit der ID %s an den Kunden schicken";
$GLOBALS['TL_LANG']['tl_li_invoice']['reports']['0'] = "Berichte";
$GLOBALS['TL_LANG']['tl_li_invoice']['reports']['1'] = "Den Verlauf der Rechnungen anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice']['reminder']['0'] = "Erinnerungen";
$GLOBALS['TL_LANG']['tl_li_invoice']['reminder']['1'] = "Rechnungserinnerungen verwalten";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation']['0'] = 'Generierungen';
$GLOBALS['TL_LANG']['tl_li_invoice']['generation']['1'] = 'Rechnungsgenerierungen verwalten';
$GLOBALS['TL_LANG']['tl_li_invoice']['showFile']['0'] = "Rechnungsdatei anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice']['showFile']['1'] = "Die Rechnungsdatei mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadFile']['0'] = "Rechnung herunterladen";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadFile']['1'] = "Die Rechnung mit der ID %s herunterladen";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_month'] = "Rechnungsverlauf - Monatsübersicht";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_year'] = "Rechnungsverlauf - Jahresübersicht";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_income'] = "Einnahmen";
$GLOBALS['TL_LANG']['tl_li_invoice']['report_expenses'] = "Ausgaben";
$GLOBALS['TL_LANG']['tl_li_invoice']['income'] = "Einnahme";
$GLOBALS['TL_LANG']['tl_li_invoice']['expense'] = "Ausgabe";
$GLOBALS['TL_LANG']['tl_li_invoice']['tax_number'] = "Steuernummer";
$GLOBALS['TL_LANG']['tl_li_invoice']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_number'] = "Rechnungs-Nr.";
$GLOBALS['TL_LANG']['tl_li_invoice']['introduction_male'] = "Sehr geehrter Herr %s,<br />für Ihren Auftrag bedanke ich mich und berechne folgendes für meine Leistungen.";
$GLOBALS['TL_LANG']['tl_li_invoice']['introduction_female'] = "Sehr geehrte Frau %s,<br />für Ihren Auftrag bedanke ich mich und berechne folgendes für meine Leistungen.";
$GLOBALS['TL_LANG']['tl_li_invoice']['servicePositions']['0'] = "Leistungen";
$GLOBALS['TL_LANG']['tl_li_invoice']['servicePositions']['1'] = "Bitte wählen Sie die Leistungspositionen aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['productPositions']['0'] = "Produkte";
$GLOBALS['TL_LANG']['tl_li_invoice']['productPositions']['1'] = "Bitte wählen Sie die Produktpositionen aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['hourPositions']['0'] = "Stunden";
$GLOBALS['TL_LANG']['tl_li_invoice']['hourPositions']['1'] = "Bitte wählen Sie die Stundenpositionen aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_quantity']['0'] = "Anzahl";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_quantity']['1'] = "Bitte geben Sie die Anzahl für diese Position ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit']['0'] = "Einheit";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit']['1'] = "Bitte wählen Sie die Einheit für diese Position aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_item']['0'] = "Referenz";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_item']['1'] = "Bitte wählen Sie die Referenz im CRM aus.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_label']['0'] = "Bezeichnung";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_label']['1'] = "Bitte geben Sie die Bezeichnung für diese Position ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit_price']['0'] = "Einzelpreis";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_unit_price']['1'] = "Bitte geben Sie den Einzelpreis für diese Position ein.";
$GLOBALS['TL_LANG']['tl_li_invoice']['position_total_price'] = "Gesamtpreis";
$GLOBALS['TL_LANG']['tl_li_invoice']['performance_is_invoice_date'] = "Das Rechnungsdatum entspricht dem Leistungsdatum.";
$GLOBALS['TL_LANG']['tl_li_invoice']['performance_date_at'] = "Leistungsdatum: %s";
$GLOBALS['TL_LANG']['tl_li_invoice']['account_data'] = "Kontodaten";
$GLOBALS['TL_LANG']['tl_li_invoice']['account_number'] = "Kontonummer";
$GLOBALS['TL_LANG']['tl_li_invoice']['bank_code'] = "BLZ";
$GLOBALS['TL_LANG']['tl_li_invoice']['bank'] = "Bank";
$GLOBALS['TL_LANG']['tl_li_invoice']['maturity_remark'] = "Bitte überweisen Sie den Rechnungsbetrag innerhalb der nächsten %s Tagen.";
$GLOBALS['TL_LANG']['tl_li_invoice']['greeting'] = "Mit freundlichen Grüßen<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['service'] = "Leistungen";
$GLOBALS['TL_LANG']['tl_li_invoice']['products'] = "Produkte";
$GLOBALS['TL_LANG']['tl_li_invoice']['hours'] = "Stunden";
$GLOBALS['TL_LANG']['tl_li_invoice']['total_netto'] = "Rechnungsbetrag (netto)";
$GLOBALS['TL_LANG']['tl_li_invoice']['total_brutto'] = "Rechnungsbetrag (brutto)";
$GLOBALS['TL_LANG']['tl_li_invoice']['tax'] = "Umsatzsteuer";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['unit'] = "Stück";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['hour'] = "Stunde";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['month'] = "Monat";
$GLOBALS['TL_LANG']['tl_li_invoice']['units']['year'] = "Jahr";
$GLOBALS['TL_LANG']['tl_li_invoice']['discountOptions']['percent'] = '%';
$GLOBALS['TL_LANG']['tl_li_invoice']['discountOptions']['value'] = 'Wert';
$GLOBALS['TL_LANG']['tl_li_invoice']['details'] = "Details";
$GLOBALS['TL_LANG']['tl_li_invoice']['downloadInvoice'] = "Rechnung runterladen";
$GLOBALS['TL_LANG']['tl_li_invoice']['noInvoicesAvailable'] = "Keine Rechnungen verfügbar.";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoiceNotFound'] = "Rechnung nicht gefunden.";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_generation'] = "Rechnungsgenerierung";
$GLOBALS['TL_LANG']['tl_li_invoice']['generation_success'] = "Die Rechnung wurde erfolgreich generiert.";
$GLOBALS['TL_LANG']['tl_li_invoice']['back_overview'] = "Zurück zur Übersicht";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_subject'] = "Rechnung";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_text_male'] = "Sehr geehrter Herr %s,\n\nanbei die neue Rechnung vom %s.\n\nMit freundlichen Grüßen\n%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_text_female'] = "Sehr geehrte Frau %s,\n\nanbei die neue Rechnung vom %s.\n\nMit freundlichen Grüßen\n%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_html_male'] = "Sehr geehrter Herr %s,<br /><br />anbei die neue Rechnung vom %s.<br /><br />Mit freundlichen Grüßen<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_html_female'] = "Sehr geehrte Frau %s,<br /><br />anbei die neue Rechnung vom %s.<br /><br />Mit freundlichen Grüßen<br />%s";
$GLOBALS['TL_LANG']['tl_li_invoice']['invoice_dispatch'] = "Rechnungsversand";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_successful'] = "Die Rechnung wurde erfolgreich versant.";
$GLOBALS['TL_LANG']['tl_li_invoice']['dispatch_failed'] = "Die Rechnung konnte nicht versant werden. Genauere Informationen entnehmen Sie bitte dem System Log.";
$GLOBALS['TL_LANG']['tl_li_invoice']['generatedInvoiceName'] = "Rechnung ";
 
?>
