<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_task_comment.php
 *
 * Contao extension: li_crm 0.4.0 alpha1
 * Deutsch translation file
 *
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb
 * License   : MIT
 * Author    : Christian Kolb (Liplex), www.liplex.de
 * Author    : Tristan Lins (InfinitySoft), www.infinitysoft.de
 * Translator: Christian Kolb (Liplex), www.liplex.de
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */


/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_li_task_comment']['settings_legend'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_li_task_comment']['comment_legend']  = "Kommentar";
$GLOBALS['TL_LANG']['tl_li_task_comment']['toCustomer']      = array("Einem anderen Kunden zuweisen", "Bitte wählen Sie einen Kunden aus.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['toProject']       = array("Einem anderen Projekt zuweisen", "Bitte wählen Sie einen Projekt aus.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['priority']        = array("Neue Priorität zuweisen", "Bitte wählen Sie die Prioriät aus.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['title']           = array("Neuen Titel zuweisen", "Bitte geben Sie den Titel ein.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['deadline']        = array("Neue Deadline zuweisen", "Bitte geben Sie das Datum ein bis zu dem die Aufgabe abgeschlossen sein muss.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['toStatus']        = array("Einen neuen Status zuweisen", "Bitte wählen Sie den Status der Aufgabe aus.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['toUser']          = array("Zugewiesen an", "Bitte wählen Sie den Benutzer aus der sich um die Aufgabe kümmern soll.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['comment']         = array("Kommentar", "Bitte geben Sie einen Kommentar ein.");
$GLOBALS['TL_LANG']['tl_li_task_comment']['keeptime']        = array("Aufgewendete Zeit erfassen", "Die aufgewendete Zeit erfassen.");
$GLOBALS['TL_LANG']['tl_li_working_hour']['hours']           = array("Stunden", "Anzahl der Stunden");
$GLOBALS['TL_LANG']['tl_li_working_hour']['minutes']         = array("Minuten", "Anzahl der Minuten");
$GLOBALS['TL_LANG']['tl_li_working_hour']['toWorkPackage']   = array("Arbeitspaket", "Das Arbeitspaket, dem die Arbeitsstunden zugeordnet werden sollen.");


/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_li_task_comment']['new']  = array("Neuer Kommentar", "Einen neuen Kommentar erstellen");
$GLOBALS['TL_LANG']['tl_li_task_comment']['edit'] = array("Kommentar editieren", "Den Kommentar mit der ID %s editieren");


/**
 * BE listing
 */
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeNoCustomer']      = '&rarr; Zuweisung zu Kunde gelöscht';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeCustomerProject'] = '&rarr; zugewiesen zu Kunde %s, Projekt %s';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeCustomer']        = '&rarr; zugewiesen zu Kunde %s';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changePriority']        = '&rarr; neue Priorität %s';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeTitle']           = '&rarr; Titel aktualisiert';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeDeadline']        = '&rarr; neue Deadline %s';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeStatus']          = '&rarr; Status zu %2$s geändert';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['changeUser']            = '&rarr; neu zugewiesen an %2$s';
$GLOBALS['TL_LANG']['tl_li_task_comment']['be_task_comment']['keeptime']              = '&rarr; benötigte Zeit %d:%02d in %s';
