<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_product_type.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product_type']['type_legend'] = "Produkttyp";
$GLOBALS['TL_LANG']['tl_li_product_type']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_product_type']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_product_type']['icon']['0'] = "Icon";
$GLOBALS['TL_LANG']['tl_li_product_type']['icon']['1'] = "Bitte wählen Sie das Icon aus. Es sollte die Maße von 16x16 haben.";
$GLOBALS['TL_LANG']['tl_li_product_type']['new']['0'] = "Neuer Produkttyp";
$GLOBALS['TL_LANG']['tl_li_product_type']['new']['1'] = "Einen neuen Produkttyp anlegen";
$GLOBALS['TL_LANG']['tl_li_product_type']['edit']['0'] = "Produkttyp bearbeiten";
$GLOBALS['TL_LANG']['tl_li_product_type']['edit']['1'] = "Den Produkttyp mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_product_type']['copy']['0'] = "Produkttyp duplizieren";
$GLOBALS['TL_LANG']['tl_li_product_type']['copy']['1'] = "Den Produkttyp mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_product_type']['delete']['0'] = "Produkttyp löschen";
$GLOBALS['TL_LANG']['tl_li_product_type']['delete']['1'] = "Den Produkttyp mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_product_type']['show']['0'] = "Produkttyp anzeigen";
$GLOBALS['TL_LANG']['tl_li_product_type']['show']['1'] = "Den Produkttyp mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_product_type']['defaultIcon'] = "Standard";
 
?>
