<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_invoice_settings.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['invoice_data_legend'] = "Rechnungsdaten";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['invoice_number_legend'] = "Rechnungsnummer";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_maturity']['0'] = "Laufzeit";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_maturity']['1'] = "Geben Sie die Anzahl der Tage ein die der Kunde zur Bezahlung der Rechnung Zeit hat.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation']['0'] = "Generierung der Rechnungsnummer";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation']['1'] = "Bitte geben Sie die Kombination von Insert-Tags und Text ein, durch die eine Rechnungsnummer generiert werden soll. Mit {{countInvoices::x}} wird die aktuelle Anzahl der Ausgangsrechnungen ausgegeben. Der x-Wert bestimmt auf wie viele Stellen die Rechnungsnummer mit Nullen aufgefüllt werden soll.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation_start']['0'] = "Rechnungsnummer Start";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['li_crm_invoice_number_generation_start']['1'] = "Bitte geben Sie die Zahl ein, bei der der Rechnungszähler startet. Dadurch können Sie die Nummern z. B. ab 100 starten lassen.";
$GLOBALS['TL_LANG']['tl_li_invoice_settings']['edit'] = "Rechnungseinstellungen bearbeiten";
 
?>
