<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_hourly_wage.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage_legend'] = "Stundensatz";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['price_legend'] = "Preis";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['title']['0'] = "Bezeichnung";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['title']['1'] = "Bitte geben Sie die Bezeichnung des Stundensatzes ein.";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage']['0'] = "Stundensatz";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['wage']['1'] = "Bitte geben Sie die Bezahlung pro Stunde in diesem Stundensatz (Netto) ein.";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['toTax']['0'] = "Steuersatz";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['toTax']['1'] = "Bitte wählen Sie den Steuersatz aus.";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['currency']['0'] = "Währung";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['currency']['1'] = "Bitte geben Sie die Währung des Preises an.";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['new']['0'] = "Neuer Stundensatz";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['new']['1'] = "Einen neuen Stundensatz erstellen";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['edit']['0'] = "Stundensatz bearbeiten";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['edit']['1'] = "Den Stundensatz mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['copy']['0'] = "Stundensatz duplizieren";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['copy']['1'] = "Den Stundensatz mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['delete']['0'] = "Stundnesatz löschen";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['delete']['1'] = "Den Stundensatz mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['show']['0'] = "Stundensatz anzeigen";
$GLOBALS['TL_LANG']['tl_li_hourly_wage']['show']['1'] = "Den Stundensatze mit der ID %s anzeigen";
 
?>
