<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_invoice_generation.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['invoice_legend'] = "Rechnung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generation_legend'] = "Generierung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['settings_legend'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCustomer']['1'] = "Bitte wählen Sie einen Kunden aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCategory']['0'] = "Rechnungskategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toCategory']['1'] = "Bitte wählen Sie die Rechnungskategorie aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['alias']['1'] = "Bitte geben Sie den Alias ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['currency']['0'] = "Währung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['currency']['1'] = "Bitte geben Sie die Währung des Preises an.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['maturity']['0'] = "Laufzeit";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['maturity']['1'] = "Geben Sie die Anzahl der Tage ein, die der Kunde zur Bezahlung der Rechnung Zeit hat, falls diese von der Standard- und Templateeinstellungen abweicht.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['headline']['0'] = "Überschrift";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['headline']['1'] = "Bitte geben Sie die Überschrift ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toTemplate']['0'] = "Rechnungstemplate";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toTemplate']['1'] = "Bitte wählen Sie das Rechnungstemplate aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toAddress']['0'] = "Rechnungsadresse";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['toAddress']['1'] = "Bitte wählen Sie die Rechnungsadresse aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['startDate'] = array('Startdatum', 'Bitte geben Sie das Startdatum ein.');
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInverval'] = array('Intervall', 'Bitte wählen Sie den Intervall aus.');
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['descriptionBefore']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['descriptionBefore']['1'] = "Bitte geben Sie die Beschreibung vor den Positionen ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['discount'] = array('Rabatt', 'Bitte geben Sie den Rabatt ein.');
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['earlyPaymentDiscount'] = array('Skontotext', 'Bitte geben Sie den Skontotext ein.');
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['descriptionAfter']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['descriptionAfter']['1'] = "Bitte geben Sie die Beschreibung nach den Positionen ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['publishImmediately']['0'] = "Rechnung sofort veröffentlichen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['publishImmediately']['1'] = "Die Rechnung sofort auf der Website anzeigen.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['sendImmediately']['0'] = "Rechnung sofort verschicken";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['sendImmediately']['1'] = "Die Rechnung sofort verschicken.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['new']['0'] = "Neue Generierung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['new']['1'] = "Eine neue Generierung erstellen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['edit']['0'] = "Generierung editieren";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['edit']['1'] = "Die Generierung mit der ID %s editieren";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['copy']['0'] = "Generierung kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['copy']['1'] = "Die Generierung mit der ID %s kopieren";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['delete']['0'] = "Generierung löschen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['delete']['1'] = "Die Generierung mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['show']['0'] = "Generierung anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['show']['1'] = "Die Generierung mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['fixedPositions']['0'] = "Fixe Positionen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['fixedPositions']['1'] = "Soll die Generierung mit fixen Positionen arbeiten?";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['servicePositions']['0'] = "Leistungen";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['servicePositions']['1'] = "Bitte wählen Sie die Leistungspositionen aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['productPositions']['0'] = "Produkte";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['productPositions']['1'] = "Bitte wählen Sie die Produktpositionen aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['hourPositions']['0'] = "Stunden";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['hourPositions']['1'] = "Bitte wählen Sie die Stundenpositionen aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_quantity']['0'] = "Anzahl";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_quantity']['1'] = "Bitte geben Sie die Anzahl für diese Position ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit']['0'] = "Einheit";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit']['1'] = "Bitte wählen Sie die Einheit für diese Position aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_item']['0'] = "Referenz";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_item']['1'] = "Bitte wählen Sie die Referenz im CRM aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_label']['0'] = "Bezeichnung";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_label']['1'] = "Bitte geben Sie die Bezeichnung für diese Position ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit_price']['0'] = "Einzelpreis";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_unit_price']['1'] = "Bitte geben Sie den Einzelpreis für diese Position ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['position_total_price'] = "Gesamtpreis";
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['discountOptions']['percent'] = '%';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['discountOptions']['value'] = 'Wert';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['weekly'] = 'Wöchentlich';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['biweekly'] = 'Zweiwöchentlich';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['monthly'] = 'Monatlich';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['bimonthly'] = 'Zweimonatlich';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['quarterly'] = 'Vierteljährlich';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['half-yearly'] = 'Halbjährlich';
$GLOBALS['TL_LANG']['tl_li_invoice_generation']['generationInvervals']['yearly'] = 'Jährlich';