<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_work_package.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_work_package']['package_legend'] = "Arbeitspaket";
$GLOBALS['TL_LANG']['tl_li_work_package']['settings_legend'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_li_work_package']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_work_package']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_work_package']['hourLimit']['0'] = "Stundenlimit";
$GLOBALS['TL_LANG']['tl_li_work_package']['hourLimit']['1'] = "Bitte geben Sie ein Stundenlimit ein.";
$GLOBALS['TL_LANG']['tl_li_work_package']['toHourlyWage']['0'] = "Stundensatz";
$GLOBALS['TL_LANG']['tl_li_work_package']['toHourlyWage']['1'] = "Der Stundensatz, der für dieses Arbeitspaket berechnet wird.";
$GLOBALS['TL_LANG']['tl_li_work_package']['isExternal']['0'] = "Extern";
$GLOBALS['TL_LANG']['tl_li_work_package']['isExternal']['1'] = "Handelt es sich um ein externes Arbeitspaket?";
$GLOBALS['TL_LANG']['tl_li_work_package']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_work_package']['toCustomer']['1'] = "Bitte wählen Sie den Kunden aus, dem diese Leistung zugeordnet werden soll. Dies überschreibt die bei \"Projekt\" ausgewählte Option.";
$GLOBALS['TL_LANG']['tl_li_work_package']['toProject']['0'] = "Projekt";
$GLOBALS['TL_LANG']['tl_li_work_package']['toProject']['1'] = "Bitte wählen Sie ein Projekt aus.";
$GLOBALS['TL_LANG']['tl_li_work_package']['printOnInvoice']['0'] = "Auf Rechnung drucken";
$GLOBALS['TL_LANG']['tl_li_work_package']['printOnInvoice']['1'] = "Sollen die Stunden auf eine Rechnung gedruckt werden können?";
$GLOBALS['TL_LANG']['tl_li_work_package']['new']['0'] = "Neues Arbeitspaket";
$GLOBALS['TL_LANG']['tl_li_work_package']['new']['1'] = "Ein neues Arbeitspaket anlegen";
$GLOBALS['TL_LANG']['tl_li_work_package']['edit']['0'] = "Arbeitspaket bearbeiten";
$GLOBALS['TL_LANG']['tl_li_work_package']['edit']['1'] = "Das Arbeitspaket mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_work_package']['copy']['0'] = "Arbeitspaket duplizieren";
$GLOBALS['TL_LANG']['tl_li_work_package']['copy']['1'] = "Das Arbeitspaket mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_work_package']['delete']['0'] = "Arbeitspaket löschen";
$GLOBALS['TL_LANG']['tl_li_work_package']['delete']['1'] = "Das Arbeitspaket mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_work_package']['show']['0'] = "Arbeitspaket anzeigen";
$GLOBALS['TL_LANG']['tl_li_work_package']['show']['1'] = "Das Arbeitspakets mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_work_package']['internal'] = "Intern";
 
?>
