<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_invoice_template.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_template']['template_legend'] = "Rechnungstemplate";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_data_legend'] = "Rechnungsdaten";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['generation_path_legend'] = "Generierungspfad";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_template']['0'] = "Rechnungs-Template";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['invoice_template']['1'] = "Bitte wählen Sie das Rechnungs-Template aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['logo']['0'] = "Logo";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['logo']['1'] = "Bitte wählen Sie das Logo aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['maturity']['0'] = "Laufzeit";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['maturity']['1'] = "Geben Sie die Anzahl der Tage ein, die der Kunde zur Bezahlung der Rechnung Zeit hat, falls diese von der Standardeinstellungen abweicht.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionBefore']['0'] = "Beschreibung vor den Positionen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionBefore']['1'] = "Bitte geben Sie die Beschreibung vor den Positionen ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionAfter']['0'] = "Beschreibung nach den Positionen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['descriptionAfter']['1'] = "Bitte geben Sie die Beschreibung nach den Positionen ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['basePath']['0'] = "Basispfad";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['basePath']['1'] = "Bitte wählen Sie den Basisordner aus.";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periodFolder']['0'] = "Periodischen Ordner erstellen?";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periodFolder']['1'] = "Soll ein zusätzlicher periodischer Ordner erstellt werden?";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['daily'] = "Täglich";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['weekly'] = "Wöchentlich";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['monthly'] = "Monatlich";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['periods']['yearly'] = "Jährlich";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['new']['0'] = "Neues Rechnungstemplate";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['new']['1'] = "Ein neues Rechnungstemplate anlegen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['edit']['0'] = "Rechnungstemplate bearbeiten";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['edit']['1'] = "Das Rechnungstemplate mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['copy']['0'] = "Rechnungstemplate duplizieren";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['copy']['1'] = "Das Rechnungstemplate mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['delete']['0'] = "Rechnungstemplate löschen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['delete']['1'] = "Das Rechnungstemplate mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['show']['0'] = "Rechnungstemplate anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice_template']['show']['1'] = "Das Rechnungstemplate mit der ID %s anzeigen";
 
?>
