<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_invoice_dispatch_settings.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['dispatch_legend'] = "Versand";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_from']['0'] = "Absender E-Mail";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_from']['1'] = "Bitte geben Sie die E-Mail Adresse des Absenders ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_fromName']['0'] = "Absender Name";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['li_crm_invoice_dispatch_fromName']['1'] = "Bitte geben Sie den Namen des Absenders ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_dispatch_settings']['edit'] = "Versandeinstellungen bearbeiten";
 
?>
