<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_tax.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_tax']['tax_legend'] = "Steuersätze";
$GLOBALS['TL_LANG']['tl_li_tax']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_tax']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_tax']['rate']['0'] = "Steuersatz";
$GLOBALS['TL_LANG']['tl_li_tax']['rate']['1'] = "Bitte geben Sie den Steuersatz ein.";
$GLOBALS['TL_LANG']['tl_li_tax']['new']['0'] = "Neuer Steuersatz";
$GLOBALS['TL_LANG']['tl_li_tax']['new']['1'] = "Einen neuen Steuersatz anlegen";
$GLOBALS['TL_LANG']['tl_li_tax']['edit']['0'] = "Steuersatz bearbeiten";
$GLOBALS['TL_LANG']['tl_li_tax']['edit']['1'] = "Den Steuersatz mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_tax']['copy']['0'] = "Steuersatz duplizieren";
$GLOBALS['TL_LANG']['tl_li_tax']['copy']['1'] = "Den Steuersatz mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_tax']['delete']['0'] = "Steuersatz löschen";
$GLOBALS['TL_LANG']['tl_li_tax']['delete']['1'] = "Den Steuersatz mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_tax']['show']['0'] = "Steuersatz anzeigen";
$GLOBALS['TL_LANG']['tl_li_tax']['show']['1'] = "Den Steuersatz mit der ID %s anzeigen";
 
?>
