<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_project.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_project']['project_legend'] = "Projekt";
$GLOBALS['TL_LANG']['tl_li_project']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_project']['toCustomer']['1'] = "Zu welchem Kunden gehört das Projekt?";
$GLOBALS['TL_LANG']['tl_li_project']['projectNumber']['0'] = "Projektnummer";
$GLOBALS['TL_LANG']['tl_li_project']['projectNumber']['1'] = "Bitte geben Sie die Projektnummer ein.";
$GLOBALS['TL_LANG']['tl_li_project']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_project']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_project']['new']['0'] = "Neues Projekt";
$GLOBALS['TL_LANG']['tl_li_project']['new']['1'] = "Ein neues Projekt anlegen";
$GLOBALS['TL_LANG']['tl_li_project']['edit']['0'] = "Projekt bearbeiten";
$GLOBALS['TL_LANG']['tl_li_project']['edit']['1'] = "Das Projekt mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_project']['copy']['0'] = "Projekt duplizieren";
$GLOBALS['TL_LANG']['tl_li_project']['copy']['1'] = "Das Projekt mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_project']['delete']['0'] = "Projekt löschen";
$GLOBALS['TL_LANG']['tl_li_project']['delete']['1'] = "Das Projekt mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_project']['show']['0'] = "Projekt anzeigen";
$GLOBALS['TL_LANG']['tl_li_project']['show']['1'] = "Das Projekt mit der ID %s anzeigen";
 
?>
