<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_task_reminder.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task_reminder']['reminder_legend'] = "Erinnerung";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['once_legend'] = "Einmalig";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['repeatedly_legend'] = "Wiederholt";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toCustomer']['1'] = "Bitte wählen Sie einen Kunden aus.";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toTask']['0'] = "Aufgabe";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['toTask']['1'] = "Bitte wählen Sie die Aufgabe aus. (Aufgaben, deren Deadline verstrichen ist, werden nicht angezeigt!)";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindOnce']['0'] = "Einmalig erinnern";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindOnce']['1'] = "Soll einmalig eine Erinnerung verschickt werden?";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindDate']['0'] = "Erinnerungsdatum";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindDate']['1'] = "Bitte geben Sie das Datum, an dem die Erinnerung verschickt werden soll, ein.";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindRepeatedly']['0'] = "Wiederholt erinnern";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindRepeatedly']['1'] = "Soll die Erinnerung im Intervall bis zur Deadline verschickt werden?";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['0'] = "Intervall";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['1'] = "Bitte wählen Sie den Intervall aus.";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['daily'] = "Täglich";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['weekly'] = "Wöchentlich";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['monthly'] = "Monatlich";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['remindInterval']['yearly'] = "Jährlich";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['new']['0'] = "Neue Erinnerung";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['new']['1'] = "Eine neue Erinnerung erstellen";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['edit']['0'] = "Erinnerung editieren";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['edit']['1'] = "Die Erinnerung mit der ID %s editieren";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['copy']['0'] = "Erinnerung kopieren";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['copy']['1'] = "Die Erinnerung mit der ID %s kopieren";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['delete']['0'] = "Erinnerung löschen";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['delete']['1'] = "Die Erinnerung mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['show']['0'] = "Erinnerung anzeigen";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['show']['1'] = "Die Erinnerung mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['noProject'] = "Kein Projekt";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['noCustomer'] = "Kein Kunde";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['subject'] = "Aufgabenerinnerung";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['text'] = "Aufgabenerinnerung für die Aufgabe \"%s\" mit der Deadline %s.";
$GLOBALS['TL_LANG']['tl_li_task_reminder']['customerRemark'] = "Die Aufgabe gehört zum Kunden \"%s %s\".";
 
?>
