<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_product_to_customer.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['product_legend'] = "Produktzuordnung";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toCustomer']['1'] = "Der Kunde, zu dessen Projekt ein Produkt hinzugefügt werden soll.";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProject']['0'] = "Projekt";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProject']['1'] = "Das Projekt des Kunden, zu dem das Produkt hinzugefügt werden soll.";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProduct']['0'] = "Produkt";
$GLOBALS['TL_LANG']['tl_li_product_to_customer']['toProduct']['1'] = "Das Produkt, das hinzugefügt werden soll.";
 
?>
