<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_product.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_product']['product_legend'] = "Produkt";
$GLOBALS['TL_LANG']['tl_li_product']['price_legend'] = "Preis";
$GLOBALS['TL_LANG']['tl_li_product']['toProductType']['0'] = "Produkttyp";
$GLOBALS['TL_LANG']['tl_li_product']['toProductType']['1'] = "Bitte wählen Sie den Produkttyp aus.";
$GLOBALS['TL_LANG']['tl_li_product']['number']['0'] = "Nummer";
$GLOBALS['TL_LANG']['tl_li_product']['number']['1'] = "Bitte geben Sie die Nummer ein.";
$GLOBALS['TL_LANG']['tl_li_product']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_product']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_product']['price']['0'] = "Preis";
$GLOBALS['TL_LANG']['tl_li_product']['price']['1'] = "Bitte geben Sie den Preis ein.";
$GLOBALS['TL_LANG']['tl_li_product']['currency']['0'] = "Währung";
$GLOBALS['TL_LANG']['tl_li_product']['currency']['1'] = "Bitte geben Sie die Währung des Preises an.";
$GLOBALS['TL_LANG']['tl_li_product']['toTax']['0'] = "Steuersatz";
$GLOBALS['TL_LANG']['tl_li_product']['toTax']['1'] = "Bitte wählen Sie den Steuersatz aus.";
$GLOBALS['TL_LANG']['tl_li_product']['new']['0'] = "Neues Produkt";
$GLOBALS['TL_LANG']['tl_li_product']['new']['1'] = "Ein neue Produkt anlegen";
$GLOBALS['TL_LANG']['tl_li_product']['edit']['0'] = "Produkt bearbeiten";
$GLOBALS['TL_LANG']['tl_li_product']['edit']['1'] = "Das Produkt mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_product']['copy']['0'] = "Produkt duplizieren";
$GLOBALS['TL_LANG']['tl_li_product']['copy']['1'] = "Das Produkt mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_product']['delete']['0'] = "Produkt löschen";
$GLOBALS['TL_LANG']['tl_li_product']['delete']['1'] = "Das Produkt mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_product']['show']['0'] = "Produkt anzeigen";
$GLOBALS['TL_LANG']['tl_li_product']['show']['1'] = "Das Produkt mit der ID %s anzeigen";
 
?>
