<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_task.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_task']['settings_legend'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_li_task']['task_legend'] = "Aufgabe";
$GLOBALS['TL_LANG']['tl_li_task']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_task']['toCustomer']['1'] = "Bitte wählen Sie einen Kunden aus.";
$GLOBALS['TL_LANG']['tl_li_task']['toProject']['0'] = "Projekt";
$GLOBALS['TL_LANG']['tl_li_task']['toProject']['1'] = "Bitte wählen Sie einen Projekt aus.";
$GLOBALS['TL_LANG']['tl_li_task']['toStatus']['0'] = "Status";
$GLOBALS['TL_LANG']['tl_li_task']['toStatus']['1'] = "Bitte wählen Sie den Status der Aufgabe aus.";
$GLOBALS['TL_LANG']['tl_li_task']['toUser']['0'] = "Zugewiesen an";
$GLOBALS['TL_LANG']['tl_li_task']['toUser']['1'] = "Bitte wählen Sie den Benutzer aus der sich um die Aufgabe kümmern soll.";
$GLOBALS['TL_LANG']['tl_li_task']['priority']['0'] = "Priorität";
$GLOBALS['TL_LANG']['tl_li_task']['priority']['1'] = "Bitte wählen Sie die Prioriät aus.";
$GLOBALS['TL_LANG']['tl_li_task']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_task']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_task']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_li_task']['alias']['1'] = "Bitte geben Sie den Alias ein.";
$GLOBALS['TL_LANG']['tl_li_task']['deadline']['0'] = "Deadline";
$GLOBALS['TL_LANG']['tl_li_task']['deadline']['1'] = "Bitte geben Sie das Datum ein bis zu dem die Aufgabe abgeschlossen sein muss.";
$GLOBALS['TL_LANG']['tl_li_task']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_li_task']['description']['1'] = "Bitte geben Sie die Beschreibung ein.";
$GLOBALS['TL_LANG']['tl_li_task']['new']['0'] = "Neue Aufgabe";
$GLOBALS['TL_LANG']['tl_li_task']['new']['1'] = "Eine neue Aufgabe erstellen";
$GLOBALS['TL_LANG']['tl_li_task']['edit']['0'] = "Aufgabe editieren";
$GLOBALS['TL_LANG']['tl_li_task']['edit']['1'] = "Die Aufgabe mit der ID %s editieren";
$GLOBALS['TL_LANG']['tl_li_task']['copy']['0'] = "Aufgabe kopieren";
$GLOBALS['TL_LANG']['tl_li_task']['copy']['1'] = "Die Aufgabe mit der ID %s kopieren";
$GLOBALS['TL_LANG']['tl_li_task']['delete']['0'] = "Aufgabe löschen";
$GLOBALS['TL_LANG']['tl_li_task']['delete']['1'] = "Die Aufgabe mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_task']['show']['0'] = "Aufgabe anzeigen";
$GLOBALS['TL_LANG']['tl_li_task']['show']['1'] = "Die Aufgabe mit der ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_li_task']['noCustomer'] = "Kein Kunde";
$GLOBALS['TL_LANG']['tl_li_task']['reminder']['0'] = "Aufgabenerinnerungen";
$GLOBALS['TL_LANG']['tl_li_task']['reminder']['1'] = "Aufgabenerinnerungen verwalten";
 
?>
