<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_timekeeping_settings.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendar_legend'] = "Kalender einstellen";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['li_crm_timekeeping_week_mode']['0'] = "Beginn einer Kalenderwoche";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['li_crm_timekeeping_week_mode']['1'] = "Legt fest, wann eine Kalenderwoche beginnt und wie mit dem Jahreswechsel beim Zählen der Kalenderwochen umgegangen werden soll.";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['7'] = "Montags / Einheitlich";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['3'] = "Montags / Mehrheitlich";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['2'] = "Sonntags / Einheitlich";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['calendarWeekModeOptions']['6'] = "Sonntags / Mehrheitlich";
$GLOBALS['TL_LANG']['tl_li_timekeeping_settings']['edit'] = "Stundenerfassung einstellen";
 
?>
