<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_service.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_service']['service_legend'] = "Leistung";
$GLOBALS['TL_LANG']['tl_li_service']['price_legend'] = "Preis";
$GLOBALS['TL_LANG']['tl_li_service']['date_legend'] = "Datum";
$GLOBALS['TL_LANG']['tl_li_service']['toCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_li_service']['toCustomer']['1'] = "Bitte wählen Sie den Kunden aus, dem diese Leistung zugeordnet werden soll. Dies überschreibt die bei \"Projekt\" ausgewählte Option.";
$GLOBALS['TL_LANG']['tl_li_service']['toProject']['0'] = "Projekt";
$GLOBALS['TL_LANG']['tl_li_service']['toProject']['1'] = "Bitte wählen Sie das Projekt aus. Nur wirksam, wenn bei \"Kunde\" kein Kunde ausgewählt ist.";
$GLOBALS['TL_LANG']['tl_li_service']['toServiceType']['0'] = "Leistungstyp";
$GLOBALS['TL_LANG']['tl_li_service']['toServiceType']['1'] = "Bitte wählen Sie den Leistungstyp aus.";
$GLOBALS['TL_LANG']['tl_li_service']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_service']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_service']['price']['0'] = "Preis";
$GLOBALS['TL_LANG']['tl_li_service']['price']['1'] = "Bitte geben Sie den Preis ein.";
$GLOBALS['TL_LANG']['tl_li_service']['toTax']['0'] = "Steuersatz";
$GLOBALS['TL_LANG']['tl_li_service']['toTax']['1'] = "Bitte wählen Sie den Steuersatz aus.";
$GLOBALS['TL_LANG']['tl_li_service']['currency']['0'] = "Währung";
$GLOBALS['TL_LANG']['tl_li_service']['currency']['1'] = "Bitte geben Sie die Währung des Preises an.";
$GLOBALS['TL_LANG']['tl_li_service']['startDate']['0'] = "Startdatum";
$GLOBALS['TL_LANG']['tl_li_service']['startDate']['1'] = "Bitte geben Sie das Startdatum ein.";
$GLOBALS['TL_LANG']['tl_li_service']['endDate']['0'] = "Enddatum";
$GLOBALS['TL_LANG']['tl_li_service']['endDate']['1'] = "Bitte geben Sie das Enddatum ein.";
$GLOBALS['TL_LANG']['tl_li_service']['repetition']['0'] = "Wiederholung";
$GLOBALS['TL_LANG']['tl_li_service']['repetition']['1'] = "Soll die Leistung wiederholt werden?";
$GLOBALS['TL_LANG']['tl_li_service']['period']['0'] = "Periode";
$GLOBALS['TL_LANG']['tl_li_service']['period']['1'] = "Bitte wählen Sie eine Periode.";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['1'] = "1 Monat";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['3'] = "3 Monate";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['6'] = "6 Monate";
$GLOBALS['TL_LANG']['tl_li_service']['periods']['12'] = "12 Monate";
$GLOBALS['TL_LANG']['tl_li_service']['new']['0'] = "Neue Leistung";
$GLOBALS['TL_LANG']['tl_li_service']['new']['1'] = "Eine neue Leistung anlegen";
$GLOBALS['TL_LANG']['tl_li_service']['edit']['0'] = "Leistung bearbeiten";
$GLOBALS['TL_LANG']['tl_li_service']['edit']['1'] = "Die Leistung mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_service']['copy']['0'] = "Leistung duplizieren";
$GLOBALS['TL_LANG']['tl_li_service']['copy']['1'] = "Die Leistung mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_service']['delete']['0'] = "Leistung löschen";
$GLOBALS['TL_LANG']['tl_li_service']['delete']['1'] = "Die Leistung mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_service']['show']['0'] = "Leistung anzeigen";
$GLOBALS['TL_LANG']['tl_li_service']['show']['1'] = "Die Leistung mit der ID %s anzeigen";
 
?>
