<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_invoice_category.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_invoice_category']['category_legend'] = "Rechnungskategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['orderNumber']['0'] = "Sortiernummer";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['orderNumber']['1'] = "Bitte geben Sie die Sortiernummer ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['cssClass']['0'] = "CSS Klasse";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['cssClass']['1'] = "Bitte geben Sie die CSS Klasse ein.";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['new']['0'] = "Neue Rechnungskategorie";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['new']['1'] = "Eine neue Rechnungskategorie anlegen";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['edit']['0'] = "Rechnungskategorie bearbeiten";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['edit']['1'] = "Die Rechnungskategorie mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['copy']['0'] = "Rechnungskategorie duplizieren";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['copy']['1'] = "Die Rechnungskategorie mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['delete']['0'] = "Rechnungskategorie löschen";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['delete']['1'] = "Die Rechnungskategorie mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['show']['0'] = "Rechnungskategorie anzeigen";
$GLOBALS['TL_LANG']['tl_li_invoice_category']['show']['1'] = "Die Rechnungskategorie mit der ID %s anzeigen";
 
?>
