<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_contact.php 
 * 
 * Contao extension: li_crm 0.3.1 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_li_contact']['contact_legend'] = "Kontakt";
$GLOBALS['TL_LANG']['tl_li_contact']['date_legend'] = "Datum und Zeit";
$GLOBALS['TL_LANG']['tl_li_contact']['note_legend'] = "Notiz";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment_legend'] = "Anlage";
$GLOBALS['TL_LANG']['tl_li_contact']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_li_contact']['title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_li_contact']['category']['0'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_li_contact']['category']['1'] = "Bitte wählen Sie die Kategorie aus.";
$GLOBALS['TL_LANG']['tl_li_contact']['startDate']['0'] = "Startdatum";
$GLOBALS['TL_LANG']['tl_li_contact']['startDate']['1'] = "Bitte geben Sie das Startdatum gemäß des globalen Datumsformats ein.";
$GLOBALS['TL_LANG']['tl_li_contact']['startTime']['0'] = "Startzeit";
$GLOBALS['TL_LANG']['tl_li_contact']['startTime']['1'] = "Bitte geben Sie die Startzeit gemäß des globalen Zeitformats ein.";
$GLOBALS['TL_LANG']['tl_li_contact']['addEnd']['0'] = "Ende hinzufügen";
$GLOBALS['TL_LANG']['tl_li_contact']['addEnd']['1'] = "Dem Kontakt Enddatum und -zeit hinzufügen.";
$GLOBALS['TL_LANG']['tl_li_contact']['endDate']['0'] = "Enddatum";
$GLOBALS['TL_LANG']['tl_li_contact']['endDate']['1'] = "Lassen Sie das Feld leer, um ein eintägiges Event zu erstellen.";
$GLOBALS['TL_LANG']['tl_li_contact']['endTime']['0'] = "Endzeit";
$GLOBALS['TL_LANG']['tl_li_contact']['endTime']['1'] = "Geben Sie dieselbe Start- und Endzeit ein, um ein Event mit offenem Ende zu erstellen.";
$GLOBALS['TL_LANG']['tl_li_contact']['result']['0'] = "Ergebnis";
$GLOBALS['TL_LANG']['tl_li_contact']['result']['1'] = "Bitte wählen Sie das Ergebnis aus.";
$GLOBALS['TL_LANG']['tl_li_contact']['direction']['0'] = "Richtung";
$GLOBALS['TL_LANG']['tl_li_contact']['direction']['1'] = "Bitte wählen Sie die Richtung aus.";
$GLOBALS['TL_LANG']['tl_li_contact']['note']['0'] = "Notiz";
$GLOBALS['TL_LANG']['tl_li_contact']['note']['1'] = "Bitte geben Sie die Notiz ein.";
$GLOBALS['TL_LANG']['tl_li_contact']['addAttachment']['0'] = "Anlage hinzufügen";
$GLOBALS['TL_LANG']['tl_li_contact']['addAttachment']['1'] = "Dem Kontakt eine Anlage hinzufügen.";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment']['0'] = "Anlage";
$GLOBALS['TL_LANG']['tl_li_contact']['attachment']['1'] = "Bitte wählen Sie eine Anlage aus.";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['phone'] = "Telefonat";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['email'] = "E-Mail";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['mail'] = "Brief";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['fax'] = "Fax";
$GLOBALS['TL_LANG']['tl_li_contact']['categories']['direct'] = "Kundenbesuch";
$GLOBALS['TL_LANG']['tl_li_contact']['results']['reached'] = "Erreicht";
$GLOBALS['TL_LANG']['tl_li_contact']['results']['not_reached'] = "Nicht erreicht";
$GLOBALS['TL_LANG']['tl_li_contact']['directions']['incoming'] = "Eingehend";
$GLOBALS['TL_LANG']['tl_li_contact']['directions']['outgoing'] = "Ausgehend";
$GLOBALS['TL_LANG']['tl_li_contact']['new']['0'] = "Neuer Kontakt";
$GLOBALS['TL_LANG']['tl_li_contact']['new']['1'] = "Einen neuen Kontakt anlegen";
$GLOBALS['TL_LANG']['tl_li_contact']['edit']['0'] = "Kontakt bearbeiten";
$GLOBALS['TL_LANG']['tl_li_contact']['edit']['1'] = "Den Kontakt mit der ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_li_contact']['copy']['0'] = "Kontakt duplizieren";
$GLOBALS['TL_LANG']['tl_li_contact']['copy']['1'] = "Den Kontakt mit der ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_li_contact']['delete']['0'] = "Kontakt löschen";
$GLOBALS['TL_LANG']['tl_li_contact']['delete']['1'] = "Den Kontakt mit der ID %s löschen";
$GLOBALS['TL_LANG']['tl_li_contact']['show']['0'] = "Kontakt anzeigen";
$GLOBALS['TL_LANG']['tl_li_contact']['show']['1'] = "Den Kontakt mit der ID %s anzeigen";
 
?>
