<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_li_company_settings.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_li_company_settings']['edit'] = "Unternehmenseinstellungen bearbeiten";
$GLOBALS['TL_LANG']['tl_li_company_settings']['company_legend'] = "Unternehmen";
$GLOBALS['TL_LANG']['tl_li_company_settings']['address_legend'] = "Adresse";
$GLOBALS['TL_LANG']['tl_li_company_settings']['bank_legend'] = "Bank";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_name']['0'] = "Name des Unternehmens";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_name']['1'] = "Bitte geben Sie den Namen Ihres Unternehmens ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_default_currency']['0'] = "Standardwährung";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_default_currency']['1'] = "Bitte wählen Sie die Standardwährung Ihres Unternehmens aus.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_tax_number']['0'] = "Steuernummer";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_tax_number']['1'] = "Bitte geben Sie die Steuernummer Ihres Unternehmens ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_ustid']['0'] = "Ust-IdNr";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_ustid']['1'] = "Bitte geben Sie die Ust-IdNr Ihres Unternehmens ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_postal']['0'] = "Postleitzahl";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_company_postal']['1'] = "Bitte geben Sie die Postleitzahl ohne führende Nullen ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_account_number']['0'] = "Kontonummer";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_account_number']['1'] = "Bitte geben Sie Ihre Kontonummer Ihres Kontos ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank_code']['0'] = "BLZ";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank_code']['1'] = "Bitte geben Sie die BLZ Ihrer Bank ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank']['0'] = "Bank";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bank']['1'] = "Bitte geben Sie den Namen Ihrer Bank ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_iban']['0'] = "IBAN";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_iban']['1'] = "Bitte geben Sie Ihre IBAN ein.";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bic']['0'] = "BIC";
$GLOBALS['TL_LANG']['tl_li_company_settings']['li_crm_bic']['1'] = "Bitte geben Sie Ihr BIC ein.";