<?php
/**
 * TL_ROOT/system/modules/li_crm/languages/de/tl_member.php 
 * 
 * Contao extension: li_crm 0.4.0 alpha1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : MIT 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Christian Kolb (Liplex), www.liplex.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['customer_legend'] = "Kunde";
$GLOBALS['TL_LANG']['tl_member']['isCustomer']['0'] = "Kunde";
$GLOBALS['TL_LANG']['tl_member']['isCustomer']['1'] = "Ist das Mitglied ein Kunde?";
$GLOBALS['TL_LANG']['tl_member']['customerNumber']['0'] = "Kundennummer";
$GLOBALS['TL_LANG']['tl_member']['customerNumber']['1'] = "Bitte geben Sie die Kundennummer ein.";
$GLOBALS['TL_LANG']['tl_member']['customerName']['0'] = "Kundenname";
$GLOBALS['TL_LANG']['tl_member']['customerName']['1'] = "Bitte geben Sie den Kundennamen ein.";
$GLOBALS['TL_LANG']['tl_member']['customerColor']['0'] = "Einfärbung";
$GLOBALS['TL_LANG']['tl_member']['customerColor']['1'] = "Diese Farbe wird für die Anzeige der geschriebenen Stunden für diesen Kunden verwendet.";
 
?>
